Added the '-product' option in 'create_k8s' to target a specific product

diff --git a/padogrid-deployment/src/main/resources/hazelcast/bin_sh/create_k8s b/padogrid-deployment/src/main/resources/hazelcast/bin_sh/create_k8s
--- a/padogrid-deployment/src/main/resources/hazelcast/bin_sh/create_k8s
+++ b/padogrid-deployment/src/main/resources/hazelcast/bin_sh/create_k8s
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash 
 
 # ========================================================================
-# Copyright (c) 2020 Netcrest Technologies, LLC. All rights reserved.
+# Copyright (c) 2020-2021 Netcrest Technologies, LLC. All rights reserved.
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
@@ -23,13 +23,18 @@ EXECUTABLE="`basename $0`"
 
 __options()
 {
-   echo "-k8s -cluster -?"
+   echo "-product -k8s -cluster -?"
 }
 
 if [ "$OPTIONS" == "true" ]; then
    __options
    exit
 fi
+
+PRODUCT_OPTIONS=$(echo "$K8S_PRODUCT_LIST" | sed 's/ /|/g')
+PRODUCTS_SUPPORTED=$(echo "$K8S_PRODUCT_LIST" | sed 's/ /, /g')
+THIS_PRODUCT="$(basename $(dirname $SCRIPT_DIR))"
+K8S_OPTIONS=$(getK8sOptions)
 
 if [ "$HELP" == "true" ]; then
 cat <<EOF
@@ -41,7 +46,10 @@ NAME
    $EXECUTABLE - Create a Kubernetes environment in the current padogrid workspace
 
 SYNOPSIS
-   $EXECUTABLE [-k8s minikube|gke] -cluster cluster_name [-?]
+   $EXECUTABLE [-product $PRODUCT_OPTIONS]
+              [-k8s minikube|gke]
+              -cluster cluster_name
+              [-?]
 
 DESCRIPTION
    Creates a Kubernetes environment that includes Hazelcast deployment files for
@@ -56,6 +64,9 @@ DESCRIPTION
    comes with a document describing the prerequisites and detailed instructions.
 
 OPTIONS
+   -product $PRODUCT_OPTIONS
+             Kubernetes cluster product name. Supported products are $PRODUCTS_SUPPORTED.
+
    -k8s minikube
              Minikube on your local machine.
 
@@ -66,14 +77,14 @@ OPTIONS
              Minishift on your local machine.
 
    -cluster cluster_name
-             Required Kubernetes cluster name. This name is used to create
-             a cluster in the cloud platform if it does not exist.
+             Required Kubernetes cluster name. This name is used to create a cluster in
+             the cloud platform if it does not exist.
 
 EOF
 if [ "$MAN_SPECIFIED" == "false" ]; then
 cat <<EOF
 DEFAULT
-   $EXECUTABLE -k8s $DEFAULT_K8S -cluster cluster_name
+   $EXECUTABLE -product $THIS_PRODUCT -k8s $DEFAULT_K8S -cluster cluster_name
 
 FILES
    $PADOGRID_WORKSPACE/k8s
@@ -82,6 +93,28 @@ FILES
 EOF
 fi
    exit
+fi
+
+#
+# Run the target k8s command if the product is different.
+#
+if [ "$PRODUCT_ARG" != "" ]; then
+   if [ "$(containsWord "$DOCKER_PRODUCT_LIST" "$PRODUCT_ARG")" == "false" ]; then
+      >&2 echo -e "${CLightRed}ERROR:${CNone} Specified product is not supported: [$PRODUCT_ARG]. Command aborted."
+      exit 1
+   fi
+   if [ "$THIS_PRODUCT" != "$PRODUCT_ARG" ] && [ "$PRODUCT_ARG" != "jet" ]; then
+      $PADOGRID_HOME/$PRODUCT_ARG/bin_sh/$EXECUTABLE "$@"
+      exit
+   fi
+   if [ "$PRODUCT_ARG" == "jet" ]; then
+      CLUSTER_TYPE="jet"
+    else
+      CLUSTER_TYPE="imdg"
+    fi
+else
+   # Default product is hazelcast and hence CLUSTER_TYPE is "imdg"
+   CLUSTER_TYPE="imdg"
 fi
 
 if [ "$CLUSTER_SPECIFIED" == "false" ]; then
@@ -225,6 +258,7 @@ fi
 #
 echo ""
 echo "     WORKSPACE: $PADOGRID_WORKSPACE"
+echo -e "       Product: ${CLightGreen}$CLUSTER_TYPE${CNone}"
 echo "    Kubernetes: $K8S"
 echo "Kubernetes Environment:"
 echo "   $CLUSTER_DIR"
