Fixed vm key issue

diff --git a/padogrid-deployment/src/main/resources/hazelcast/bin_sh/vm_test b/padogrid-deployment/src/main/resources/hazelcast/bin_sh/vm_test
--- a/padogrid-deployment/src/main/resources/hazelcast/bin_sh/vm_test
+++ b/padogrid-deployment/src/main/resources/hazelcast/bin_sh/vm_test
@@ -165,17 +165,19 @@ if [ "$VM_PRIVATE_KEY_FILE" == "" ]; then
    fi
 fi
 KEY_FILE=`getClusterProperty "vm.privateKeyFile"`
-if [ "$KEY_FILE" != "" ]; then 
-   VM_KEY="$KEY_FILE"
-elif [ "$VM_PRIVATE_KEY_FILE" != "" ]; then
+if [ "$KEY_FILE" == "" ]; then 
    KEY_FILE="$VM_PRIVATE_KEY_FILE"
 fi
 if [ ! -f "$KEY_FILE" ]; then
-   echo >&2 "ERROR: Specified private key does not exist [$KEY_FILE]."
+   echo >&2 "ERROR: Private key does not exist [$KEY_FILE]."
    echo >&2 "       Command aborted."
    exit 1
 fi
-VM_KEY="-i $KEY_FILE"
+if [ "$KEY_FILE" == "" ]; then
+   VM_KEY=""
+else
+   VM_KEY="-i $KEY_FILE"
+fi
 
 # Fail fast: Exit if any of the hosts is not reachable
 for VM_HOST in $__VM_HOSTS; do
