Updated Hazelcast dashboards

diff --git a/padogrid-deployment/src/main/resources/common/apps/grafana/bin_sh/delete_folder b/padogrid-deployment/src/main/resources/common/apps/grafana/bin_sh/delete_folder
--- a/padogrid-deployment/src/main/resources/common/apps/grafana/bin_sh/delete_folder
+++ b/padogrid-deployment/src/main/resources/common/apps/grafana/bin_sh/delete_folder
@@ -53,7 +53,7 @@ fi
 
 __UID=`./get_folder_uid -folder $FOLDER`
 if [ "$__UID" == "" ]; then
-   echo "${CError}ERROR:${CNone} Folder not found [$FOLDER]. Command aborted."
+   echo -e >&2 "${CError}ERROR:${CNone} Folder not found [$FOLDER]. Command aborted."
    exit 1
 fi
 
