Added Hazelcast workflow example config files

diff --git a/padogrid-deployment/src/main/resources/common/apps/grafana/bin_sh/export_folder b/padogrid-deployment/src/main/resources/common/apps/grafana/bin_sh/export_folder
--- a/padogrid-deployment/src/main/resources/common/apps/grafana/bin_sh/export_folder
+++ b/padogrid-deployment/src/main/resources/common/apps/grafana/bin_sh/export_folder
@@ -53,7 +53,13 @@ exit
 fi
 
 if [ "$FOLDER" != "" ]; then
-   FOLDERS=$FOLDER
+   __UID=`./get_folder_uid -folder $FOLDER`
+   if [ "$__UID" == "" ]; then
+      echo -e >&2 "${CError}ERROR:${CNone} Specified folder not found in Grafana [$FOLDER]. Command aborted."
+      exit 1
+   else
+      FOLDERS=$FOLDER
+   fi
 elif [ "$ALL" != "true" ]; then
    FOLDERS=$DEFAULT_FOLDER
 else
@@ -74,7 +80,7 @@ else
 fi
 
 if [ "$FOLDERS" == "" ]; then
-   echo "Folders not found in Grafana. Command aboarded."
+   echo -e >&2 "${CError}ERROR:${CNone} Folders not found in Grafana. Command aborted."
    exit 1
 fi
    
diff --git a/padogrid-deployment/src/main/resources/common/apps/grafana/bin_sh/get_dashboards b/padogrid-deployment/src/main/resources/common/apps/grafana/bin_sh/get_dashboards
--- a/padogrid-deployment/src/main/resources/common/apps/grafana/bin_sh/get_dashboards
+++ b/padogrid-deployment/src/main/resources/common/apps/grafana/bin_sh/get_dashboards
@@ -53,7 +53,7 @@ fi
 
 __ID=`./get_folder_id -folder $FOLDER`
 if [ "$__ID" == "" ]; then
-   echo "ERROR: Folder not found [$FOLDER]. Command aborted."
+   echo -e >&2 "${CError}ERROR:${CNone} Folder not found [$FOLDER]. Command aborted."
    exit 1
 fi
 
diff --git a/padogrid-deployment/src/main/resources/common/apps/grafana/bin_sh/get_folder b/padogrid-deployment/src/main/resources/common/apps/grafana/bin_sh/get_folder
--- a/padogrid-deployment/src/main/resources/common/apps/grafana/bin_sh/get_folder
+++ b/padogrid-deployment/src/main/resources/common/apps/grafana/bin_sh/get_folder
@@ -53,4 +53,9 @@ fi
 
 __UID=`./get_folder_uid -folder $FOLDER`
 
+if [ "$__UID" == "" ]; then
+   echo -e >&2 "${CError}ERROR:${CNone} Specified folder not found in Grafana [$FOLDER]. Command aborted."
+   exit 1
+fi
+
 curl -sS $GRAFANA_URL/api/folders/$__UID | jq .
