Aligned group configuration with other components

diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/create_group b/padogrid-deployment/src/main/resources/common/bin_sh/create_group
--- a/padogrid-deployment/src/main/resources/common/bin_sh/create_group
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/create_group
@@ -50,16 +50,10 @@ SYNOPSIS
 
 DESCRIPTION
    Creates multiple clusters in the current workspace. Once the clusters are created,
-   you can reconfigured each cluster by editing the followig file in their cluster directory.
+   you can reconfigure each cluster by editing the followig file in their respective
+   cluster directory.
 
    etc/cluster.properties
-
-   If the group is the first group created for the workspace, then it is set as the default group
-   so that it can be managed without specifying the '-group' option of the '_group' commands.
-   You can change the default group by setting the followling property in the workspace 
-   'etc/clusters.properties' file.
-
-   clusters.group.default=mygroup
 
 OPTIONS
    -product product_name
@@ -103,10 +97,6 @@ cat <<EOF
 DEFAULT
    $EXECUTABLE -prefix grid -count 2 -type default
 
-FILES
-   $PADOGRID_WORKSPACE/etc/clusters.properties
-             The current workspace group file.
-
 EOF
 fi
 cat <<EOF
@@ -114,6 +104,16 @@ SEE ALSO
 EOF
    printSeeAlsoList "make_cluster *_group" $EXECUTABLE
    exit
+fi
+
+if [ "$GROUP" == "" ]; then
+   GROUP="mygroup"
+fi
+GROUP_DIR="$PADOGRID_WORKSPACE/groups/$GROUP"
+
+if [ -d "$GROUP_DIR" ]; then
+   echo >&2 -e "${CLightRed}ERROR:${CNone} Specified group already exists: [$GROUP]. Command aborted."
+   exit 1
 fi
 
 if [ "$PRODUCT_ARG" == "" ]; then
@@ -186,25 +186,10 @@ for i in $(seq 0 $LAST_CLUSTER_NUM); do
    fi
 done
 
-
-if [ "$GROUP" == "" ]; then
-   GROUP="mygroup"
-fi
-
-GROUP_NAMES=""
-CLUSTER_NAMES=""
-if [ -f "$PADOGRID_WORKSPACE/etc/clusters.properties" ]; then
-   GROUP_NAMES=$(getProperty "$PADOGRID_WORKSPACE/etc/clusters.properties" "clusters.group.names")
-   CLUSTER_NAMES=$(getProperty "$PADOGRID_WORKSPACE/etc/clusters.properties" "clusters.$GROUP.cluster.names")
-   if [ "$CLUSTER_NAMES" != "" ]; then
-      echo -e >&2 "${LightRed}ERROR:${CNone} The cluster group already exists: [$GROUP]. Command aborted."
-      exit 1
-   fi
-fi
-
 #
 # Generate base clusters
 #
+CLUSTER_NAMES=""
 if [ "$PORT_ARG" != "" ]; then
    FIRST_START_PORT="$PORT_ARG"
 else
@@ -366,30 +351,26 @@ if [ "$TYPE_ARG" == "pado" ]; then
 fi
 
 # Group the grid (cluster) IDs
-
-if [ "$GROUP_NAMES" == "" ]; then
-   GROUP_NAMES="$GROUP"
-else
-   GROUP_NAMES="$GROUP_NAMES, $GROUP"
-fi
-
-if [ ! -d "$PADOGRID_WORKSPACE/etc" ]; then
-   mkdir "$PADOGRID_WORKSPACE/etc"
-fi
-
-if [ ! -f "$PADOGRID_WORKSPACE/etc/clusters.properties" ]; then
-   echo "#" > "$PADOGRID_WORKSPACE/etc/clusters.properties"
-   echo "# This file contains workspace-wide cluster specific properties." >> "$PADOGRID_WORKSPACE/etc/clusters.properties"
-   echo "#" >> "$PADOGRID_WORKSPACE/etc/clusters.properties"
-   echo "" >> "$PADOGRID_WORKSPACE/etc/clusters.properties"
-   echo "# Default group" >> "$PADOGRID_WORKSPACE/etc/clusters.properties"
-   echo "clusters.group.default=$GROUP" >> "$PADOGRID_WORKSPACE/etc/clusters.properties"
-   echo "" >> "$PADOGRID_WORKSPACE/etc/clusters.properties"
-   echo "# Enter comma separated cluster group names" >> "$PADOGRID_WORKSPACE/etc/clusters.properties"
-   echo "clusters.group.names=$GROUP_NAMES" >> "$PADOGRID_WORKSPACE/etc/clusters.properties"
-else
-   setProperty "$PADOGRID_WORKSPACE/etc/clusters.properties" "clusters.group.names" "$GROUP_NAMES"
-fi
-echo "" >> "$PADOGRID_WORKSPACE/etc/clusters.properties"
-echo "# $GROUP - Enter comma separated cluster names" >> "$PADOGRID_WORKSPACE/etc/clusters.properties"
-echo "clusters.$GROUP.cluster.names=$CLUSTER_NAMES" >> "$PADOGRID_WORKSPACE/etc/clusters.properties"
+mkdir -p "$GROUP_DIR/etc"
+GROUP_FILE="$GROUP_DIR/etc/group.properties"
+echo "#" > "$GROUP_FILE"
+echo "# This file contains group specific properties." >> "$GROUP_FILE"
+echo "#" >> "$GROUP_FILE"
+echo "" >> "$GROUP_FILE"
+echo "# Group name" >> "$GROUP_FILE"
+echo "group.name=$GROUP" >> "$GROUP_FILE"
+echo "" >> "$GROUP_FILE"
+echo "# Cluster name prefix" >> "$GROUP_FILE"
+echo "group.cluster.prefix=$PREFIX" >> "$GROUP_FILE"
+echo "" >> "$GROUP_FILE"
+echo "# Comma separated cluster names" >> "$GROUP_FILE"
+echo "group.cluster.names=$CLUSTER_NAMES" >> "$GROUP_FILE"
+echo "" >> "$GROUP_FILE"
+echo "# Product" >> "$GROUP_FILE"
+echo "group.product=$PRODUCT_ARG" >> "$GROUP_FILE"
+echo "" >> "$GROUP_FILE"
+echo "# Type (default or pado)" >> "$GROUP_FILE"
+echo "group.type=$TYPE_ARG" >> "$GROUP_FILE"
+echo "" >> "$GROUP_FILE"
+echo "# First port" >> "$GROUP_FILE"
+echo "group.firstPort=$FIRST_START_PORT" >> "$GROUP_FILE"
diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/kill_group b/padogrid-deployment/src/main/resources/common/bin_sh/kill_group
--- a/padogrid-deployment/src/main/resources/common/bin_sh/kill_group
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/kill_group
@@ -55,7 +55,7 @@ DESCRIPTION
 
 OPTIONS
    -group group_name
-             Group name. If not specified, then it kills the 'default' group of clusters.
+             Group name. If not specified, then it kills the current group.
 
    -workspace workspace_name
              Workspace name. If not specified, then it kills the group of clusters in the current workspace.
@@ -71,10 +71,6 @@ cat <<EOF
 DEFAULT
    $EXECUTABLE -workspace $WORKSPACE -group default
 
-FILES
-   $PADOGRID_WORKSPACE/etc/clusters.properties
-             The current workspace group file.
-
 EOF
 fi
 cat <<EOF
@@ -84,26 +80,21 @@ EOF
    exit
 fi
 
-CLUSTERS_FILE="$PADOGRID_WORKSPACES_HOME/$WORKSPACE/etc/clusters.properties"
-
-if [ ! -f "$CLUSTERS_FILE" ]; then
-   echo -e >&2 "${CLightRed}ERROR:${CNone} No cluster groups found in the workspace. Run 'create_group' to create one. Command aborted."
+if [ "$(isValidWorkspace $WORKSPACE)" == "false" ]; then
+   echo -e >&2 "${CLightRed}ERROR:${CNone} Specified workspace does not exist: [$WORKSPACE]. Command aborted."
    exit 1
 fi
-   
 
 if [ "$GROUP" == "" ]; then
-   GROUP="default"
+   echo -e >&2 "${CLightRed}ERROR:${CNone} '-group' not specified. Command aborted."
+   exit 1
 fi
 
-if [ "$GROUP" = "default" ]; then
-   GROUP=$(getProperty "$CLUSTERS_FILE" "clusters.group.default")
-fi
+GROUP_DIR="$PADOGRID_WORKSPACES_HOME/$WORKSPACE/groups/$GROUP"
+GROUP_FILE="$GROUP_DIR/etc/group.properties"
 
-if [ "$GROUP" == "" ]; then
-   echo -e >&2 "${CLightRed}ERROR:${CNone} Default group undefined. Please set the 'clusters.group.default' property in the following file:"
-   echo -e >&2 "       $CLUSTERS_FILE"
-   echo -e >&2 "       Command aborted."
+if [ ! -f "$GROUP_FILE" ]; then
+   echo -e >&2 "${CLightRed}ERROR:${CNone} Specified group not found. Run 'create_group' to create one. Command aborted."
    exit 1
 fi
 
@@ -111,7 +102,7 @@ CURRENT_DIR="`pwd`"
 CURRENT_WORKSPACE="`basename $PADOGRID_WORKSPACE`"
 CURRENT_CLUSTER=$CLUSTER
 
-CLUSTER_NAMES=$(getProperty "$CLUSTERS_FILE" "clusters.$GROUP.cluster.names")
+CLUSTER_NAMES=$(getProperty "$GROUP_FILE" "group.cluster.names")
 
 if [ "$CURRENT_WORKSPACE" != "$WORKSPACE" ]; then
    switch_workspace $WORKSPACE
diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/remove_group b/padogrid-deployment/src/main/resources/common/bin_sh/remove_group
--- a/padogrid-deployment/src/main/resources/common/bin_sh/remove_group
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/remove_group
@@ -50,10 +50,15 @@ SYNOPSIS
    $EXECUTABLE [-group group_name] [-workspace workspace_name] [-kill] [-simulate] [-quiet] [-?]
 
 DESCRIPTION
-   Permanently removes the specified group of clusters from the specified workspace. This command 
-   iteratively invokes the 'remove_cluster' to remove each cluster. Note that the 'remove_cluster'
-   command aborts if the cluster is still running. To override this behavior, specify the '-kill'
-   option to first kill the cluster before removing it.
+   Permanently removes the specified group of clusters from the specified workspace. This command
+   aborts if any of the clusters has active (running) members. Note that it only checks the
+   active members and not other components such as locators, mangement center, leaders, masters,
+   and etc. If no active members are found then it first kills all remaining components if any
+   and removes the group.
+
+   If it aborts due to the active members, then you can run the 'stop_group' command to 
+   stop the clusters before runnning this command again. You can also suppress the active
+   member verification step by specifying the '-kill' option.
 
    By default, this command runs in the interactive mode if the '-quiet' option is not specified.
 
@@ -82,10 +87,6 @@ cat <<EOF
 DEFAULT
    $EXECUTABLE -workspace $WORKSPACE -group group_name
 
-FILES
-   $PADOGRID_WORKSPACE/etc/clusters.properties
-             The current workspace group file.
-
 EOF
 fi
 cat <<EOF
@@ -95,8 +96,21 @@ EOF
    exit
 fi
 
+if [ "$(isValidWorkspace $WORKSPACE)" == "false" ]; then
+   echo -e >&2 "${CLightRed}ERROR:${CNone} Specified workspace does not exist: [$WORKSPACE]. Command aborted."
+   exit 1
+fi
+
 if [ "$GROUP" == "" ]; then
    echo -e >&2 "${CLightRed}ERROR:${CNone} Group name required. Use '-group' to specify the group to remove.  Command aborted."
+   exit 1
+fi
+
+GROUP_DIR="$PADOGRID_WORKSPACES_HOME/$WORKSPACE/groups/$GROUP"
+GROUP_FILE="$GROUP_DIR/etc/group.properties"
+
+if [ ! -f "$GROUP_FILE" ]; then
+   echo -e >&2 "${CLightRed}ERROR:${CNone} Specified group not found. Command aborted."
    exit 1
 fi
 
@@ -105,28 +119,11 @@ if [ "$SIMULATE" == "true" ]; then
    QUIET=$SIMULATE
 fi
 
-CLUSTERS_FILE="$PADOGRID_WORKSPACES_HOME/$WORKSPACE/etc/clusters.properties"
-
-if [ ! -f "$CLUSTERS_FILE" ]; then
-   echo -e >&2 "${CLightRed}ERROR:${CNone} No cluster groups found in the workspace. Command aborted."
-   exit 1
-fi
-   
 CURRENT_DIR="`pwd`"
 CURRENT_WORKSPACE="`basename $PADOGRID_WORKSPACE`"
 CURRENT_CLUSTER=$CLUSTER
 
-CLUSTER_NAMES_COMMAS=$(getProperty "$CLUSTERS_FILE" "clusters.$GROUP.cluster.names")
-
-if [ "$CLUSTER_NAMES_COMMAS" == "" ]; then
-   echo -e >&2 "${CLightRed}ERROR:${CNone} Group name undefined in the workspace. Command aborted."
-   exit 1
-fi
-
-if [ "$(isValidWorkspace $WORKSPACE)" == "false" ]; then
-   echo -e >&2 "${CLightRed}ERROR:${CNone} Specified workspace does not exist: [$WORKSPACE]. Command aborted."
-   exit 1
-fi
+CLUSTER_NAMES_COMMAS=$(getProperty "$GROUP_FILE" "group.cluster.names")
 
 if [ "$QUIET" == "false" ]; then
    echo ""
@@ -150,6 +147,26 @@ fi
 
 CLUSTER_NAMES=$(echo $CLUSTER_NAMES_COMMAS | sed 's/,/ /g')
 
+# First, check to see if cluster members are running. If so, abort.
+# Note that it only checks cluster members. If no members are running then it
+# sets KILL=true so that it kills non-member components before removing the group.
+COUNT=0
+if [ "$KILL" != "true" ]; then
+   echo "Cluster Members Running:"
+   for i in $CLUSTER_NAMES; do
+      MEMBER_COUNT=$(getActiveMemberCount $WORKSPACE $i)
+      let COUNT=COUNT+MEMBER_COUNT
+      echo "   $i - $MEMBER_COUNT"
+   done
+fi
+if [ "$COUNT" -gt 0 ]; then
+   echo -e "${CLightRed}ERROR:${CNone} One or more clusters are still active. Stop the clusters first and try again."
+   echo "       Specify the '-kill' option to override this message. Command aborted."
+   exit 1
+else
+   KILL="true"
+fi
+
 # Back up group in the workspaces/bundles directory.
 GROUP_ARCHIVE_FILE="$PADOGRID_WORKSPACES_HOME/.archive/$GROUP-clusters-group.tar.gz"
 if [ ! -d $PADOGRID_WORKSPACES_HOME/.archive ]; then
@@ -167,7 +184,7 @@ if [ "$SIMULATE" != "true" ]; then
    popd > /dev/null 2>&1
 else
    echo "Simulating group backup..."
-   echo tar -czf $GROUP_ARCHIVE_FILE $CLUSTER_NAMES
+   echo "   tar -czf $GROUP_ARCHIVE_FILE $CLUSTER_NAMES"
 fi
 
 if [ "$KILL" == "true" ]; then
@@ -178,45 +195,26 @@ if [ "$KILL" == "true" ]; then
       done
    else
       echo "Simulating group kill..."
+      for i in $CLUSTER_NAMES; do
+         echo "   kill_cluster -all -cluster $i"
+      done
    fi
-   echo ""
 fi
 
 if [ "$SIMULATE" != "true" ]; then
-   pushd "$PADOGRID_WORKSPACES_HOME/$WORKSPACE/clusters" > /dev/null 2>&1
    echo "Removing group: [$GROUP]..."
    for i in $CLUSTER_NAMES; do
       remove_cluster -cluster $i -quiet
    done
-   popd > /dev/null 2>&1
-   GROUP_NAMES_COMMAS=$(getProperty "$CLUSTERS_FILE" "clusters.group.names")
-   GROUP_NAMES=$(echo $GROUP_NAMES_COMMAS | sed 's/,/ /g')
-   NEW_GROUP_NAMES_COMMAS=""
-   NEW_FIRST_GROUP=""
-   for i in $GROUP_NAMES; do
-      if [ "$i" != "$GROUP" ]; then
-         if [ "$NEW_GROUP_NAMES_COMMAS" = "" ]; then
-            NEW_GROUP_NAMES_COMMAS="$i"
-            NEW_FIRST_GROUP="$i"
-         else
-            NEW_GROUP_NAMES_COMMAS="$NEW_GROUP_NAMES_COMMAS, $i"
-         fi
-      fi
-   done
-   setProperty "$CLUSTERS_FILE" "clusters.group.names" "$NEW_GROUP_NAMES_COMMAS"
-   sed -i${__SED_BACKUP} -e '/clusters.'$GROUP'.cluster.names/d' -e '/#.*'$GROUP'/d' "$CLUSTERS_FILE"
-   DEFAULT_GROUP=$(getProperty "$CLUSTERS_FILE" "clusters.group.default")
-   # If the default group has been removed then set the first group in the list
-   # as the default group.
-   if [ "$DEFAULT_GROUP" == "$GROUP" ]; then
-      setProperty "$CLUSTERS_FILE" "clusters.group.default" "$NEW_FIRST_GROUP"
-      echo -e "The default group has been changed from ${CLightRed}$GROUP${CNone} to ${CLightGreen}$NEW_FIRST_GROUP${CNone}."
+   if [ -d "$GROUP_DIR" ]; then
+       rm -rf "$GROUP_DIR"
    fi
 else
    echo "Simulating group removal..."
    for i in $CLUSTER_NAMES; do
-      echo remove_cluster -cluster $i -quiet
+      echo "   remove_cluster -cluster $i -quiet"
    done
+   echo "   rm -rf $GROUP_DIR"
 fi
 
 if [ "$CURRENT_WORKSPACE" != "$WORKSPACE" ]; then
diff --git a/padogrid-deployment/src/main/resources/geode/bin_sh/shutdown_cluster b/padogrid-deployment/src/main/resources/geode/bin_sh/shutdown_cluster
--- a/padogrid-deployment/src/main/resources/geode/bin_sh/shutdown_cluster
+++ b/padogrid-deployment/src/main/resources/geode/bin_sh/shutdown_cluster
@@ -71,11 +71,6 @@ fi
 
 retrieveClusterEnvFile $PADOGRID_WORKSPACE/clusters/$CLUSTER
 
-if [ ! -d $CLUSTER_DIR ]; then
-   >&2 echo "ERROR: The specified cluster does not exist: [$CLUSTER]. Command aborted."
-   exit 1
-fi
-
 #
 # Run the target cluster command if the product is different.
 #
@@ -85,6 +80,11 @@ if [ "$PRODUCT_CLUSTER_SPECIFIED" == "false" ]; then
       $PADOGRID_HOME/$PRODUCT/bin_sh/$EXECUTABLE -product-cluster $CLUSTER "$@"
       exit
    fi
+fi
+
+if [ ! -d $CLUSTER_DIR ]; then
+   >&2 echo "ERROR: The specified cluster does not exist: [$CLUSTER]. Command aborted."
+   exit 1
 fi
 
 # Get workspace name
