Added support for bundle products and alphanumeric order for component types

diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/create_bundle b/padogrid-deployment/src/main/resources/common/bin_sh/create_bundle
--- a/padogrid-deployment/src/main/resources/common/bin_sh/create_bundle
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/create_bundle
@@ -171,10 +171,26 @@ if [ "$ALL" = "true" ]; then
 else
    FILE_PREFIX=""
    FILE_POSTFIX=""
+   FILE_APP=""
+   FILE_CLUSTER=""
+   FILE_DOCKER=""
+   FILE_K9S=""
+   FILE_POD=""
    INCLUDE_CLUSTER="false"
    if ( [ "$APP_SPECIFIED" == "false" ] && [ "$POD_SPECIFIED" == "false" ] &&  [ "$DOCKER_SPECIFIED" == "false" ] &&  [ "$K8S_SPECIFIED" == "false" ]) ||
       ( [ "$CLUSTER_SPECIFIED" == "true" ] ); then
       INCLUDE_CLUSTER="true"
+   fi
+   if [ "$APP" != "" ]; then
+      if  [ "`isAppExist $APP`" == "false" ]; then 
+         echo "----------------------------------------------------------------"
+         echo "WORKSPACE: $PADOGRID_WORKSPACE"
+         echo "    ERROR: Undefined app: [$APP]. Command aborted."
+         echo "----------------------------------------------------------------"
+         exit 1
+      fi
+      APPS="$APP"
+      FILE_TRAIL="app-$APPS"
    fi
    if [ "$INCLUDE_CLUSTER" == "true" ]; then
       if [ "$CLUSTER" != "" ]; then
@@ -185,28 +201,12 @@ else
             echo "----------------------------------------------------------------"
             exit 1
          fi
-         FILE_PREFIX="cluster"
-         FILE_POSTFIX=$CLUSTER
-         CLUSTERS=$CLUSTER
+         CLUSTERS="$CLUSTER"
+         if [ "$FILE_TRAIL" != "" ]; then
+            FILE_TRAIL="${FILE_TRAIL}-"
+         fi
+         FILE_TRAIL="${FILE_TRAIL}cluster-${CLUSTERS}"
       fi
-   fi
-   if [ "$APP" != "" ]; then
-      if  [ "`isAppExist $APP`" == "false" ]; then 
-         echo "----------------------------------------------------------------"
-         echo "WORKSPACE: $PADOGRID_WORKSPACE"
-         echo "    ERROR: Undefined app: [$APP]. Command aborted."
-         echo "----------------------------------------------------------------"
-         exit 1
-      fi
-      if [ "$FILE_PREFIX" != "" ]; then
-         FILE_PREFIX="${FILE_PREFIX}-"
-      fi
-      FILE_PREFIX="${FILE_PREFIX}app"
-      if [ "$FILE_POSTFIX" != "" ]; then
-         FILE_POSTFIX="${FILE_POSTFIX}-"
-      fi
-      FILE_POSTFIX="${FILE_POSTFIX}$APP"
-     APPS=$APP
    fi
    if [ "$DOCKER" != "" ]; then
       if  [ "`isDockerExist $DOCKER`" == "false" ]; then
@@ -216,15 +216,11 @@ else
          echo "----------------------------------------------------------------"
          exit 1
       fi
-      if [ "$FILE_PREFIX" != "" ]; then
-         FILE_PREFIX="${FILE_PREFIX}-"
+      DOCKERS="$DOCKER"
+      if [ "$FILE_TRAIL" != "" ]; then
+         FILE_TRAIL="${FILE_TRAIL}-"
       fi
-      FILE_PREFIX="${FILE_PREFIX}docker"
-      if [ "$FILE_POSTFIX" != "" ]; then
-         FILE_POSTFIX="${FILE_POSTFIX}-"
-      fi
-      FILE_POSTFIX="${FILE_POSTFIX}$DOCKER"
-      DOCKER_CLUSTERS=$DOCKER
+      FILE_TRAIL="${FILE_TRAIL}docker-${DOCERS}"
    fi
    if [ "$K8S" != "" ]; then
       if  [ "`isK8sExist $K8S`" == "false" ]; then
@@ -234,15 +230,11 @@ else
          echo "----------------------------------------------------------------"
          exit 1
       fi
-      if [ "$FILE_PREFIX" != "" ]; then
-         FILE_PREFIX="${FILE_PREFIX}-"
+      K8SS="$K8S"
+      if [ "$FILE_TRAIL" != "" ]; then
+         FILE_TRAIL="${FILE_TRAIL}-"
       fi
-      FILE_PREFIX="${FILE_PREFIX}k8s"
-      if [ "$FILE_POSTFIX" != "" ]; then
-         FILE_POSTFIX="${FILE_POSTFIX}-"
-      fi
-      FILE_POSTFIX="${FILE_POSTFIX}$K8S"
-     K8S_CLUSTERS=$K8S
+      FILE_TRAIL="${FILE_TRAIL}k8s-${K8SS}"
    fi
    if [ "$POD_SPECIFIED" == "false" ]; then
       POD=""
@@ -255,15 +247,11 @@ else
          echo "----------------------------------------------------------------"
          exit 1
       fi
-      if [ "$FILE_PREFIX" != "" ]; then
-         FILE_PREFIX="${FILE_PREFIX}-"
+      PODS="$POD"
+      if [ "$FILE_TRAIL" != "" ]; then
+         FILE_TRAIL="${FILE_TRAIL}-"
       fi
-      FILE_PREFIX="${FILE_PREFIX}pod"
-      if [ "$FILE_POSTFIX" != "" ]; then
-         FILE_POSTFIX="${FILE_POSTFIX}-"
-      fi
-      FILE_POSTFIX="${FILE_POSTFIX}$POD"
-      PODS=$POD
+      FILE_TRAIL="${FILE_TRAIL}pod-${PODS}"
    fi
    if [ "$PRODUCT" == "hazelcast" ]; then
       if [ "$CLUSTER_TYPE" == "jet" ]; then
@@ -275,7 +263,7 @@ else
        __PRODUCT="$PRODUCT"
    fi
       
-   BUNDLE_TAR_FILE_PATH=$BUNDLE_DIR/bundle-${__PRODUCT}-${PRODUCT_VERSION}-${FILE_PREFIX}-${FILE_POSTFIX}-${TIMESTAMP}.tar.gz
+   BUNDLE_TAR_FILE_PATH=$BUNDLE_DIR/bundle-${__PRODUCT}-${PRODUCT_VERSION}-${FILE_TRAIL}-${TIMESTAMP}.tar.gz
 fi
 
 # clusters
diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/show_bundle b/padogrid-deployment/src/main/resources/common/bin_sh/show_bundle
--- a/padogrid-deployment/src/main/resources/common/bin_sh/show_bundle
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/show_bundle
@@ -7,7 +7,7 @@ EXECUTABLE="`basename $0`"
 
 __options()
 {
-   echo "-user -console -all -list -header -catalog -?"
+   echo "-user -product -console -all -list -header -catalog -?"
 }
 
 if [ "$OPTIONS" == "true" ]; then
@@ -22,33 +22,41 @@ WORKSPACE
    $PADOGRID_WORKSPACE
 
 NAME
-   $EXECUTABLE - Show the specified bundle's READEME.md in the browser 
+   $EXECUTABLE - List online bundles or display bundle descriptions
 
 SYNOPSIS
-   $EXECUTABLE [-console] [-all | [-list|-header|-catalog] ] [bundle_file_name]
+   $EXECUTABLE [-user GitHub_user_name] [-all | [-product bundle_product_name] | [-list|-header|-catalog] ] [-console] [bundle_file_name]
 
 DESCRIPTION
-   Displays the specified bundle's README.md file in the browser by default. If it's
-   unable to launch the browser then it displays the README.md file on the console instead.
+   Lists online bundles or displays the specified bundle's README.md file in the browser. If
+   browser is not supported then it displays the README.md file on the console instead. By
+   default, it searches the repos maintained by the GitHub user, 'padogrid'.
+
+   The user name can be changed by specifying the '-user' option. To include a list of user names,
+   set the 'GITHUB_USERS' environment variable in the '~/.padogrid/seten.sh' file.
 
 OPTIONS
+   -user
+             GitHub user name. If specified, then the specified user's GitHub repos are searched
+             for bundles. 
+            
    -all
-             Includes all product bundles available in the remote padogrid bundle repo.
+             Includes all product bundles available in the remote bundle repo.
+   
+   -product bundle_product_name
+             Search the specified bundle product. Supported bundle product names are: 
+                $BUNDLE_PRODUCT_LIST
 
    -list
-             Lists product bundles available in the remote padogrid bundle repo. If '-all'
+             Lists product bundles available in the remote bundle repo. If '-all'
              is specified then it lists bundles available for all products, other wise, it lists
              bundles for only the the current workspace product.
 
    -header
              Lists product bundles along with header information describing each bundle in the
-             remote padogrid bundle repo. If '-all' is specified then it lists bundles available
+             remote bundle repo. If '-all' is specified then it lists bundles available
              for all products, other wise, it lists bundles for only the the current workspace product.
 
-   -user
-             GitHub user name. If specified, then the specified user's GitHub repos are searched
-             for bundles. 
-            
    -console
              Displays README.md on the console. By default, if this option is not specified,
              then it displays the README.md file in the browser. If the browser cannot be
@@ -60,10 +68,10 @@ OPTIONS
 
 
    bundle_file_name
-             Bundle file name of README.md.
+             Bundle name or bundle file path
 
 DEFAULT
-   $EXECUTABLE bundle_file_name
+   $EXECUTABLE -user padogrid -list
 
 EXAMPLES
    To list remote bundles for the current workspace product:
@@ -79,10 +87,10 @@ EXAMPLES
       $EXECUTABLE -catalog
 
    To view a remote bundle help (READEME.md) in the browser:
-      $EXECUTABLE bundle-jet-3.2-cluster-trade.tar.gz
+      $EXECUTABLE bundle-jet-3-cluster-trade
 
    To view a remote bundle help (READEME.md) on the console:
-      $EXECUTABLE -console bundle-jet-3.2-cluster-trade.tar.gz
+      $EXECUTABLE -console bundle-jet-3-cluster-trade
 EOF
 if [ "$MAN_SPECIFIED" == "false" ]; then
 cat <<EOF
@@ -103,10 +111,34 @@ fi
 if [ "$1" == "" ]; then
    LIST="true"
 fi
+GITHUB_USER="padogrid"
+if [ "$USER" != "" ]; then
+   GITHUB_USER="$USER"
+   GITHUB_USERS="$GITHUB_USER"
+else
+   SETENV_FILE="$HOME/.padogrid/setenv.sh"
+   if [ -f "$SETENV_FILE" ]; then
+      . $SETENV_FILE
+   fi
+   GITHUB_USERS="padogrid $GITHUB_USERS"
+fi
+if [ "$ALL" == "true" ]; then
+   BUNDLE_PRODUCTS="$BUNDLE_PRODUCT_LIST"
+   BUNDLE_PRODUCT="$PRODUCT"
+elif [ "$PRODUCT_ARG" != "" ]; then
+   BUNDLE_PRODUCTS="$PRODUCT_ARG"
+   BUNDLE_PRODUCT="$PRODUCT_ARG"
+else
+   BUNDLE_PRODUCTS="$PRODUCT"
+   BUNDLE_PRODUCT="$PRODUCT"
+fi
 
 if [ "$CATALOG" == "true" ]; then
    LIST="false"
    HEADER="false"
+   GITHUB_USER_HOME="https://github.com/$GITHUB_USER"
+   BUNDLE_REPOS="https://github.com/$GITHUB_USER?tab=repositories"
+   CATALOG_URL="$GITHUB_USER_HOME/catalog-$BUNDLE_PRODUCT/tree/master/Bundle-Catalog.md"
    BROWSER_URL="${CATALOG_URL}"
    if [[ ${OS_NAME} == DARWIN* ]]; then
       open "$BROWSER_URL"
@@ -121,27 +153,19 @@ if [ "$CATALOG" == "true" ]; then
    fi
 fi
 
-SETENV_FILE="$HOME/.padogrid/setenv.sh"
-if [ -f "$SETENV_FILE" ]; then
-   . $SETENV_FILE
-fi
-GITHUB_USERS="padogrid $GITHUB_USERS"
-if [ "$ALL" == "true" ]; then
-   BUNDLE_PRODUCTS="geode gemfire hazelcast jet"
-else
-   BUNDLE_PRODUCTS="$PRODUCT"
-fi
 
 if [ "$ALL" == "true" ]; then
     LIST="true"
 fi
-
 if [ "$USER" != "" ]; then
-   GITHUB_USERS="$USER"
    LIST="true"
 fi
-   
-if [ "$LIST" == "true" ] || [ "$HEADER" == "true" ]; then
+
+BUNDLE_FILE_PATH=${@: -1}
+ARG1=${@: -2}
+
+if [ "$1" == "" ] || [[ "$BUNDLE_FILE_PATH" == "-"* ]] || [[ "$ARG1" == "-product "* ]] || [[ "$ARG1" == "-user "* ]]; then
+   # If bundle file not specified... 
    echo ""
    echo "Remote Bundle List"
    echo "------------------"
@@ -155,7 +179,7 @@ if [ "$LIST" == "true" ] || [ "$HEADER" == "true" ]; then
       echo -e "(Repo: ${CLightGreen}$GITHUB_USER_HOME)${CNone}"
       let BUNDLE_INDEX=0
       for BUNDLE_PRODUCT in $BUNDLE_PRODUCTS; do
-         HREF=$(curl -sS $BUNDLE_REPOS | grep "\/$GITHUB_USER/${BUNDLE_PRODUCT}\-")
+         HREF=$(curl -sS $BUNDLE_REPOS | grep "\/$GITHUB_USER/bundle-${BUNDLE_PRODUCT}\-")
          BUNDLE_LIST=""
          for i in $HREF; do
             if [[ $i == *href=* ]]; then
@@ -191,42 +215,72 @@ if [ "$LIST" == "true" ] || [ "$HEADER" == "true" ]; then
    echo " Preview bundle contents: install_bundle -download -preview bundle_file_name"
    echo "          Install bundle: install_bundle -download bundle_file_name"
    echo ""
-
-   exit
-fi
-
-BUNDLE_FILE_PATH=${@: -1}
-
-for BUNDLE_NAME in $BUNDLE_LIST; do
-   if [ "$BUNDLE_NAME" == "$BUNDLE_FILE_PATH" ]; then
-      BUNDLE_FOUND="true"
-   fi
-done
-if [ "$BUNDLE_FOUND" != "true" ]; then
-   echo >&2 "ERROR: Specified bundle does not exist in the repo. Command aborted."
-   exit 1
-fi
-
-BUNDLE_NAME=$BUNDLE_FILE_PATH
-BROWSER_URL="${GITHUB_USER_HOME}/${BUNDLE_NAME}"
-RAW_FILE_URL="${RAW_BASE_URL}/${BUNDLE_NAME}/master/README.md"
-
-if [ "$CONSOLE" == "true" ]; then
-   curl $RAW_FILE_URL
-   URL=$RAW_FILE_URL
 else
-   if [[ ${OS_NAME} == DARWIN* ]]; then
-      open "$BROWSER_URL"
-      URL=$BROWSER_URL
-   elif [[ ${OS_NAME} == CYGWIN* ]] || [ "$(which cmd.exe)" != "" ]; then
-      cmd.exe /c start "" "$BROWSER_URL" > /dev/null 2>&1
-      URL=$BROWSER_URL
+   # If bundle file specified... 
+
+   # Get bundle type
+   if [[ "$BUNDLE_FILE_PATH" == "bundle-geode-"* ]]; then
+      __PRODUCT="geode"
+      BUNDLE_PRODUCT="geode"
+   elif [[ "$BUNDLE_FILE_PATH" == "bundle-gemfire-"* ]]; then
+      __PRODUCT="geode"
+      BUNDLE_PRODUCT="gemfire"
+   elif [[ "$BUNDLE_FILE_PATH" == "bundle-hazelcast-"* ]]; then
+      __PRODUCT="hazelcast"
+      BUNDLE_PRODUCT="hazelcast"
+   elif [[ "$BUNDLE_FILE_PATH" == "bundle-jet-"* ]]; then
+      __PRODUCT="hazelcast"
+      BUNDLE_PRODUCT="jet"
    else
+      echo >&2 "ERROR: Invalid bundle name. Command aborted."
+      exit 1
+   fi
+   
+   
+   GITHUB_USER_HOME="https://github.com/$GITHUB_USER"
+   BUNDLE_REPOS="https://github.com/$GITHUB_USER?tab=repositories"
+   CATALOG_URL="$GITHUB_USER_HOME/catalog-$__PRODUCT/tree/master/Bundle-Catalog.md"
+   RAW_BASE_URL="https://raw.githubusercontent.com/$GITHUB_USER"
+   HREF=$(curl -sS $BUNDLE_REPOS | grep "\/$GITHUB_USER/bundle-${BUNDLE_PRODUCT}\-")
+   BUNDLE_LIST=""
+   for i in $HREF; do
+      if [[ $i == *href=* ]]; then
+         BUNDLE_NAME=$(echo $i | sed -e "s/.*href=\"//" -e  "s/\"//g" -e "s/\/$GITHUB_USER\///")
+         BUNDLE_LIST="$BUNDLE_LIST $BUNDLE_NAME"
+      fi
+   done
+   
+   for BUNDLE_NAME in $BUNDLE_LIST; do
+      if [ "$BUNDLE_NAME" == "$BUNDLE_FILE_PATH" ]; then
+         BUNDLE_FOUND="true"
+      fi
+   done
+   if [ "$BUNDLE_FOUND" != "true" ]; then
+      echo >&2 "ERROR: Specified bundle does not exist in the repo. Command aborted."
+      exit 1
+   fi
+   
+   BUNDLE_NAME=$BUNDLE_FILE_PATH
+   BROWSER_URL="${GITHUB_USER_HOME}/${BUNDLE_NAME}"
+   RAW_FILE_URL="${RAW_BASE_URL}/${BUNDLE_NAME}/master/README.md"
+   
+   if [ "$CONSOLE" == "true" ]; then
       curl $RAW_FILE_URL
       URL=$RAW_FILE_URL
+   else
+      if [[ ${OS_NAME} == DARWIN* ]]; then
+         open "$BROWSER_URL"
+         URL=$BROWSER_URL
+      elif [[ ${OS_NAME} == CYGWIN* ]] || [ "$(which cmd.exe)" != "" ]; then
+         cmd.exe /c start "" "$BROWSER_URL" > /dev/null 2>&1
+         URL=$BROWSER_URL
+      else
+         curl $RAW_FILE_URL
+         URL=$RAW_FILE_URL
+      fi
    fi
+   
+   echo ""
+   echo $BROWSER_URL
+   echo ""
 fi
-
-echo ""
-echo $BROWSER_URL
-echo ""
