Updated bash completion for create_group

diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/create_group b/padogrid-deployment/src/main/resources/common/bin_sh/create_group
--- a/padogrid-deployment/src/main/resources/common/bin_sh/create_group
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/create_group
@@ -160,9 +160,9 @@ if [ "$TYPE_ARG" == "pado" ]; then
      echo >&2 "WORKSPACE: $PADOGRID_WORKSPACE"
      echo >&2 "----------------------------------------------------------------"
      echo -e >&2 "    ${CLightRed}ERROR:${CNone} Pado is not found. You must set PADO_HOME with the Pado installation path in the following"
-     echo >&2 "       workspace 'setenv.sh' file."
+     echo >&2 "           workspace 'setenv.sh' file."
      echo >&2 -e "       ${CLightRed}$PADOGRID_WORKSPACE/setenv.sh${CNone}"
-     echo >&2 "       Command aborted."
+     echo >&2 "           Command aborted."
      exit 1
   fi
 fi
