Added -workspace compeltion for install_bundle

diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/install_bundle b/padogrid-deployment/src/main/resources/common/bin_sh/install_bundle
--- a/padogrid-deployment/src/main/resources/common/bin_sh/install_bundle
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/install_bundle
@@ -136,6 +136,7 @@ fi
 
 BUNDLE_FILE_PATH=${@: -1}
 
+echo "DOWNLOAD=$DOWNLOAD"
 if [ "$USER" == "" ]; then
    GITHUB_USER="padogrid"
 else
@@ -146,7 +147,7 @@ if [ "$DOWNLOAD" == "true" ]; then
    if [ "$WORKSPACE_SPECIFIED" == "true" ]; then
       GIT_DIR="$PADOGRID_WORKSPACES_HOME/$BUNDLE_FILE_PATH"
       if [ "$QUIET" == "false" ] && [ -d "$GIT_DIR" ]; then
-         echo >&2 "ERROR: Specified bundle workspace already exists. Command aborted."
+         echo >&2 "ERROR: The specified bundle workspace already exists. Command aborted."
          exit 1
       fi
    else
@@ -154,7 +155,7 @@ if [ "$DOWNLOAD" == "true" ]; then
       TARBALL=${BUNDLE_FILE_PATH}.tar.gz
       TARBALL_PATH=$PADOGRID_WORKSPACE/bundles/$TARBALL
       if [ "$QUIET" == "false" ] && [ -f "$TARBALL_PATH" ]; then
-         echo "Specified bundle exists in the bundles directory."
+         echo "The specified bundle exists in the bundles directory."
          echo "   $PADOGRID_WORKSPACE/bundles/$TARBALL"
          REDO=true
          INNER_LOOP=true
