Fixed write permissions logic issue

diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/install_padogrid b/padogrid-deployment/src/main/resources/common/bin_sh/install_padogrid
--- a/padogrid-deployment/src/main/resources/common/bin_sh/install_padogrid
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/install_padogrid
@@ -318,7 +318,11 @@ function containsWord
 }
 
 # Exit if the user lacks download permissions
-if [ ! -w "$PADOGRID_PRODUCTS_PATH" ]; then
+if [ -d "$PADOGRID_ENV_BASE_PATH" ] && [ ! -w "$PADOGRID_ENV_BASE_PATH" ]; then
+   echo -e "${CError}ERROR:${CNone} Product installation denied. You do not have write permissions. Command aborted."
+   exit 1
+fi
+if [ -d "$PADOGRID_PRODUCTS_PATH" ] && [ ! -w "$PADOGRID_PRODUCTS_PATH" ]; then
    echo -e "${CError}ERROR:${CNone} Product installation denied. You do not have write permissions. Command aborted."
    exit 1
 fi
