Added install_padogrid -version and support for headless workspace

diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/install_padogrid b/padogrid-deployment/src/main/resources/common/bin_sh/install_padogrid
--- a/padogrid-deployment/src/main/resources/common/bin_sh/install_padogrid
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/install_padogrid
@@ -40,6 +40,7 @@ else
          -scan ) SCAN_SPECIFIED="true";;
          -save ) SAVE_SPECIFIED="true";;
          -file ) LOAD_SPECIFIED="true";;
+         -version ) VERSION_SPECIFIED="true";;
          -?) HELP="true";;
          * ) 
             if [ "$PREV" == "-product" ]; then
@@ -48,6 +49,8 @@ else
                SAVE_ARG="$i";
             elif [ "$PREV" == "-load" ]; then
                LOAD_ARG="$i";
+            elif [ "$PREV" == "-version" ]; then
+               VERSION_ARG="$i";
             else
                echo "Invalid option: [$i]. Command aborted."
                exit 1
@@ -128,7 +131,7 @@ PADOGRID_WORKSPACES_PATH="$PADOGRID_ENV_BASE_PATH/workspaces"
 
 __options()
 {
-   echo "-product -quiet -simulate -save -load -scan -?"
+   echo "-product -version -quiet -simulate -save -load -scan -?"
 }
 
 if [ "$OPTIONS" == "true" ]; then
@@ -143,7 +146,8 @@ NAME
    $EXECUTABLE - Install Padogrid and downloable products
 
 SYNOPSIS
-   $EXECUTABLE [-product] [-quiet] [-simulate] [-scan] [-save|-load file_path] [-?]
+   $EXECUTABLE [-product product_name] [-version product_version]
+                    [-quiet] [-simulate] [-scan] [-save|-load file_path] [-?]
 
 DESCRIPTION
    Installs PadoGrid and downloadable products. This command downloads one or more selected products
@@ -161,6 +165,10 @@ for i in $DOWNLOADABLE_PRODUCTS; do
    echo "             $i"
 done
 cat <<EOF
+
+   -version product_version
+             Product version to install. The product version number must exactly match the version
+             number conventions used by PadoGrid.
 
    -simulate
              If specified, then it only simulates the download steps by printing the 'curl' commands.
@@ -258,6 +266,11 @@ echo -e "      - Amazon Corretto OpenJDK ${CUrl}https://aws.amazon.com/corretto$
 cat <<EOF
 
 NOTES
+   - Derby distributions have the following Java version dependencies.
+     - Java 17+ - 10.16.x.x
+     - Java 9+ - 10.15.x.x
+     - Java 8+ - 10.14.x.x, 10.13.x.x
+
    - Jet Management Center installation is no longer supported. Install Hazelcast Management Center
      instead. It supports both IMDG and Jet.
 
@@ -557,7 +570,7 @@ function getDownloadablePadowebVersions
       local PAGE_VERSIONS=$(curl -sL $download_url | grep "padoweb_" | grep '\.tar\.gz' | sed -e 's/.*padogrid_//' | grep "\/padoweb_.*" | sed -e 's/\.tar\.gz.*//')
       PAGE_VERSIONS=$(unique_words "$PAGE_VERSIONS")
       if [ "$PAGE_VERSIONS" == "" ]; then
-         local assets_urls=$(curl -sL $download_url | grep "padoweb_" | grep '\.tar\.gz' | sed -e 's/.*padogrid_//' | grep "\/padoweb_.*" | sed -e 's/\.tar\.gz.*//')
+         local assets_urls=$(curl -s $download_url | grep "expanded_assets" | sed -e 's/^.*src="//g' -e 's/".*$//')
          if [ "$assets_urls" == "" ]; then
             is_next_page="false"
          else
@@ -1445,7 +1458,100 @@ GRAFANA_ENTERPRISE_VERSION=""
 GRAFANA_OSS_VERSION=""
 DERBY_VERSION=""
 
-if [ "$QUIET" == "true" ]; then
+if [ "$VERSION_SPECIFIED" == "true" ]; then
+
+   INSTALL_COUNT=1
+   case $PRODUCT_ARG in
+      confluent )
+         DOWNLOAD_VERSIONS=( "${CONFLUENT_DOWNLOAD_VERSIONS[@]}" )
+         CONFLUENT_DIST_VERSION=$VERSION_ARG
+         CONFLUENT_VERSION=$(echo $CONFLUENT_DIST_VERSION | sed 's/.*-//') ;;
+      derby )
+         DOWNLOAD_VERSIONS=( "${DERBY_DOWNLOAD_VERSIONS[@]}" )
+         DERBY_VERSION=$VERSION_ARG ;;
+      hadoop )
+         DOWNLOAD_VERSIONS=( "${HADOOP_DOWNLOAD_VERSIONS[@]}" )
+         HADOOP_VERSION=$VERSION_ARG ;;
+      hazelcast-desktop )
+         DOWNLOAD_VERSIONS=( "${HAZELCAST_DESKTOP_DOWNLOAD_VERSIONS[@]}" )
+         HAZELCAST_DESKTOP_VERSION=$VERSION_ARG ;;
+      hazelcast-enterprise ) 
+         DOWNLOAD_VERSIONS=( "${HAZELCAST_ENTERPRISE_DOWNLOAD_VERSIONS[@]}" )
+         HAZELCAST_ENTERPRISE_VERSION=$VERSION_ARG ;;
+      hazelcast-mc )
+         DOWNLOAD_VERSIONS=( "${HAZELCAST_MANAGEMENT_CENTER_DOWNLOAD_VERSIONS[@]}" )
+         HAZELCAST_MANAGEMENT_CENTER_VERSION=$VERSION_ARG ;;
+      hazelcast-oss )
+         DOWNLOAD_VERSIONS=( "${HAZELCAST_OSS_DOWNLOAD_VERSIONS[@]}" )
+         HAZELCAST_OSS_VERSION=$VERSION_ARG ;;
+      geode )
+         DOWNLOAD_VERSIONS=( "${GEODE_DOWNLOAD_VERSIONS[@]}" )
+         GEODE_VERSION=$VERSION_ARG ;;
+      grafana-enterprise )
+         DOWNLOAD_VERSIONS=( "${GRAFANA_DOWNLOAD_VERSIONS[@]}" )
+         GRAFANA_ENTERPRISE_VERSION=$VERSION_ARG ;;
+      grafana-oss )
+         DOWNLOAD_VERSIONS=( "${GRAFANA_DOWNLOAD_VERSIONS[@]}" )
+         GRAFANA_OSS_VERSION=$VERSION_ARG ;;
+      kafka )
+         DOWNLOAD_VERSIONS=( "${KAFKA_DOWNLOAD_VERSIONS[@]}" )
+         KAFKA_VERSION=$VERSION_ARG
+         KAFKA_SCALA_VERSIONS_ARRAY=($(getScalaKafkaVersions "$KAFKA_VERSION"))
+         # Pick the last one (newer version of scala)
+         KAFKA_DIST_VERSION=${KAFKA_SCALA_VERSIONS_ARRAY[${#KAFKA_SCALA_VERSIONS_ARRAY[@]}-1]}
+         ;;
+      pado )
+         DOWNLOAD_VERSIONS=( "${PADO_DOWNLOAD_VERSIONS[@]}" )
+         PADO_VERSION=$VERSION_ARG ;;
+      padodesktop )
+         DOWNLOAD_VERSIONS=( "${PADODESKTOP_DOWNLOAD_VERSIONS[@]}" )
+         PADODESKTOP_VERSION=$VERSION_ARG ;;
+      padoeclipse )
+         DOWNLOAD_VERSIONS=( "${PADOECLIPSE_DOWNLOAD_VERSIONS[@]}" )
+         PADOECLIPSE_VERSION=$VERSION_ARG ;;
+      padogrid )
+         DOWNLOAD_VERSIONS=( "${PADOGRID_DOWNLOAD_VERSIONS[@]}" )
+         PADOGRID_VERSION=$VERSION_ARG ;;
+      padoweb )
+         DOWNLOAD_VERSIONS=( "${PADOWEB_DOWNLOAD_VERSIONS[@]}" )
+         PADOWEB_VERSION=$VERSION_ARG ;;
+      prometheus )
+         DOWNLOAD_VERSIONS=( "${PROMETHEUS_DOWNLOAD_VERSIONS[@]}" )
+         PROMETHEUS_VERSION=$VERSION_ARG ;;
+      redis-oss )
+         DOWNLOAD_VERSIONS=( "${REDIS_DOWNLOAD_VERSIONS[@]}" )
+         REDIS_VERSION=$VERSION_ARG ;;
+      snappydata )
+         DOWNLOAD_VERSIONS=( "${SNAPPYDATA_DOWNLOAD_VERSIONS[@]}" )
+         SNAPPYDATA_VERSION=$VERSION_ARG ;;
+      spark )
+         DOWNLOAD_VERSIONS=( "${SPARK_DOWNLOAD_VERSIONS[@]}" )
+         SPARK_VERSION=$VERSION_ARG
+         SPARK_DIST_VERSION=${SPARK_VERSION}-bin-without-hadoop ;;
+      *) ;;
+   esac
+
+   found="false"
+   for i in ${DOWNLOAD_VERSIONS[@]}; do
+      if [ "$i" == "$VERSION_ARG" ]; then
+         found="true"
+      fi
+   done
+
+   if [ "$found" == "false" ]; then
+      echo ""
+      echo "Downloadable product versions: [$PRODUCT_ARG]"
+      index=0
+      for i in ${DOWNLOAD_VERSIONS[@]}; do
+         echo "[$index] $i"
+         let index=index+1
+      done
+      echo ""
+      echo -e >&2 "${CLightRed}ERROR:${CNone} Product version not found [$VERSION_ARG]. Command aborted."
+      exit 1
+   fi
+
+elif [ "$QUIET" == "true" ]; then
    # Set to the latest versions
    PADOGRID_VERSION=${PADOGRID_DOWNLOAD_VERSIONS[0]}
    if [[ "$PADOGRID_VERSION" == *"SNAPSHOT" ]]; then
@@ -1842,7 +1948,7 @@ while [ "$REDO" == "true" ]; do
          __INSTALLED="false"
          while [ "$__LOOP" == "true" ]; do
             __INDEX=0
-            echo -e "Kafka distributions ${CUrl}${KAFKA_DOWNLOAD_URL}/$KAFKA_VERSION/${CNone}"
+            echo -e "Kafka distributions ${CUrl}${KAFKA_DOWNLOAD_URL}$KAFKA_VERSION/${CNone}"
             for i in ${KAFKA_SCALA_VERSIONS_ARRAY[@]}; do
                __INSTALLED="false"
                for j in ${INSTALLED_VERSIONS[@]}; do
@@ -2047,7 +2153,7 @@ while [ "$REDO" == "true" ]; do
       case $INPUT in
          [Cc]* ) REDO=false; INNER_LOOP=false;;
          [Rr]* ) REDO=true; INNER_LOOP=false;;
-            [Qq]* ) echo "Command Aborted."; INNER_LOOP=false; exit;;
+         [Qq]* ) echo "Command Aborted."; INNER_LOOP=false; exit;;
       esac
    done
 
@@ -2829,7 +2935,7 @@ if [ "$PROMETHEUS_VERSION" != "" ]; then
       POSTFIX=".$OS_NAME-$HARDWARE_NAME"
    fi
    PROMETHEUS_RELEASE="prometheus-$PROMETHEUS_VERSION${POSTFIX}"
-   PROMETHEUS_TARBALL="prometheus-$PROMETHEUS_RELEASE.tar.gz"
+   PROMETHEUS_TARBALL="$PROMETHEUS_RELEASE.tar.gz"
    installProduct "prometheus" "$SIMULATE"
 fi
 if [ "$GRAFANA_ENTERPRISE_VERSION" != "" ]; then
