Added -tag to install_bundle

diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/install_bundle b/padogrid-deployment/src/main/resources/common/bin_sh/install_bundle
--- a/padogrid-deployment/src/main/resources/common/bin_sh/install_bundle
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/install_bundle
@@ -23,7 +23,7 @@ EXECUTABLE="`basename $0`"
 
 __options()
 {
-   echo "-user -githost -branch -connect -preview -download -checkout -workspace -replace -force -overwrite-workspace -init -quiet -?"
+   echo "-user -githost -branch -tag -connect -preview -download -checkout -workspace -replace -force -overwrite-workspace -init -quiet -?"
 }
 
 if [ "$OPTIONS" == "true" ]; then
@@ -49,7 +49,8 @@ WARNING
 SYNOPSIS
    $EXECUTABLE [-user git_user_name]
                   [-githost github | gitea]
-                  [-branch git_branch] 
+                  [-branch git_branch | -tag git_tag] 
+                  [-tag git_tag] 
                   [-connect https | ssh]
                   [-checkout default | workspace_name]
                   [-workspace default | workspace_name]
@@ -84,6 +85,9 @@ OPTIONS
 
    -branch git_branch
              Git branch to download. If not specified then the default branch is downloaded.
+
+   -tag git_tag
+             Git tag to download. If not specified then the default branch is downloaded.
 
    -connect https | ssh
              Git connection type. For GitHub, the default is 'https'. To connect to private repos,
@@ -288,6 +292,18 @@ if [ "$SED_SUB_EXPRESSION" != "" ]; then
    WORKSPACE_NAME=$(echo $BUNDLE_FILE_PATH | sed "s$SED_SUB_EXPRESSION")
 fi
 
+# Exit if both -branch and -tag are specified
+if [ "$BRANCH" != "" ] && [ "$TAG" != "" ]; then
+   echo -e >&2 "${CError}ERROR:${CNone} '-branch' and '-tag' are not allowed together. Command aborted."
+   exit 1
+fi
+
+BRANCH_TAG=""
+if [ "$BRANCH" != "" ]; then
+   BRANCH_TAG="$BRANCH"
+elif [ "$TAG" != "" ]; then
+   BRANCH_TAG="$TAG"
+fi
 
 #
 # Handle -all:w
@@ -491,7 +507,7 @@ if [ "$DOWNLOAD" == "true" ] || [ "$DOWNLOADED_BUNDLE_FILE_SPECIFIED" == "true" 
       fi
       GIT_DIR="$PADOGRID_WORKSPACES_HOME/$REPO_NAME"
       if [ "$OVERWRITE_WORKSPACE_SPECIFIED" == "false" ] && [ -d "$GIT_DIR" ]; then
-         echo -e >&2 "${CLightRed}ERROR:${CNone} The specified bundle workspace already exists: [$REPO_NAME]. Command aborted."
+         echo -e >&2 "${CLightRed}ERROR:${CNone} The specified bundle workspace already exists: [$REPO_NAME]. Specify '-overwrite-workspace' to overwrite. Command aborted."
          exit 1
       elif [ "$OVERWRITE_WORKSPACE_SPECIFIED" == "true" ]; then
          if [ -d "$GIT_DIR/.git" ] ; then
@@ -772,6 +788,13 @@ if [ "$DOWNLOAD" == "true" ] || [ "$DOWNLOADED_BUNDLE_FILE_SPECIFIED" == "true" 
                exit 1
             fi
             git checkout $BRANCH
+         elif [ "$TAG" != "" ]; then
+            TAG_IN_REMOTE=$(git ls-remote --tags origin ${BRANCH})
+            if [[ -z ${TAG_IN_REMOTE} ]]; then
+               echo -e >&2 "${CLightRed}ERROR:${CNone} The specified tag does not exist: [$BRANCH]. Command aborted."
+               exit 1
+            fi
+            git checkout $TAG
          fi
          git pull
          if [ "$IS_BUNDLE_WORKSPACE" == "false" ]; then
@@ -801,6 +824,10 @@ if [ "$DOWNLOAD" == "true" ] || [ "$DOWNLOADED_BUNDLE_FILE_SPECIFIED" == "true" 
                popd > /dev/null 2>&1 
             fi
             echo ""
+            if [ "$BRANCH_TAG" != "" ]; then
+               echo "Branch/Tag: $BRANCH_TAG"
+               echo ""
+            fi
             echo "Bundle workspace updated. Switch workspace by executing the following command:"
          else
             TEMP_WORKSPACE_DIR=$PADOGRID_WORKSPACES_HOME/__ws-${WORKSPACE_NAME}
@@ -838,6 +865,10 @@ if [ "$DOWNLOAD" == "true" ] || [ "$DOWNLOADED_BUNDLE_FILE_SPECIFIED" == "true" 
             fi
 
             echo ""
+            if [ "$BRANCH_TAG" != "" ]; then
+               echo "Branch/Tag: $BRANCH_TAG"
+               echo ""
+            fi
             echo "Bundle workspace created. Switch workspace by executing the following command:"
          fi
 
@@ -995,6 +1026,7 @@ else
    echo "INSTALLED"
    echo "---------"
 fi
+
 if [ "$PREVIEW" == "true" ]; then
    echo "      Cluster Type: $CLUSTER_TYPE"
    if [ "$DOWNLOAD" == "true" ]; then
@@ -1002,6 +1034,7 @@ if [ "$PREVIEW" == "true" ]; then
    else
    echo "            Bundle: $BUNDLE_FILE_PATH"
    fi
+   echo "        Branch/Tag: $BRANCH_TAG"
    echo "   Preiview Pod(s):$PODS"
    echo "Preview Cluster(s):$CLUSTERS"
    echo "   Preview Apps(s):$APPS"
@@ -1011,6 +1044,7 @@ else
    echo "           WORKSPACE: $WORKSPACE_PATH"
    echo "        Cluster Type: $CLUSTER_TYPE"
    echo "              Bundle: $BUNDLE_FILE_PATH"
+   echo "          Branch/Tag: $BRANCH_TAG"
    echo "    Installed Pod(s):$PODS"
    echo "Installed Cluster(s):$CLUSTERS"
    echo "    Installed App(s):$APPS"
