Added support for installing zip bundles

diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/install_bundle b/padogrid-deployment/src/main/resources/common/bin_sh/install_bundle
--- a/padogrid-deployment/src/main/resources/common/bin_sh/install_bundle
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/install_bundle
@@ -70,6 +70,10 @@ DESCRIPTION
       install_bundle -checkout
       install_bundle -workspace -download
 
+   If your local environment does not have access to the Internet, then you can install
+   the online bundles by manually downloading them. Download the zip files from the
+   repos and execute this command. See examples below.
+
 OPTIONS
    -user git_user_name
              Git user name. If specified, then it downloads the specified bundle from user's
@@ -119,8 +123,8 @@ OPTIONS
              Quiet mode. Supresses the interactive prompt.
 
    bundle_file_path
-              Bundle file path if local or bundle name if download.
-
+              Bundle file path if local or bundle name if download. If the bundle file name ends with the .zip extension,
+              then it assumes the bundle file was downloaded from the repo and installs the bundle accordingly.
 
 DEFAULT
    $EXECUTABLE -user padogrid -githost github
@@ -141,6 +145,11 @@ EXAMPLES
    To check out a remote bundle as a workspace:
       $EXECUTABLE -checkout bundle-coherence-14-app-perf_test_wan-cluster-ln-ny
 
+   To install a downloaded zip file.
+      $EXECUTABLE bundle-hazelcast-4n5-cluster-session-master.zip
+      $EXECUTABLE -workspace bundle-hazelcast-4n5-cluster-session-master.zip
+      $EXECUTABLE -workspace mysession bundle-hazelcast-4n5-cluster-session-master.zip
+      
 EOF
 if [ "$MAN_SPECIFIED" == "false" ]; then
 cat <<EOF
@@ -166,6 +175,15 @@ if [ "$LIST" == "true" ]; then
 fi
 
 BUNDLE_FILE_PATH=${@: -1}
+DOWNLOADED_BUNDLE_FILE_SPECIFIED=false
+if [[ $BUNDLE_FILE_PATH == *.zip ]]; then
+   DOWNLOADED_BUNDLE_FILE_SPECIFIED=true
+   DOWNLOADED_BUNDLE_FILE_NAME=$(basename $BUNDLE_FILE_PATH)
+   DOWNLOADED_BUNDLE_NAME=${DOWNLOADED_BUNDLE_FILE_NAME%.zip}
+   BUNDLE_NAME=${DOWNLOADED_BUNDLE_NAME%-master}
+else
+   BUNDLE_NAME=$BUNDLE_FILE_PATH
+fi
 
 #
 # Returns "true" if one of the specfied product versions match the configured product version.
@@ -242,13 +260,24 @@ function createClusterEnv
     done
 }
 
+if [ "$DOWNLOADED_BUNDLE_FILE_SPECIFIED" == "true" ]; then
+   if [ "$CHECKOUT_SPECIFIED" == "true" ]; then
+      echo -e >&2 "${CLightRed}ERROR:${CNone} Invalid options. '-checkout' not allowed with a zip file. Command aborted."
+      exit 1
+   fi
+   if [ "$DOWNLOAD" == "true" ]; then
+      echo -e >&2 "${CLightRed}ERROR:${CNone} Invalid options. '-download' not allowed with a zip file. Command aborted."
+      exit 1
+   fi
+fi
+
 if [ "$CHECKOUT_SPECIFIED" == "true" ] && [ "$WORKSPACE_SPECIFIED" == "true" ]; then
    echo -e >&2 "${CLightRed}ERROR:${CNone} Invalid options. Specify either '-checkout' or '-workspace'. Command aborted."
    exit 1
 fi
 
 # Set arguments. (due to the arg parser limitations, we need to do this here)
-if [ "$CHECKOUT_ARG" == "" ] || [[ "$CHECKOUT_ARG" == "-"* ]]; then
+if [ "$CHECKOUT_ARG" == "" ] || [[ "$CHECKOUT_ARG" == "-"* ]] || [ "$WORKSPACE_ARG" == "$BUNDLE_FILE_PATH" ]; then
    if [ "$CHECKOUT_ARG" == "-download" ]; then
       DOWNLOAD="true"
    elif [ "$CHECKOUT_ARG" == "-preview" ]; then
@@ -262,7 +291,7 @@ if [ "$CHECKOUT_SPECIFIED" == "true" ]; then
    DOWNLOAD="true"
 fi
 if [ "$WORKSPACE_NAME" == "" ] || [ "$WORKSPACE_NAME" == "default" ]; then
-   if [ "$WORKSPACE_ARG" == "" ] || [[ "$WORKSPACE_ARG" == "-"* ]]; then
+   if [ "$WORKSPACE_ARG" == "" ] || [[ "$WORKSPACE_ARG" == "-"* ]] || [ "$WORKSPACE_ARG" == "$BUNDLE_FILE_PATH" ]; then
       if [ "$WORKSPACE_ARG" == "-download" ]; then
          DOWNLOAD="true"
       elif [ "$WORKSPACE_ARG" == "-preview" ]; then
@@ -279,13 +308,14 @@ if [ "$USER" == "" ]; then
 else
    GITHUB_USER="$USER"
 fi
-if [ "$DOWNLOAD" == "true" ]; then
+if [ "$DOWNLOAD" == "true" ] || [ "$DOWNLOADED_BUNDLE_FILE_SPECIFIED" == "true" ]; then
    IS_DOWNLOAD="true"
+   REPO_NAME=""
    if [ "$CHECKOUT_SPECIFIED" == "true" ] || [ "$WORKSPACE_SPECIFIED" == "true" ]; then
       if [ "$WORKSPACE_NAME" != "default" ]; then
          REPO_NAME="$WORKSPACE_NAME"
       else
-         REPO_NAME="$BUNDLE_FILE_PATH"
+         REPO_NAME="$BUNDLE_NAME"
       fi
       GIT_DIR="$PADOGRID_WORKSPACES_HOME/$REPO_NAME"
       if [ "$QUIET" == "false" ] && [ -d "$GIT_DIR" ]; then
@@ -293,24 +323,23 @@ if [ "$DOWNLOAD" == "true" ]; then
          exit 1
       fi
    else
-      GIT_DIR=$PADOGRID_WORKSPACE/bundles/$BUNDLE_FILE_PATH
-      TARBALL=${BUNDLE_FILE_PATH}.tar.gz
-      TARBALL_PATH=$PADOGRID_WORKSPACE/bundles/$TARBALL
-      if [ "$QUIET" == "false" ] && [ -f "$TARBALL_PATH" ]; then
-         echo "The specified bundle exists in the bundles directory."
-         echo "   $PADOGRID_WORKSPACE/bundles/$TARBALL"
-         REDO=true
-         INNER_LOOP=true
-         while [ "$INNER_LOOP" == "true" ]; do
-            read -p "Enter 'e' to install the existing bundle, 'd' to download, 'q' to quit: " INPUT
-            case $INPUT in
-               [Ee]* ) IS_DOWNLOAD="false"; INNER_LOOP=false;;
-               [Dd]* ) IS_DOWNLOAD="true"; INNER_LOOP=false;;
-               [Qq]* ) echo "Command Aborted."; INNER_LOOP=false; exit;;
-               * ) INNER_LOOP=true;;
-            esac
-         done
-      fi
+      GIT_DIR=$PADOGRID_WORKSPACE/bundles/$BUNDLE_NAME
+      TARBALL=${BUNDLE_NAME}.tar.gz
+   fi
+   TARBALL_PATH=$PADOGRID_WORKSPACE/bundles/$TARBALL
+   if [ "$QUIET" == "false" ] && [ -f "$TARBALL_PATH" ] && [ "$DOWNLOADED_BUNDLE_FILE_SPECIFIED" == "false" ]; then
+      echo "The specified bundle exists in the bundles directory."
+      echo "   $PADOGRID_WORKSPACE/bundles/$TARBALL"
+      REDO=true
+      INNER_LOOP=true
+      while [ "$INNER_LOOP" == "true" ]; do
+         read -p "Enter 'e' to install the existing bundle, 'd' to download, 'q' to quit: " INPUT
+         case $INPUT in
+            [Ee]* ) IS_DOWNLOAD="false"; INNER_LOOP=false;;
+            [Dd]* ) IS_DOWNLOAD="true"; INNER_LOOP=false;;
+            [Qq]* ) echo "Command Aborted."; INNER_LOOP=false; exit;; * ) INNER_LOOP=true;;
+         esac
+      done
    fi
    if [ "$IS_DOWNLOAD" == "true" ]; then
       if [ "$CHECKOUT_SPECIFIED" == "false" ] && [ "$WORKSPACE_SPECIFIED" == "false" ]; then
@@ -325,28 +354,58 @@ if [ "$DOWNLOAD" == "true" ]; then
          . $SETENV_FILE
       fi
 
-      GIT_PATH=$PADOGRID_WORKSPACE/bundles/required_products.txt
-      if [ "$GITHOST" == "gitea" ]; then
-         GITHUB_USER_HOME="$GITEA_SSH_URL:$GITHUB_USER"
-         USER_REPOS_URL="$GITEA_HTTPS_URL/api/v1/user/repos"
-         REPOS_URL="$GITEA_HTTPS_URL/api/v1/repos"
-         AUTH_HEADER="Authorization: token $GITEA_ACCESS_TOKEN"
-         REQUIRED_PRODUCTS_CONTENT_URL="$REPOS_URL/$GITHUB_USER/${BUNDLE_FILE_PATH}/contents/required_products.txt"
-         curl -sS -X GET "$REQUIRED_PRODUCTS_CONTENT_URL" -H "$AUTH_HEADER" | grep -o "\"content\":\"[^\"]*" | sed 's/"content":"//' | base64 -d > $GIT_PATH 2>/dev/null
-      else
-         if [ "$CONNECT" == "ssh" ] || [ "$GITHUB_PRIVATE_REPO_ENABLED" == "true" ]; then
-             GITHUB_USER_HOME="git@github.com:$GITHUB_USER"
+      REQUIRED_PRODUCTS_FILE_PATH=$PADOGRID_WORKSPACE/bundles/required_products.txt
+      if [ "$DOWNLOADED_BUNDLE_FILE_SPECIFIED" == "true" ]; then
+         pushd $PADOGRID_WORKSPACE/bundles > /dev/null 2>&1 
+         jar xf $BUNDLE_FILE_PATH $DOWNLOADED_BUNDLE_NAME
+
+         if [ ! -d "$DOWNLOADED_BUNDLE_NAME" ]; then
+            echo -e >&2 "${CLightRed}ERROR:${CNone} Invalid bundle zip file. Command aborted."
+            exit 1
          else
-             GITHUB_USER_HOME="https://github.com/$GITHUB_USER"
+            if [ "$DOWNLOADED_BUNDLE_NAME" != "$BUNDLE_NAME" ]; then
+               mv $DOWNLOADED_BUNDLE_NAME $BUNDLE_NAME
+            fi
+            if [ -f $BUNDLE_NAME/required_products.txt ]; then
+               cp $BUNDLE_NAME/required_products.txt .
+            fi
+            # Make all scripts in bin_sh executable
+            for i in $(find $BUNDLE_NAME -name bin_sh); do
+               if [ -d $i ]; then
+                  chmod 755 $i/*
+               fi
+            done
+            if [ "$CHECKOUT_SPECIFIED" == "true" ] || [ "$WORKSPACE_SPECIFIED" == "true" ]; then
+               mv $BUNDLE_NAME $PADOGRID_WORKSPACES_HOME/$WORKSPACE_NAME
+               if [ "$WORKSPACE_NAME" == "default" ]; then
+                  WORKSPACE_NAME=$BUNDLE_NAME
+               fi
+            fi
          fi
-         RAW_REQUIRED_PRODUCTS_URL=https://raw.githubusercontent.com/$GITHUB_USER/$BUNDLE_FILE_PATH/master/required_products.txt
-         curl -sS $RAW_REQUIRED_PRODUCTS_URL > $GIT_PATH 2>/dev/null
+         popd > /dev/null 2>&1 
+      else
+         if [ "$GITHOST" == "gitea" ]; then
+            GITHUB_USER_HOME="$GITEA_SSH_URL:$GITHUB_USER"
+            USER_REPOS_URL="$GITEA_HTTPS_URL/api/v1/user/repos"
+            REPOS_URL="$GITEA_HTTPS_URL/api/v1/repos"
+            AUTH_HEADER="Authorization: token $GITEA_ACCESS_TOKEN"
+            REQUIRED_PRODUCTS_CONTENT_URL="$REPOS_URL/$GITHUB_USER/${BUNDLE_FILE_PATH}/contents/required_products.txt"
+            curl -sS -X GET "$REQUIRED_PRODUCTS_CONTENT_URL" -H "$AUTH_HEADER" | grep -o "\"content\":\"[^\"]*" | sed 's/"content":"//' | base64 -d > $REQUIRED_PRODUCTS_FILE_PATH 2>/dev/null
+         else
+            if [ "$CONNECT" == "ssh" ] || [ "$GITHUB_PRIVATE_REPO_ENABLED" == "true" ]; then
+                GITHUB_USER_HOME="git@github.com:$GITHUB_USER"
+            else
+                GITHUB_USER_HOME="https://github.com/$GITHUB_USER"
+            fi
+            RAW_REQUIRED_PRODUCTS_URL=https://raw.githubusercontent.com/$GITHUB_USER/$BUNDLE_FILE_PATH/master/required_products.txt
+            curl -sS $RAW_REQUIRED_PRODUCTS_URL > $REQUIRED_PRODUCTS_FILE_PATH 2>/dev/null
+         fi
       fi
       
       declare -a requiredProducts
       declare -a clusterTypes
       declare -a propArray
-      getPropertiesArray "$GIT_PATH" propArray
+      getPropertiesArray "$REQUIRED_PRODUCTS_FILE_PATH" propArray
       let len=${#propArray[@]}
       if [ $len -eq 0 ]; then
          echo "Using bundle name to determine installed products..."
@@ -438,43 +497,55 @@ if [ "$DOWNLOAD" == "true" ]; then
          exit 1
       fi
       
-      if [ "$CHECKOUT_SPECIFIED" == "true" ] || [ "$WORKSPACE_SPECIFIED" == "true" ]; then
-         pushd $PADOGRID_WORKSPACES_HOME > /dev/null 2>&1 
-         echo git clone $GITHUB_USER_HOME/${BUNDLE_FILE_PATH}.git $REPO_NAME
-         git clone $GITHUB_USER_HOME/${BUNDLE_FILE_PATH}.git $REPO_NAME> /dev/null 2>&1
+      if [ "$DOWNLOADED_BUNDLE_FILE_SPECIFIED" == "true" ]; then
+         pushd $GIT_DIR > /dev/null 2>&1 
+         mvn package
+         # Make all scripts in bin_sh executable
+         for i in $(find . -name bin_sh); do
+            if [ -d $i ]; then
+               chmod 755 $i/*
+            fi
+         done
          popd > /dev/null 2>&1 
       else
-         pushd $PADOGRID_WORKSPACE/bundles > /dev/null 2>&1 
-         echo git clone $GITHUB_USER_HOME/${BUNDLE_FILE_PATH}.git 
-         git clone $GITHUB_USER_HOME/${BUNDLE_FILE_PATH}.git > /dev/null 2>&1
-         popd > /dev/null 2>&1 
-      fi
-
-      if [ ! -d "$GIT_DIR" ]; then
-         echo -e >&2 "${CLightRed}ERROR:${CNone} The specified bundle does not exist for the user [$GITHUB_USER]."
-         exit 1
-      fi
-      pushd $GIT_DIR > /dev/null 2>&1 
-      if [ "$BRANCH" != "" ]; then
-         BRANCH_IN_REMOTE=$(git ls-remote --heads origin ${BRANCH})
-         if [[ -z ${BRANCH_IN_REMOTE} ]]; then
-            echo -e >&2 "${CLightRed}ERROR:${CNone} The specified branch does not exist: [$BRANCH]. Command aborted."
+         if [ "$CHECKOUT_SPECIFIED" == "true" ] || [ "$WORKSPACE_SPECIFIED" == "true" ]; then
+            pushd $PADOGRID_WORKSPACES_HOME > /dev/null 2>&1 
+            echo git clone $GITHUB_USER_HOME/${BUNDLE_FILE_PATH}.git $REPO_NAME
+            git clone $GITHUB_USER_HOME/${BUNDLE_FILE_PATH}.git $REPO_NAME> /dev/null 2>&1
+            popd > /dev/null 2>&1 
+         else
+            pushd $PADOGRID_WORKSPACE/bundles > /dev/null 2>&1 
+            echo git clone $GITHUB_USER_HOME/${BUNDLE_FILE_PATH}.git 
+            git clone $GITHUB_USER_HOME/${BUNDLE_FILE_PATH}.git > /dev/null 2>&1
+            popd > /dev/null 2>&1
+         fi
+         if [ ! -d "$GIT_DIR" ]; then
+            echo -e >&2 "${CLightRed}ERROR:${CNone} The specified bundle does not exist for the user [$GITHUB_USER]."
             exit 1
          fi
-         git checkout $BRANCH
+         pushd $GIT_DIR > /dev/null 2>&1 
+         if [ "$BRANCH" != "" ]; then
+            BRANCH_IN_REMOTE=$(git ls-remote --heads origin ${BRANCH})
+            if [[ -z ${BRANCH_IN_REMOTE} ]]; then
+               echo -e >&2 "${CLightRed}ERROR:${CNone} The specified branch does not exist: [$BRANCH]. Command aborted."
+               exit 1
+            fi
+            git checkout $BRANCH
+         fi
+         git pull
+         if [ "$CHECKOUT_SPECIFIED" == "false" ] && [ "$WORKSPACE_SPECIFIED" == "false" ]; then
+            mvn package
+         fi
+         popd > /dev/null 2>&1 
       fi
-      git pull
-      if [ "$CHECKOUT_SPECIFIED" == "false" ] && [ "$WORKSPACE_SPECIFIED" == "false" ]; then
-         mvn package
-      fi
-      popd > /dev/null 2>&1 
       if [ "$CHECKOUT_SPECIFIED" == "true" ] || [ "$WORKSPACE_SPECIFIED" == "true" ]; then
+         TEMP_WORKSPACE_DIR=$PADOGRID_WORKSPACES_HOME/__ws-${BUNDLE_NAME}
          # Copy the workspace files
-         create_workspace -name __ws-${BUNDLE_FILE_PATH} -product $PRODUCT_HOME -quiet > /dev/null
-         rm -rf $PADOGRID_WORKSPACES_HOME/__ws-${BUNDLE_FILE_PATH}/clusters/*
-         cp -r $PADOGRID_WORKSPACES_HOME/__ws-${BUNDLE_FILE_PATH}/* $GIT_DIR/
-         cp $PADOGRID_WORKSPACES_HOME/__ws-${BUNDLE_FILE_PATH}/.addonenv.sh $GIT_DIR/
-         rm -rf $PADOGRID_WORKSPACES_HOME/__ws-${BUNDLE_FILE_PATH}
+         create_workspace -name __ws-${BUNDLE_NAME} -product $PRODUCT_HOME -quiet > /dev/null
+         rm -rf "$TEMP_WORKSPACE_DIR"/clusters/*
+         cp -r "$TEMP_WORKSPACE_DIR"/* "$GIT_DIR"/
+         cp "$TEMP_WORKSPACE_DIR"/.addonenv.sh "$GIT_DIR"/
+         rm -rf "$TEMP_WORKSPACE_DIR"
 
          if [ "$WORKSPACE_SPECIFIED" == "true" ]; then
             # Remove build files including git
@@ -484,7 +555,7 @@ if [ "$DOWNLOAD" == "true" ]; then
                rm -f pom.xml
                rm -f assembly-descriptor.xml
                rm -f README_HEADER.md
-            popd > /dev/null 2>&1 
+               popd > /dev/null 2>&1 
             fi
          fi
 
@@ -504,7 +575,7 @@ if [ "$DOWNLOAD" == "true" ]; then
          echo ""
          exit
       else
-        mv $GIT_DIR/target/assembly/$TARBALL $PADOGRID_WORKSPACE/bundles
+         mv $GIT_DIR/target/assembly/$TARBALL $PADOGRID_WORKSPACE/bundles
          rm -rf $GIT_DIR
          if [ -f $TARBALL_PATH ]; then
             BUNDLE_FILE_PATH=$TARBALL_PATH
@@ -525,7 +596,6 @@ if [ ! -f $BUNDLE_FILE_PATH ]; then
    echo >&2 "----------------------------------------------------------------"
    exit 1 
 fi
-
 
 # Set workspace and its path
 if [ "$WORKSPACE_NAME" != "default" ]; then
@@ -641,6 +711,7 @@ fi
 # 
 if [ "$PREVIEW" == "true" ]; then
    tar -tzvf $BUNDLE_FILE_PATH
+   echo -e "${CBrownOrange}Bundle Preview Only (Not Installed)${CNone}"
 else
    tar -C $WORKSPACE_PATH -xzvf $BUNDLE_FILE_PATH
    createClusterEnv
