Updated RWE and workspace commands to properly handle file permissions enforced when multitenancy is enabled

diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/kill_workspace b/padogrid-deployment/src/main/resources/common/bin_sh/kill_workspace
--- a/padogrid-deployment/src/main/resources/common/bin_sh/kill_workspace
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/kill_workspace
@@ -33,8 +33,10 @@ fi
 
 if [ "$WORKSPACE_ARG" != "" ]; then
    WORKSPACE=$WORKSPACE_ARG
-else
+elif [ "$PADOGRID_WORKSPACE" != "" ]; then
    WORKSPACE="`basename $PADOGRID_WORKSPACE`"
+else
+   WORKSPACE=""
 fi
 
 if [ "$HELP" == "true" ]; then
@@ -82,9 +84,19 @@ EOF
    exit
 fi
 
+
 CURRENT_DIR="`pwd`"
-CURRENT_WORKSPACE="`basename $PADOGRID_WORKSPACE`"
+if [ "$PADOGRID_WORKSPACE" == "" ]; then
+   CURRENT_WORKSPACE=""
+else
+   CURRENT_WORKSPACE="`basename $PADOGRID_WORKSPACE`"
+fi
 CURRENT_CLUSTER=$CLUSTER
+
+if [ "$WORKSPACE" == "" ] && [ "$CURRENT_WORKSPACE" == "" ]; then
+   echo -e >&2 "${CError}ERROR:${CNone} Workspace undefined. The current workspace is undefined. Command aborted."
+   exit 1
+fi
 
 if [ "$WORKSPACE" != "$CURRENT_WORKSPACE" ]; then
    switch_workspace $WORKSPACE
diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/pwd_workspace b/padogrid-deployment/src/main/resources/common/bin_sh/pwd_workspace
--- a/padogrid-deployment/src/main/resources/common/bin_sh/pwd_workspace
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/pwd_workspace
@@ -66,7 +66,16 @@ EOF
    exit
 fi
 
-WORKSPACE="`basename $PADOGRID_WORKSPACE`"
+if [ "$PADOGRID_WORKSPACE" != "" ]; then
+   WORKSPACE="`basename $PADOGRID_WORKSPACE`"
+else
+   WORKSPACE=""
+fi
+
+if [ "$WORKSPACE" == "" ]; then
+   echo -e >&2 "${CError}ERROR:${CNone} Workspace undefined. The current workspace is undefined. Command aborted."
+   exit 1
+fi
 
 if [ "$ALL" = "true" ]; then
    echo "       Current Workspace: $WORKSPACE"
diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/show_workspace b/padogrid-deployment/src/main/resources/common/bin_sh/show_workspace
--- a/padogrid-deployment/src/main/resources/common/bin_sh/show_workspace
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/show_workspace
@@ -67,6 +67,11 @@ if [ "$WORKSPACE_ARG" == "" ]; then
 else
    WORKSPACE_DIR=$PADOGRID_WORKSPACES_HOME/$WORKSPACE_ARG
 fi
+if [ "$WORKSPACE_DIR" == "" ]; then
+   echo -e >&2 "${CError}ERROR:${CNone} Workspace undefined. The current workspace is undefined. Command aborted."
+   exit 1
+fi
+
 WORKSPACE=$(basename  "$WORKSPACE_DIR")
 WORKSPACE_INFO=$(getWorkspaceInfoList $WORKSPACE)
 RWE_NAME=$(basename "$PADOGRID_WORKSPACES_HOME")
diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/start_workspace b/padogrid-deployment/src/main/resources/common/bin_sh/start_workspace
--- a/padogrid-deployment/src/main/resources/common/bin_sh/start_workspace
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/start_workspace
@@ -33,8 +33,10 @@ fi
 
 if [ "$WORKSPACE_ARG" != "" ]; then
    WORKSPACE=$WORKSPACE_ARG
-else
+elif [ "$PADOGRID_WORKSPACE" != "" ]; then
    WORKSPACE="`basename $PADOGRID_WORKSPACE`"
+else
+   WORKSPACE=""
 fi
 
 if [ "$HELP" == "true" ]; then
@@ -77,6 +79,17 @@ EOF
    exit
 fi
 
+if [ "$PADOGRID_WORKSPACE" == "" ]; then
+   CURRENT_WORKSPACE=""
+else
+   CURRENT_WORKSPACE="`basename $PADOGRID_WORKSPACE`"
+fi
+
+if [ "$WORKSPACE" == "" ] && [ "$CURRENT_WORKSPACE" == "" ]; then
+   echo -e >&2 "${CError}ERROR:${CNone} Workspace undefined. The current workspace is undefined. Command aborted."
+   exit 1
+fi
+
 if [ "$QUIET" == "false" ]; then
    echo "Workspace: $WORKSPACE"
    echo "   This command starts all clusters in the workspace. Local clusters configured with the same"
@@ -92,7 +105,6 @@ if [ "$QUIET" == "false" ]; then
 fi
 
 CURRENT_DIR="`pwd`"
-CURRENT_WORKSPACE="`basename $PADOGRID_WORKSPACE`"
 CURRENT_CLUSTER=$CLUSTER
 
 __WORKSPACES=( $WORKSPACE )
