Added padogrid.rwe pod support

diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/list_workspaces b/padogrid-deployment/src/main/resources/common/bin_sh/list_workspaces
--- a/padogrid-deployment/src/main/resources/common/bin_sh/list_workspaces
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/list_workspaces
@@ -64,12 +64,12 @@ EOF
 fi
 
 if [ "$PADOGRID_WORKSPACES_HOME" == "" ]; then
-   echo >&2 "ERROR: Workspaces not initialized. Please first run 'create_rwe' to initialize workspaces."
+   echo -e >&2 "${CError}ERROR:${CNone} Workspaces not initialized. Please first run 'create_rwe' to initialize workspaces."
    echo >&2 "       Command aborted."
    exit 1
 fi
 if [ ! -d "$PADOGRID_WORKSPACES_HOME" ]; then
-   echo >&2 "ERROR: Invalid workspaces. Please run 'create_rwe' to initialize workspaces."
+   echo -e >&2 "${CError}ERROR:${CNone} Invalid workspaces. Please run 'create_rwe' to initialize workspaces."
    echo >&2 "       Command aborted."
    exit 1
 fi
@@ -79,13 +79,13 @@ if [ "$RWE_ARG" == "" ]; then
 else
    RWE_PATH="$PADOGRID_ENV_BASE_PATH/workspaces/$RWE_ARG"
    if [ ! -d "$RWE_PATH" ]; then
-      echo >&2 "ERROR: Specifed RWE does not exist. Command aborted." 
+      echo -e >&2 "${CError}ERROR:${CNone} Specified RWE does not exist. Command aborted." 
       exit 1
    fi
    if [ ! -f "$RWE_PATH/initenv.sh" ] \
       || [ ! -f "$RWE_PATH/.addonenv.sh" ] \
       || [ ! -f "$RWE_PATH/setenv.sh" ]; then
-      echo >&2 "ERROR: Specified RWE is not a invalid RWE. Command aborted." 
+      echo >&2 "${CError}ERROR:${CNone} Specified RWE is not a invalid RWE. Command aborted." 
       exit 1
    fi
 fi
diff --git a/padogrid-deployment/src/main/resources/geode/bin_sh/create_app b/padogrid-deployment/src/main/resources/geode/bin_sh/create_app
--- a/padogrid-deployment/src/main/resources/geode/bin_sh/create_app
+++ b/padogrid-deployment/src/main/resources/geode/bin_sh/create_app
@@ -73,17 +73,7 @@ OPTIONS
              the specified app_name.
 
 DEFAULT
-EOF
-if [ "$PRODUCT_ARG" == "jet" ]; then
-cat <<EOF
-   $EXECUTABLE -app jet_demo -name jet_demo
-EOF
-else
-cat <<EOF
    $EXECUTABLE -app perf_test -name perf_test
-EOF
-fi
-cat <<EOF
 
 FILES
    $PADOGRID_WORKSPACE/apps
@@ -105,10 +95,17 @@ if [ "$PRODUCT_ARG" != "" ]; then
       exit 1
    fi
    if [ "$THIS_PRODUCT" != "$PRODUCT_ARG" ]; then
+      __PRODUCT=$PRODUCT_ARG
       if [ "$PRODUCT_ARG" == "jet" ]; then
-         PRODUCT_ARG="hazelcast"
+         __PRODUCT="hazelcast"
+      elif [ "$PRODUCT_ARG" == "gemfire" ]; then
+         __PRODUCT="geode"
       fi
-      $PADOGRID_HOME/$PRODUCT_ARG/bin_sh/$EXECUTABLE "$@"
+      args="$@"
+      if [ "$__PRODUCT" != "" ]; then
+         args=$(echo "$args" | sed "s/$PRODUCT_ARG/$__PRODUCT/")
+      fi
+      $PADOGRID_HOME/$__PRODUCT/bin_sh/$EXECUTABLE $args
       exit
    fi
 fi
@@ -120,9 +117,8 @@ if [ "$NAME_ARG" == "" ]; then
    NAME_ARG=$APP
 fi
 
-echo "debug: $PADOGRID_HOME/$PRODUCT/apps/$APP"
 if [ ! -d "$PADOGRID_HOME/$PRODUCT/apps/$APP" ]; then
-   >&2 echo "ERROR: The specified app name does not exist. Command aborted."
+   >&2 echo "ERROR: The specified app does not exist. Command aborted."
    exit 1
 fi
 if [ "$APP" == "padodesktop" ] && [ ! -d "$PADODESKTOP_HOME" ]; then
