Updated RWE and workspace commands to properly handle file permissions enforced when multitenancy is enabled

diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/list_workspaces b/padogrid-deployment/src/main/resources/common/bin_sh/list_workspaces
--- a/padogrid-deployment/src/main/resources/common/bin_sh/list_workspaces
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/list_workspaces
@@ -85,7 +85,7 @@ else
    if [ ! -f "$RWE_PATH/initenv.sh" ] \
       || [ ! -f "$RWE_PATH/.addonenv.sh" ] \
       || [ ! -f "$RWE_PATH/setenv.sh" ]; then
-      echo >&2 "${CError}ERROR:${CNone} Specified RWE is not a invalid RWE. Command aborted." 
+      echo -e >&2 "${CError}ERROR:${CNone} Specified RWE is not a invalid RWE. Command aborted." 
       exit 1
    fi
 fi
