Rename root to rwe

diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/list_k8s b/padogrid-deployment/src/main/resources/common/bin_sh/list_k8s
--- a/padogrid-deployment/src/main/resources/common/bin_sh/list_k8s
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/list_k8s
@@ -37,12 +37,12 @@ EOF
 fi
 
 if [ "$PADOGRID_WORKSPACES_HOME" == "" ]; then
-   >&2 echo "ERROR: Workspaces not initialized. Please first run 'create_root' to initialize workspaces."
+   >&2 echo "ERROR: Workspaces not initialized. Please first run 'create_rwe' to initialize workspaces."
    >&2 echo "       Command aborted."
    exit 1
 fi
 if [ ! -d "$PADOGRID_WORKSPACES_HOME" ]; then
-   >&2 echo "ERROR: Invalid workspaces. Please run 'create_root' to initialize workspaces."
+   >&2 echo "ERROR: Invalid workspaces. Please run 'create_rwe' to initialize workspaces."
    >&2 echo "       Command aborted."
    exit 1
 fi
