Tidied up cluster execution plane

diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/make_cluster b/padogrid-deployment/src/main/resources/common/bin_sh/make_cluster
--- a/padogrid-deployment/src/main/resources/common/bin_sh/make_cluster
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/make_cluster
@@ -171,7 +171,7 @@ elif [ "$PRODUCT_ARG" == "coherence" ]; then
 fi
 
 if [ "$PRODUCT_EXISTS" == "false" ]; then
-   echo >&2 "ERROR: The specified product has not been installed: [$PRODUCT_ARG]"
+   echo >&2 "ERROR: The specified product has not been installed or configured: [$PRODUCT_ARG]"
    echo >&2 "       Command aborted."
    exit 1
 fi
