Reassgined default ports to prevent conflicts

diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/open_jupyter b/padogrid-deployment/src/main/resources/common/bin_sh/open_jupyter
--- a/padogrid-deployment/src/main/resources/common/bin_sh/open_jupyter
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/open_jupyter
@@ -75,8 +75,8 @@ EOF
    exit
 fi
 
-if [ "$(which jupyter)" == "" ]; then
-   echo >&2 "ERROR: jupyter executable not found. Command aborted."
+if [ "$(which jupyter 2> /dev/null)" == "" ]; then
+   echo >&2 -e "${CLightRed}ERROR:${CNone} jupyter executable not found. Command aborted."
    exit 1
 fi
    
