Added additional support for multitenancy

diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/show_rwe b/padogrid-deployment/src/main/resources/common/bin_sh/show_rwe
--- a/padogrid-deployment/src/main/resources/common/bin_sh/show_rwe
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/show_rwe
@@ -66,12 +66,12 @@ EOF
 fi
 
 if [ "$PADOGRID_WORKSPACES_HOME" == "" ]; then
-   echo >&2 "ERROR: Workspaces not initialized. Please first run 'create_rwe' to initialize workspaces."
+   echo >&2 -e "${CError}ERROR:${CNone} Workspaces not initialized. Please first run 'create_rwe' to initialize workspaces."
    echo >&2 "       Command aborted."
    exit 1
 fi
 if [ ! -d "$PADOGRID_WORKSPACES_HOME" ]; then
-   echo >&2 "ERROR: Invalid workspaces. Please run 'create_rwe' to initialize workspaces."
+   echo >&2 -e "${CError}ERROR:${CNone} Invalid workspaces. Please run 'create_rwe' to initialize workspaces."
    echo >&2 "       Command aborted."
    exit 1
 fi
@@ -84,10 +84,10 @@ else
    __RWE_PATH="$RWE_PARENT_DIR/$RWE_ARG"
    RWE_NAME=$RWE_ARG
    if [ ! -d "$__RWE_PATH" ]; then
-      echo >&2 "ERROR: Specified RWE does not exist [$RWE_ARG]. Command aborted."
+      echo >&2 -e "${CError}ERROR:${CNone} Specified RWE does not exist [$RWE_ARG]. Command aborted."
       exit 1
    elif [ "$(isValidRwe $RWE_ARG)" == "false" ]; then
-      echo >&2 "ERROR: Specified RWE is not valid [$RWE_ARG]. Command aborted."
+      echo >&2 -e "${CError}ERROR:${CNone} Specified RWE is not valid [$RWE_ARG]. Command aborted."
       exit 1
    fi
 fi
