Added preliminary support for Kafka

diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/update_products b/padogrid-deployment/src/main/resources/common/bin_sh/update_products
--- a/padogrid-deployment/src/main/resources/common/bin_sh/update_products
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/update_products
@@ -37,7 +37,7 @@ WORKSPACE_NAME=$(basename $PADOGRID_WORKSPACE)
 
 __options()
 {
-   echo "-?"
+   echo "-product -?"
 }
 
 if [ "$OPTIONS" == "true" ]; then
@@ -55,7 +55,7 @@ NAME
    $EXECUTABLE - Interatively add or update product versions in the current RWE
 
 SYNOPSIS
-   $EXECUTABLE [-?]
+   $EXECUTABLE [-product product_name] [-?]
 
 DESCRIPTION
    Interactively add or update the current PadoGrid environment (RWE) with the installed product
@@ -63,12 +63,39 @@ DESCRIPTION
    products are installed. If you have products installed in other directories, then you can use
    the 'change_version' command or manually enter them in the RWE and/or workspace setenv.sh file.
 
+OPTIONS
+   -product product_name
+             Product to update. The product name must be one of the following.
+
+EOF
+for i in $DOWNLOADABLE_PRODUCTS; do
+   echo "             $i"
+done
+   echo "             jet-mc"
+cat <<EOF
+
+NOTES
+   PadoGrid support for Kafka is limited to the new RAFT mode which requires Kafka 2.8.0 or
+   a later version.
+
 EOF
 cat <<EOF
 SEE ALSO
 EOF
    printSeeAlsoList "change_version install_padogrid show_products" $EXECUTABLE
    exit
+fi
+
+# Exit if invalid product specified
+if [ "$PRODUCT_ARG" != "" ]; then
+   if [ "$(containsWord "$DOWNLOADABLE_PRODUCTS jet-mc" "$PRODUCT_ARG")" == "false" ]; then
+      echo -e >&2 "${CLightRed}ERROR:${CNone} Invalid product name: [$PRODUCT_ARG]. Please enter one of the following products."
+      for i in $DOWNLOADABLE_PRODUCTS; do
+         echo >&2 "          $i"
+      done
+      echo >&2 "       Command aborted."
+      exit 1
+   fi
 fi
 
 function getProductVersions
@@ -99,6 +126,8 @@ function getProductVersions
    fi
    __SNAPPYDATA_VERSION=${SNAPPYDATA_HOME#*snappydata-}
    __SPARK_VERSION=${SPARK_HOME#*spark-}
+   __KAFKA_VERSION=${KAFKA_HOME#*kafka_}
+   __HADOOP_VERSION=${HADOOP_HOME#*hadoop-}
 }
 
 #
@@ -167,6 +196,8 @@ JET_OSS_VERSIONS="(none) $JET_OSS_VERSIONS"
 JET_MANAGEMENT_CENTER_VERSIONS="(none) $JET_MANAGEMENT_CENTER_VERSIONS"
 SNAPPYDATA_VERSIONS="(none) $SNAPPYDATA_VERSIONS"
 SPARK_VERSIONS="(none) $SPARK_VERSIONS"
+KAFKA_VERSIONS="(none) $KAFKA_VERSIONS"
+HADOOP_VERSIONS="(none) $HADOOP_VERSIONS"
 
 # Convert to array
 __PADOGRID_VERSIONS=($PADOGRID_VERSIONS)
@@ -181,6 +212,8 @@ __JET_OSS_VERSIONS=($JET_OSS_VERSIONS)
 __JET_MANAGEMENT_CENTER_VERSIONS=($JET_MANAGEMENT_CENTER_VERSIONS)
 __SNAPPYDATA_VERSIONS=($SNAPPYDATA_VERSIONS)
 __SPARK_VERSIONS=($SPARK_VERSIONS)
+__KAFKA_VERSIONS=($KAFKA_VERSIONS)
+__HADOOP_VERSIONS=($HADOOP_VERSIONS)
 
 echo ""
 echo "Products Directoy:"
@@ -202,6 +235,8 @@ SELECTED_INDEX_JET_OSS=""
 SELECTED_INDEX_JET_MC=""
 SELECTED_INDEX_SNAPPYDATA=""
 SELECTED_INDEX_SPARK=""
+SELECTED_INDEX_KAFKA=""
+SELECTED_INDEX_HADOOP=""
 
 # Product PRODUCT_EVAL_ARRAY.
 INDEX_PADOGRID=0
@@ -214,9 +249,11 @@ INDEX_JET=6
 INDEX_JET_MC=7
 INDEX_SNAPPYDATA=8
 INDEX_SPARK=9
+INDEX_KAFKA=10
+INDEX_HADOOP=11
 
 # PRODUCT_HOME_ARRAY contains an ordered list of product home environment variable names
-PRODUCT_HOME_ARRAY=(PADOGRID_HOME PADO_HOME GEMFIRE_HOME GEODE_HOME HAZELAST_HOME HAZELCAST_MC_HOME JET_HOME JET_MC_HOME SNAPPYDATA_HOME SPARK_HOME)
+PRODUCT_HOME_ARRAY=(PADOGRID_HOME PADO_HOME GEMFIRE_HOME GEODE_HOME HAZELAST_HOME HAZELCAST_MC_HOME JET_HOME JET_MC_HOME SNAPPYDATA_HOME SPARK_HOME KAFKA_HOME HADOOP_HOME)
 
 # PRODUCT_EVAL_ARRAY is an ordered list of selected product versions. See INDEX_ variables above.
 # [0] PADOGRID
@@ -229,49 +266,74 @@ PRODUCT_HOME_ARRAY=(PADOGRID_HOME PADO_HOME GEMFIRE_HOME GEODE_HOME HAZELAST_HOM
 # [7] JET_MC
 # [8] SNAPPYDATA
 # [9] SPARK
+# [10] KAFKA
+# [11] HADOOP
 # "none" indicates no product selection
-PRODUCT_EVAL_ARRAY=(none none none none none none none none none none)
+unset PRODUCT_EVAL_ARRAY
+let LAST_INDEX=${#PRODUCT_HOME_ARRAY[@]}-1
+for i in $(seq 0 $LAST_INDEX); do
+  PRODUCT_EVAL_ARRAY[$i]="none"
+done
 
 REDO="true"
 while [ "$REDO" == "true" ]; do
    # PadoGrid
-   doUserInput "PadoGrid" "$PADOGRID_VERSIONS" "$PADOGRID_VERSION" "$SELECTED_INDEX_PADOGRID"
-   echo "Selected: [$SELECTED_INDEX] ${__PADOGRID_VERSIONS[$SELECTED_INDEX]}"
-   SELECTED_INDEX_PADOGRID=$SELECTED_INDEX
-   PRODUCT_EVAL_ARRAY[$INDEX_PADOGRID]=${__PADOGRID_VERSIONS[$SELECTED_INDEX]}
-   echo ""
+   if [ "$PRODUCT_ARG" == "" ] || [ "$PRODUCT_ARG" == "padogrid" ]; then
+      doUserInput "PadoGrid" "$PADOGRID_VERSIONS" "$PADOGRID_VERSION" "$SELECTED_INDEX_PADOGRID"
+      echo "Selected: [$SELECTED_INDEX] ${__PADOGRID_VERSIONS[$SELECTED_INDEX]}"
+      SELECTED_INDEX_PADOGRID=$SELECTED_INDEX
+      PRODUCT_EVAL_ARRAY[$INDEX_PADOGRID]=${__PADOGRID_VERSIONS[$SELECTED_INDEX]}
+   fi
    
    # Pado
-   doUserInput "Pado" "$PADO_VERSIONS" "__$PADO_VERSION" "$SELECTED_INDEX_PADO"
-   echo "Selected: [$SELECTED_INDEX] ${__PADO_VERSIONS[$SELECTED_INDEX]}"
-   SELECTED_INDEX_PADO=$SELECTED_INDEX
-   PRODUCT_EVAL_ARRAY[$INDEX_PADO]=${__PADO_VERSIONS[$SELECTED_INDEX]}
-   echo ""
+   if [ "$PRODUCT_ARG" == "" ] || [ "$PRODUCT_ARG" == "pado" ]; then
+      doUserInput "Pado" "$PADO_VERSIONS" "__$PADO_VERSION" "$SELECTED_INDEX_PADO"
+      echo "Selected: [$SELECTED_INDEX] ${__PADO_VERSIONS[$SELECTED_INDEX]}"
+      SELECTED_INDEX_PADO=$SELECTED_INDEX
+      PRODUCT_EVAL_ARRAY[$INDEX_PADO]=${__PADO_VERSIONS[$SELECTED_INDEX]}
+      echo ""
+   fi
    
    # GemFire
-   doUserInput "GemFire" "$GEMFIRE_VERSIONS" "$__GEMFIRE_VERSION" "$SELECTED_INDEX_GEMFIRE"
-   echo "Selected: [$SELECTED_INDEX] ${__GEMFIRE_VERSIONS[$SELECTED_INDEX]}"
-   SELECTED_INDEX_GEMFIRE=$SELECTED_INDEX
-   PRODUCT_EVAL_ARRAY[$INDEX_GEMFIRE]=${__GEMFIRE_VERSIONS[$SELECTED_INDEX]}
-   echo ""
+   if [ "$PRODUCT_ARG" == "" ] || [ "$PRODUCT_ARG" == "gemfire" ]; then
+      doUserInput "GemFire" "$GEMFIRE_VERSIONS" "$__GEMFIRE_VERSION" "$SELECTED_INDEX_GEMFIRE"
+      echo "Selected: [$SELECTED_INDEX] ${__GEMFIRE_VERSIONS[$SELECTED_INDEX]}"
+      SELECTED_INDEX_GEMFIRE=$SELECTED_INDEX
+      PRODUCT_EVAL_ARRAY[$INDEX_GEMFIRE]=${__GEMFIRE_VERSIONS[$SELECTED_INDEX]}
+      echo ""
+   fi
    
    # Geode
-   doUserInput "Geode" "$GEODE_VERSIONS" "$__GEODE_VERSION" "$SELECTED_INDEX_GEODE"
-   echo "Selected: [$SELECTED_INDEX] ${__GEODE_VERSIONS[$SELECTED_INDEX]}"
-   SELECTED_INDEX_GEODE=$SELECTED_INDEX
-   PRODUCT_EVAL_ARRAY[$INDEX_GEODE]=${__GEODE_VERSIONS[$SELECTED_INDEX]}
+   if [ "$PRODUCT_ARG" == "" ] || [ "$PRODUCT_ARG" == "geode" ]; then
+      doUserInput "Geode" "$GEODE_VERSIONS" "$__GEODE_VERSION" "$SELECTED_INDEX_GEODE"
+      echo "Selected: [$SELECTED_INDEX] ${__GEODE_VERSIONS[$SELECTED_INDEX]}"
+      SELECTED_INDEX_GEODE=$SELECTED_INDEX
+      PRODUCT_EVAL_ARRAY[$INDEX_GEODE]=${__GEODE_VERSIONS[$SELECTED_INDEX]}
    echo ""
+   fi
 
-   __INNER_LOOP="true"
-   __NONE="false"
-   while [ "$__INNER_LOOP" == "true" ]; do
-      read -p "Do you want to add Hazelcast Enterprise or OSS? Enter 'e' for Enterprise, 'o' for OSS, 'n' for none: " INPUT
-      case $INPUT in
-         [Ee]* ) IS_HAZELCAST_ENTERPRISE="true"; __INNER_LOOP="false";;
-         [Oo]* ) IS_HAZELCAST_ENTERPRISE="false"; __INNER_LOOP="false";;
-         [Nn]* ) IS_HAZELCAST_ENTERPRISE="false"; __NONE="true"; __INNER_LOOP="false";;
-      esac
-   done
+   if [ "$PRODUCT_ARG" == "" ]; then
+      __NONE="false"
+      __INNER_LOOP="true"
+      while [ "$__INNER_LOOP" == "true" ]; do
+         read -p "Do you want to add Hazelcast Enterprise or OSS? Enter 'e' for Enterprise, 'o' for OSS, 'n' for none: " INPUT
+         case $INPUT in
+            [Ee]* ) IS_HAZELCAST_ENTERPRISE="true"; __INNER_LOOP="false";;
+            [Oo]* ) IS_HAZELCAST_ENTERPRISE="false"; __INNER_LOOP="false";;
+            [Nn]* ) IS_HAZELCAST_ENTERPRISE="false"; __NONE="true"; __INNER_LOOP="false";;
+         esac
+      done
+   else
+      if [ "$PRODUCT_ARG" == "hazelcast-enterprise" ]; then
+         IS_HAZELCAST_ENTERPRISE="true"
+         __NONE="false"
+      elif [ "$PRODUCT_ARG" == "hazelcast-oss" ]; then
+         IS_HAZELCAST_ENTERPRISE="false"
+         __NONE="false"
+      else
+         __NONE="true"
+      fi
+   fi
 
    if [ "$__NONE" == "false" ]; then
       if [ "$IS_HAZELCAST_ENTERPRISE" == "true" ]; then
@@ -292,22 +354,36 @@ while [ "$REDO" == "true" ]; do
    fi
 
    # Hazelcast Management Center
-   doUserInput "Hazelcast Management Center" "$HAZELCAST_MANAGEMENT_CENTER_VERSIONS" "$__HAZELCAST_MC_VERSION" "$SELECTED_INDEX_HAZELCAST_MC"
-   echo "Selected: [$SELECTED_INDEX] ${__HAZELCAST_MANAGEMENT_CENTER_VERSIONS[$SELECTED_INDEX]}"
-   SELECTED_INDEX_HAZELCAST_MC=$SELECTED_INDEX
-   PRODUCT_EVAL_ARRAY[$INDEX_HAZELCAST_MC]=${__HAZELCAST_MANAGEMENT_CENTER_VERSIONS[$SELECTED_INDEX]}
-   echo ""
+   if [ "$PRODUCT_ARG" == "" ] || [ "$PRODUCT_ARG" == "hazelcast-mc" ]; then
+      doUserInput "Hazelcast Management Center" "$HAZELCAST_MANAGEMENT_CENTER_VERSIONS" "$__HAZELCAST_MC_VERSION" "$SELECTED_INDEX_HAZELCAST_MC"
+      echo "Selected: [$SELECTED_INDEX] ${__HAZELCAST_MANAGEMENT_CENTER_VERSIONS[$SELECTED_INDEX]}"
+      SELECTED_INDEX_HAZELCAST_MC=$SELECTED_INDEX
+      PRODUCT_EVAL_ARRAY[$INDEX_HAZELCAST_MC]=${__HAZELCAST_MANAGEMENT_CENTER_VERSIONS[$SELECTED_INDEX]}
+      echo ""
+   fi
 
-   __INNER_LOOP="true"
-   __NONE="false"
-   while [ "$__INNER_LOOP" == "true" ]; do
-      read -p "Do you want to add Jet Enterprise or OSS? Enter 'e' for Enterprise, 'o' for OSS, 'n' for none: " INPUT
-      case $INPUT in
-         [Ee]* ) IS_JET_ENTERPRISE="true"; __INNER_LOOP="false";;
-         [Oo]* ) IS_JET_ENTERPRISE="false"; __INNER_LOOP="false";;
-         [Nn]* ) IS_HAZELCAST_ENTERPRISE="false"; __NONE="true"; __INNER_LOOP="false";;
-      esac
-   done
+   if [ "$PRODUCT_ARG" == "" ]; then
+      __INNER_LOOP="true"
+      __NONE="false"
+      while [ "$__INNER_LOOP" == "true" ]; do
+         read -p "Do you want to add Jet Enterprise or OSS? Enter 'e' for Enterprise, 'o' for OSS, 'n' for none: " INPUT
+         case $INPUT in
+            [Ee]* ) IS_JET_ENTERPRISE="true"; __INNER_LOOP="false";;
+            [Oo]* ) IS_JET_ENTERPRISE="false"; __INNER_LOOP="false";;
+            [Nn]* ) IS_HAZELCAST_ENTERPRISE="false"; __NONE="true"; __INNER_LOOP="false";;
+         esac
+      done
+    else
+      if [ "$PRODUCT_ARG" == "jet-enterprise" ]; then
+         IS_JET_ENTERPRISE="true"
+         __NONE="false"
+      elif [ "$PRODUCT_ARG" == "jet-oss" ]; then
+         IS_JET_ENTERPRISE="false"
+         __NONE="false"
+      else
+         __NONE="true"
+      fi
+   fi
 
    if [ "$__NONE" == "false" ]; then
       if [ "$IS_JET_ENTERPRISE" == "true" ]; then
@@ -328,25 +404,49 @@ while [ "$REDO" == "true" ]; do
    fi
 
    # Jet Management Center
-   doUserInput "Jet Management Center" "$JET_MANAGEMENT_CENTER_VERSIONS" "$__JET_MC_VERSION" "$SELECTED_INDEX_JET_MC"
-   echo "Selected: [$SELECTED_INDEX] ${__JET_MANAGEMENT_CENTER_VERSIONS[$SELECTED_INDEX]}"
-   SELECTED_INDEX_JET_MC=$SELECTED_INDEX
-   PRODUCT_EVAL_ARRAY[$INDEX_JET_MC]=${__JET_MANAGEMENT_CENTER_VERSIONS[$SELECTED_INDEX]}
-   echo ""
+   if [ "$PRODUCT_ARG" == "" ] || [ "$PRODUCT_ARG" == "jet-mc" ]; then
+      doUserInput "Jet Management Center" "$JET_MANAGEMENT_CENTER_VERSIONS" "$__JET_MC_VERSION" "$SELECTED_INDEX_JET_MC"
+      echo "Selected: [$SELECTED_INDEX] ${__JET_MANAGEMENT_CENTER_VERSIONS[$SELECTED_INDEX]}"
+      SELECTED_INDEX_JET_MC=$SELECTED_INDEX
+      PRODUCT_EVAL_ARRAY[$INDEX_JET_MC]=${__JET_MANAGEMENT_CENTER_VERSIONS[$SELECTED_INDEX]}
+      echo ""
+   fi
 
    # SnappyData
-   doUserInput "SnappyData" "$SNAPPYDATA_VERSIONS" "$__SNAPPYDATA_VERSION" "$SELECTED_INDEX_SNAPPYDATA"
-   echo "Selected: [$SELECTED_INDEX] ${__SNAPPYDATA_VERSIONS[$SELECTED_INDEX]}"
-   PRODUCT_EVAL_ARRAY[$INDEX_SNAPPYDATA]=${__SNAPPYDATA_VERSIONS[$SELECTED_INDEX]}
-   SELECTED_INDEX_SNAPPYDATA=$SELECTED_INDEX
-   echo ""
+   if [ "$PRODUCT_ARG" == "" ] || [ "$PRODUCT_ARG" == "snappydata" ]; then
+      doUserInput "SnappyData" "$SNAPPYDATA_VERSIONS" "$__SNAPPYDATA_VERSION" "$SELECTED_INDEX_SNAPPYDATA"
+      echo "Selected: [$SELECTED_INDEX] ${__SNAPPYDATA_VERSIONS[$SELECTED_INDEX]}"
+      PRODUCT_EVAL_ARRAY[$INDEX_SNAPPYDATA]=${__SNAPPYDATA_VERSIONS[$SELECTED_INDEX]}
+      SELECTED_INDEX_SNAPPYDATA=$SELECTED_INDEX
+      echo ""
+   fi
 
    # Spark
-   doUserInput "Spark" "$SPARK_VERSIONS" "$__SPARK_VERSION" "$SELECTED_INDEX_SPARK"
-   echo "Selected: [$SELECTED_INDEX] ${__SPARK_VERSIONS[$SELECTED_INDEX]}"
-   SELECTED_INDEX_SPARK=$SELECTED_INDEX
-   PRODUCT_EVAL_ARRAY[$INDEX_SPARK]=${__SPARK_VERSIONS[$SELECTED_INDEX]}
-   echo ""
+   if [ "$PRODUCT_ARG" == "" ] || [ "$PRODUCT_ARG" == "spark" ]; then
+      doUserInput "Spark" "$SPARK_VERSIONS" "$__SPARK_VERSION" "$SELECTED_INDEX_SPARK"
+      echo "Selected: [$SELECTED_INDEX] ${__SPARK_VERSIONS[$SELECTED_INDEX]}"
+      SELECTED_INDEX_SPARK=$SELECTED_INDEX
+      PRODUCT_EVAL_ARRAY[$INDEX_SPARK]=${__SPARK_VERSIONS[$SELECTED_INDEX]}
+      echo ""
+   fi
+
+   # Kafka
+   if [ "$PRODUCT_ARG" == "" ] || [ "$PRODUCT_ARG" == "kafka" ]; then
+      doUserInput "Kafka" "$KAFKA_VERSIONS" "$__KAFKA_VERSION" "$SELECTED_INDEX_KAFKA"
+      echo "Selected: [$SELECTED_INDEX] ${__KAFKA_VERSIONS[$SELECTED_INDEX]}"
+      SELECTED_INDEX_KAFKA=$SELECTED_INDEX
+      PRODUCT_EVAL_ARRAY[$INDEX_KAFKA]=${__KAFKA_VERSIONS[$SELECTED_INDEX]}
+      echo ""
+   fi
+
+   # Hadoop
+   if [ "$PRODUCT_ARG" == "" ] || [ "$PRODUCT_ARG" == "hadoop" ]; then
+      doUserInput "Hadoop" "$HADOOP_VERSIONS" "$__HADOOP_VERSION" "$SELECTED_INDEX_HADOOP"
+      echo "Selected: [$SELECTED_INDEX] ${__HADOOP_VERSIONS[$SELECTED_INDEX]}"
+      SELECTED_INDEX_HADOOP=$SELECTED_INDEX
+      PRODUCT_EVAL_ARRAY[$INDEX_HADOOP]=${__HADOOP_VERSIONS[$SELECTED_INDEX]}
+      echo ""
+   fi
 
    __INNER_REDO="true"
    while [ "$__INNER_REDO" == "true" ]; do
@@ -367,10 +467,10 @@ while [ "$REDO" == "true" ]; do
       __INNER_LOOP="true"
       while [ "$__INNER_LOOP" == "true" ]; do
          echo "Apply selected version(s) to the current workspace or all workspaces?"
-         echo "Enter 'c' for current workspace, 'a' for all workspaces,"
+         echo "Enter 'w' for current workspace, 'a' for all workspaces,"
          read -p "      'n' for no workspaces,     'q' to quit this command: " INPUT
          case $INPUT in
-            [Cc]* ) UPDATE_WORKSPACES="current"; __INNER_LOOP=false;;
+            [Ww]* ) UPDATE_WORKSPACES="current"; __INNER_LOOP=false;;
             [Aa]* ) UPDATE_WORKSPACES="all"; __INNER_LOOP=false;;
             [Nn]* ) UPDATE_WORKSPACES="none"; __INNER_LOOP=false;;
             [Qq]* ) exit;;
@@ -404,6 +504,8 @@ while [ "$REDO" == "true" ]; do
    echo "     Jet MC: ${__JET_MANAGEMENT_CENTER_VERSIONS[$SELECTED_INDEX_JET_MC]}"
    echo " SnappyData: ${__SNAPPYDATA_VERSIONS[$SELECTED_INDEX_SNAPPYDATA]}"
    echo "      Spark: ${__SPARK_VERSIONS[$SELECTED_INDEX_SPARK]}"
+   echo "      Kafka: ${__KAFKA_VERSIONS[$SELECTED_INDEX_KAFKA]}"
+   echo "     Hadoop: ${__HADOOP_VERSIONS[$SELECTED_INDEX_HADOOP]}"
    echo ""
    echo "The selected product(s) will be applied to"
    if [ "$UPDATE_RWE" == "true" ]; then
@@ -452,34 +554,36 @@ function getProductDirName
   local IS_ENTERPRISE="$3"
   local DIR_NAME=""
   case $INDEX in
-    [$INDEX_PADOGRID] ) DIR_NAME="padogrid_$VERSION";;
-    [$INDEX_PADO] ) DIR_NAME="pado_$VERSION";;
-    [$INDEX_GEMFIRE] ) DIR_NAME="pivotal-gemfire-$VERSION";;
-    [$INDEX_GEODE] ) DIR_NAME="apache-geode-$VERSION";;
-    [$INDEX_HAZELCAST] )
-       if [ "$IS_ENTERPRISE" == "true" ]; then 
+    $INDEX_PADOGRID ) DIR_NAME="padogrid_$VERSION";;
+    $INDEX_PADO ) DIR_NAME="pado_$VERSION";;
+    $INDEX_GEMFIRE ) DIR_NAME="pivotal-gemfire-$VERSION";;
+    $INDEX_GEODE ) DIR_NAME="apache-geode-$VERSION";;
+    $INDEX_HAZELCAST )
+       if [ "$IS_ENTERPRISE" == "true" ; then 
           DIR_NAME="hazelcast-enterprise-$VERSION"
        else
           DIR_NAME="hazelcast-$VERSION"
        fi
       ;;
-    [$INDEX_HAZELCAST_MC] ) DIR_NAME="hazelcast-management-center-$VERSION";;
-    [$INDEX_JET] )
-       if [ "$IS_ENTERPRISE" == "true" ]; then 
+    $INDEX_HAZELCAST_MC ) DIR_NAME="hazelcast-management-center-$VERSION";;
+    $INDEX_JET )
+       if [ "$IS_ENTERPRISE" == "true" ; then 
           DIR_NAME="hazelcast-jet-enterprise-$VERSION"
        else
           DIR_NAME="hazelcast-jet-$VERSION"
        fi
       ;;
-    [$INDEX_JET_MC] )
+    $INDEX_JET_MC )
        if [[ "$VERSION" == *"4.2021"* ]]; then
           DIR_NAME="hazelcast-management-center-$VERSION"
        else
           DIR_NAME="hazelcast-jet-management-center-$VERSION"
        fi
        ;;
-    [$INDEX_SNAPPYDATA] ) DIR_NAME="snappydata-$VERSION";;
-    [$INDEX_SPARK] ) DIR_NAME="spark-$VERSION";;
+    $INDEX_SNAPPYDATA ) DIR_NAME="snappydata-$VERSION";;
+    $INDEX_SPARK ) DIR_NAME="spark-$VERSION";;
+    $INDEX_KAFKA ) DIR_NAME="kafka_$VERSION";;
+    $INDEX_HADOOP ) DIR_NAME="hadoop-$VERSION";;
   esac
   echo $DIR_NAME
 }
