Overhauled vm_* commands (#2)

diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/vm_deploy_padogrid b/padogrid-deployment/src/main/resources/common/bin_sh/vm_deploy_padogrid
--- a/padogrid-deployment/src/main/resources/common/bin_sh/vm_deploy_padogrid
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/vm_deploy_padogrid
@@ -31,14 +31,6 @@ if [ "$OPTIONS" == "true" ]; then
    exit
 fi
 
-#
-# Determeint $TAR_BALL_PATH
-#
-ROOT_DIR_NAME=$(basename $PADOGRID_HOME)
-TOP_DIR="$(dirname "$BASE_DIR")"
-TAR_BALL_GZ_NAME=$ROOT_DIR_NAME.tar.gz
-TAR_BALL_GZ_PATH=$PADOGRID_WORKSPACE/bundles/$TAR_BALL_GZ_NAME
-
 if [ "$HELP" == "true" ]; then
 cat <<EOF
 
@@ -160,18 +152,17 @@ else
    fi
 fi
 
-echo "----------------------------------------------------------------"
-echo "WORKSPACE: $PADOGRID_WORKSPACE"
-echo "Deploying padogrid to the following VM hosts:"
-echo "    $VM_HOSTS"
-echo "----------------------------------------------------------------"
+if [ "$REMOTE_SPECIFIED" == "false" ]; then
+   echo "----------------------------------------------------------------"
+   echo "WORKSPACE: $PADOGRID_WORKSPACE"
+   echo "Deploying padogrid to the following VM hosts:"
+   echo "    $VM_HOSTS"
+   echo "----------------------------------------------------------------"
+fi
 
-# Replace , with space
-__VM_HOSTS=$(echo "$VM_HOSTS" | sed "s/,/ /g")
-DEFAULT_USER=$(whoami)
-VM_USER=`getClusterProperty "vm.user" "$DEFAULT_USER"`
+VM_USER=`getVmUser`
 KEY_FILE=`getClusterProperty "vm.privateKeyFile"`
-if [ "$KEY_FILE" == "" ]; then 
+if [ "$KEY_FILE" == "" ]; then
    # Set the first private key file found in the workspace directory if exists
    __VM_PRIVATE_KEY_FILE_FOUND="false"
    if [ "$VM_PRIVATE_KEY_FILE" == "" ]; then
@@ -189,33 +180,59 @@ if [ "$KEY_FILE" == "" ]; then
          done
       fi
    fi
+   # Replace '~' with the VM home path
+   KEY_FILE=$(echo $VM_PRIVATE_KEY_FILE | sed "s|\~|$HOME|")
+fi
+if [ "$KEY_FILE" == "" ]; then 
    KEY_FILE="$VM_PRIVATE_KEY_FILE"
 fi
-if [ ! -f "$KEY_FILE" ]; then
-   echo >&2 "ERROR: Private key does not exist [$KEY_FILE]."
-   echo >&2 "       Command aborted."
-   exit 1
-fi
-if [ "$KEY_FILE" == "" ]; then
-   VM_KEY=""
-else
+VM_KEY=""
+if [ "$KEY_FILE" != "" ]; then 
+   if [ ! -f "$KEY_FILE" ]; then
+      echo -e >&2 "${CError}ERROR:${CNone} Specified private key does not exist [$KEY_FILE]."
+      echo >&2 "       Command aborted."
+      exit 1
+   fi
    VM_KEY="-i $KEY_FILE"
 fi
 
 # Fail fast: Exit if any of the hosts is not reachable
-for VM_HOST in $__VM_HOSTS; do
-   REPLY=$(ssh -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT -o PasswordAuthentication=no "echo hello" 2>&1)
-   EXIT_CODE=$?
-   if [ "$EXIT_CODE" != "0" ]; then
-      echo -e "ERROR: $VM_HOST - ${CLightRed}Failed${CNone} ($REPLY)"
+#for VM_HOST in $__VM_HOSTS; do
+#   REPLY=$(ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT -o PasswordAuthentication=no "echo hello" 2>&1)
+#   EXIT_CODE=$?
+#   if [ "$EXIT_CODE" != "0" ]; then
+#      echo -e "ERROR: $VM_HOST - ${CLightRed}Failed${CNone} ($REPLY)"
+#      echo "       Command aborted."
+#      exit 1
+#   fi
+#done
+
+# Simulation runs in the quiet mode
+if [ "$SIMULATE" == "true" ]; then
+   QUIET=$SIMULATE
+fi
+
+IS_PUBLIC_HOST="false"
+if [ "$(isVmPrivateHostReachable "$VM_USER" "$VM_KEY")" == "true" ]; then
+   echo "Scanning VMs... Please wait."
+   # If private hosts are reachable then execute from here.
+   # Replace , with space
+   __VM_HOSTS=$(echo "$VM_HOSTS" | sed "s/,/ /g")
+else
+   # If private hosts are not reachable then deploy to the first public host and then
+   # use that public as a proxy to execute this command.
+   echo "Scanning public VM... Please wait."
+   VM_PUBLIC_HOSTS=`getClusterProperty "vm.public.hosts"`
+   if [ "$VM_PUBLIC_HOSTS" == "" ]; then
+      echo -e >&2 "${CError}ERROR:${CNone} Unable to connect to VM hosts. Please set 'vm.public.hosts' in 'etc/cluster.properties."
       echo "       Command aborted."
       exit 1
    fi
-done
 
-# Simulation runs in the quite mode
-if [ "$SIMULATE" == "true" ]; then
-   QUIET=$SIMULATE
+   # Use the first public host
+   VM_HOST=$(echo "$VM_PUBLIC_HOSTS" | sed "s/,.*//g")
+   __VM_HOSTS=$VM_HOST
+   IS_PUBLIC_HOST="true"
 fi
 
 # Find all existing and new hosts
@@ -226,11 +243,11 @@ COMMAND="if [ -d "$VM_PADOGRID_HOME" ]; then echo true; else echo false; fi"
 EXISTING_HOST_COUNT=0
 NEW_HOST_COUNT=0
 for VM_HOST in $__VM_HOSTS; do
-   HOST_NAME=`ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "hostname"`
+   HOST_NAME=`ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "hostname"`
    if [ "$HOST_NAME" == "$THIS_VM_HOSTNAME" ]; then
       continue
    fi
-   DIR_EXISTS=`ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT $COMMAND`
+   DIR_EXISTS=`ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT $COMMAND`
    if [ "$DIR_EXISTS" == "true" ]; then
       EXISTING_HOSTS="$EXISTING_HOSTS $VM_HOST"
       let EXISTING_HOST_COUNT=EXISTING_HOST_COUNT+1
@@ -240,16 +257,20 @@ for VM_HOST in $__VM_HOSTS; do
    fi
 done
 
-echo ""
-echo "padogrid installation found in the following host(s):"
-echo "   $EXISTING_HOSTS"
-echo ""
-echo "padogrid not found in the following host(s):"
-echo "   $NEW_HOSTS"
-echo ""
+if [ "$EXISTING_HOSTS" != "" ]; then
+   echo ""
+   echo "padogrid installation found in the following host(s):"
+   echo "   $EXISTING_HOSTS"
+fi
+
+if [ "$NEW_HOSTS" != "" ]; then
+   echo ""
+   echo "padogrid installation not found in the following host(s):"
+   echo "   $NEW_HOSTS"
+fi
 DEPLOYMENT_HOST_COUNT=$NEW_HOST_COUNT
 INPUT=
-if [ "$QUIET" == "false" ]; then
+if [ "$QUIET" == "false" ] && [ "$OVERWRITE" != "true" ]; then
    if [ "$EXISTING_HOSTS" != "" ]; then
       echo "Do you want to overwrite the existing installations?"
       echo "('overwrite' + Enter to overwrite the installations, other keys to continue.)"
@@ -260,7 +281,6 @@ if [ "$QUIET" == "false" ]; then
    OVERWRITE="false"
    if [ "$INPUT" == "overwrite" ]; then
       OVERWRITE="true"
-      let DEPLOYMENT_HOST_COUNT=DEPLOYMENT_HOST_COUNT+EXISTING_HOST_COUNT
       echo "This installation will be deployed to both existing and new hosts."
    else
       echo "Existing installations will be skipped."
@@ -277,37 +297,48 @@ if [ "$QUIET" == "false" ]; then
    fi
 fi
 
-if [ $DEPLOYMENT_HOST_COUNT -eq 0 ]; then
-   echo "No qualified hosts found. Command aborted." 
-   echo ""
-   exit
+if [ "$OVERWRITE" == "true" ]; then
+   let DEPLOYMENT_HOST_COUNT=DEPLOYMENT_HOST_COUNT+EXISTING_HOST_COUNT
+fi
+
+if [ "$IS_PUBLIC_HOST" != "true" ]; then
+   if [ $DEPLOYMENT_HOST_COUNT -eq 0 ]; then
+      exit
+   fi
 fi
 
 echo "Total deployment host count: $DEPLOYMENT_HOST_COUNT"
-echo "Creating a tar ball..."
+
+DOWNLOADS_DIR="$PADOGRID_ENV_BASE_PATH/downloads"
 ROOT_DIR_NAME=$(basename $PADOGRID_HOME)
 TAR_BALL_NAME=$ROOT_DIR_NAME.tar
+TAR_BALL_GZ_NAME=$ROOT_DIR_NAME.tar.gz
+TAR_BALL_GZ_PATH="$DOWNLOADS_DIR/$TAR_BALL_GZ_NAME"
 TAR_BALL_PATH=$PADOGRID_WORKSPACE/bundles/$TAR_BALL_NAME
 VM_PADOGRID_HOME_PARENT_DIR="$(dirname "$VM_PADOGRID_HOME")"
 
+echo "Creating a tar ball: [$TAR_BALL_GZ_PATH]..."
 if [ "$SIMULATE" != "true" ]; then
-   pushd $PADOGRID_HOME/.. 
+   pushd $PADOGRID_HOME/..  > /dev/null 2>&1
    tar czf $TAR_BALL_GZ_PATH $ROOT_DIR_NAME
-   popd
+   popd > /dev/null 2>&1
 fi
+
+ROOT_DIR_NAME=$(basename $PADOGRID_HOME)
+VM_PADOGRID_TARBALL_GZ_PATH="$VM_PADOGRID_ENV_BASE_PATH/downloads/$TAR_BALL_GZ_NAME"
 
 if [ "$NEW_HOSTS" != "" ]; then
    echo "New Hosts:"
    for VM_HOST in $NEW_HOSTS; do
       echo "   Deploying to $VM_HOST..."
       if [ "$SIMULATE" == "true" ]; then
-         echo ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "mkdir -p $VM_PADOGRID_HOME_PARENT_DIR"
-         echo scp -q -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY $TAR_BALL_GZ_PATH $VM_USER@$VM_HOST:/tmp
-         echo ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "tar -C $VM_PADOGRID_HOME_PARENT_DIR -xzf /tmp/$TAR_BALL_GZ_NAME; rm /tmp/$TAR_BALL_GZ_NAME"
+         echo ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "mkdir -p $VM_PADOGRID_HOME_PARENT_DIR"
+         echo scp -q -o stricthostkeychecking=no -o LogLevel=error -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY $TAR_BALL_GZ_PATH $VM_USER@$VM_HOST:$VM_PADOGRID_TARBALL_GZ_PATH
+         echo ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "tar -C $VM_PADOGRID_HOME_PARENT_DIR -xzf $VM_PADOGRID_TARBALL_GZ_PATH"
       else
-         ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "mkdir -p $VM_PADOGRID_HOME_PARENT_DIR"
-         scp -q -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY $TAR_BALL_GZ_PATH $VM_USER@$VM_HOST:/tmp
-         ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "tar -C $VM_PADOGRID_HOME_PARENT_DIR -xzf /tmp/$TAR_BALL_GZ_NAME; rm /tmp/$TAR_BALL_GZ_NAME"
+         ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "mkdir -p $VM_PADOGRID_HOME_PARENT_DIR"
+         scp -q -o stricthostkeychecking=no -o LogLevel=error -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY $TAR_BALL_GZ_PATH $VM_USER@$VM_HOST:$VM_PADOGRID_TARBALL_GZ_PATH
+         ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "tar -C $VM_PADOGRID_HOME_PARENT_DIR -xzf $VM_PADOGRID_TARBALL_GZ_PATH"
       fi
    done
 fi
@@ -317,17 +348,37 @@ if [ "$EXISTING_HOSTS" != "" ] && [ "$OVERWRITE" == "true" ] ; then
    for VM_HOST in $EXISTING_HOSTS; do
       echo "   Deploying to $VM_HOST..."
       if [ "$SIMULATE" == "true" ]; then
-         echo scp -q -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY $TAR_BALL_GZ_PATH $VM_USER@$VM_HOST:/tmp
-         echo ssh -q -n $VM_USER@$VM_HOST -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "tar -C $VM_PADOGRID_HOME_PARENT_DIR -xzf /tmp/$TAR_BALL_GZ_NAME; rm /tmp/$TAR_BALL_GZ_NAME"
+         echo scp -q -o stricthostkeychecking=no -o LogLevel=error -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY $TAR_BALL_GZ_PATH $VM_USER@$VM_HOST:$VM_PADOGRID_TARBALL_GZ_PATH
+         echo ssh -n $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "tar -C $VM_PADOGRID_HOME_PARENT_DIR -xzf $VM_PADOGRID_TARBALL_GZ_PATH"
       else
-         scp -q -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY $TAR_BALL_GZ_PATH $VM_USER@$VM_HOST:/tmp
-         ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "tar -C $VM_PADOGRID_HOME_PARENT_DIR -xzf /tmp/$TAR_BALL_GZ_NAME; rm /tmp/$TAR_BALL_GZ_NAME"
+         scp -q -o stricthostkeychecking=no -o LogLevel=error -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY $TAR_BALL_GZ_PATH $VM_USER@$VM_HOST:$VM_PADOGRID_TARBALL_GZ_PATH
+         ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "tar -C $VM_PADOGRID_HOME_PARENT_DIR -xzf $VM_PADOGRID_TARBALL_GZ_PATH"
       fi
    done
 fi
-echo ""
-if [ "$SIMULATE" == "true" ]; then
-   echo "Simulation deployment complete."
-else
-   echo "Deployment complete."
+
+if [ "$IS_PUBLIC_HOST" == "true" ]; then
+   # Use the public host a proxy to sync the rest of hosts
+   #RWE_NAME=$(basename $PADOGRID_WORKSPACES_HOME)
+   #WORKSPACE=$(basename $PADOGRID_WORKSPACE)
+   RWE_NAME=$(basename $VM_PADOGRID_WORKSPACES_HOME)
+   WORKSPACE=$(basename $VM_PADOGRID_WORKSPACE)
+   if [ "$OVERWRITE" == "true" ]; then
+      COMMAND_OPTS="-overwrite"
+   fi
+   if [ "$SIMULATE" == "true" ]; then
+      echo ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "switch_rwe $RWE_NAME/$WORKSPACE && $COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/$EXECUTABLE $COMMAND_OPTS -remote -cluster $CLUSTER $@"
+   else
+      ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "switch_rwe $RWE_NAME/$WORKSPACE && $COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/$EXECUTABLE $COMMAND_OPTS -remote -cluster $CLUSTER $@"
+   fi
+fi
+
+
+if [ "$REMOTE_SPECIFIED" == "false" ]; then
+   echo ""
+   if [ "$SIMULATE" == "true" ]; then
+      echo "Simulation deployment complete."
+   else
+      echo "Deployment complete."
+   fi
 fi
diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/vm_download b/padogrid-deployment/src/main/resources/common/bin_sh/vm_download
--- a/padogrid-deployment/src/main/resources/common/bin_sh/vm_download
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/vm_download
@@ -129,10 +129,7 @@ if [ "$VM_HOSTS" == "" ]; then
    echo "----------------------------------------------------------------"
 fi
 
-# Replace , with space
-__VM_HOSTS=$(echo "$VM_HOSTS" | sed "s/,/ /g")
-DEFAULT_USER=$(whoami)
-VM_USER=`getClusterProperty "vm.user" "$DEFAULT_USER"`
+VM_USER=`getVmUser`
 KEY_FILE=`getClusterProperty "vm.privateKeyFile"`
 if [ "$KEY_FILE" == "" ]; then
    # Set the first private key file found in the workspace directory if exists
@@ -152,17 +149,45 @@ if [ "$KEY_FILE" == "" ]; then
          done
       fi
    fi
+   # Replace '~' with the VM home path
+   KEY_FILE=$(echo $VM_PRIVATE_KEY_FILE | sed "s|\~|$HOME|")
+fi
+if [ "$KEY_FILE" == "" ]; then 
    KEY_FILE="$VM_PRIVATE_KEY_FILE"
 fi
-if [ "$KEY_FILE" != "" ] && [ ! -f "$KEY_FILE" ]; then
-   echo >&2 "ERROR: Private key does not exist [$KEY_FILE]."
-   echo >&2 "       Command aborted."
-   exit 1
-fi
-if [ "$KEY_FILE" == "" ]; then
-   VM_KEY=""
-else
+VM_KEY=""
+if [ "$KEY_FILE" != "" ]; then 
+   if [ ! -f "$KEY_FILE" ]; then
+      echo -e >&2 "${CError}ERROR:${CNone} Specified private key does not exist [$KEY_FILE]."
+      echo >&2 "       Command aborted."
+      exit 1
+   fi
    VM_KEY="-i $KEY_FILE"
+fi
+
+if [ "$(isVmPrivateHostReachable "$VM_USER" "$VM_KEY")" == "true" ]; then
+   echo "Scanning VMs... Please wait."
+   # If private hosts are reachable then execute from here.
+   # Replace , with space
+   __VM_HOSTS=$(echo "$VM_HOSTS" | sed "s/,/ /g")
+else
+   # If private hosts are not reachable then download files in the first public host and then
+   # download files form the public host to this host.
+   echo "Scanning public VM... Please wait."
+   VM_PUBLIC_HOSTS=`getClusterProperty "vm.public.hosts"`
+   if [ "$VM_PUBLIC_HOSTS" == "" ]; then
+      echo -e >&2 "${CError}ERROR:${CNone} Unable to connect to VM hosts. Please set 'vm.public.hosts' in 'etc/cluster.properties."
+      echo "       Command aborted."
+      exit 1
+   fi
+
+   # Download from the first public host
+   VM_HOST=$(echo "$VM_PUBLIC_HOSTS" | sed "s/,.*//g")
+   RWE_NAME=$(basename $VM_PADOGRID_WORKSPACES_HOME)
+   WORKSPACE=$(basename $VM_PADOGRID_WORKSPACE)
+   ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "switch_rwe $RWE_NAME/$WORKSPACE && $COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/$EXECUTABLE -remote -cluster $CLUSTER $@"
+
+   __VM_HOSTS=$VM_HOST
 fi
 
 # Find all existing and new hosts
@@ -191,7 +216,7 @@ for VM_HOST in $__VM_HOSTS; do
    if [ "$VM_HOST" == "$THIS_VM_HOSTNAME" ]; then
       continue
    fi
-   HOSTNAME=`ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "hostname"`
+   HOSTNAME=`ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "hostname"`
    if [ "$HOSTNAME" == "" ]; then
       echo "Invalid host [$VM_HOST]"
       continue
@@ -200,19 +225,21 @@ for VM_HOST in $__VM_HOSTS; do
    fi
 
    echo "   Downloading $VM_HOST..."
-   scp -q -r -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY $VM_USER@$VM_HOST:$FROM_LOG_DIR/*.log $LOG_DIR/ 
+   scp -q -r -o stricthostkeychecking=no -o LogLevel=error -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY $VM_USER@$VM_HOST:$FROM_LOG_DIR/*.log $LOG_DIR/ 
    case $CLUSTER_TYPE in
    geode|gemfire)
-         scp -q -r -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY $VM_USER@$VM_HOST:$FROM_STATS_DIR/*.gfs $STATS_DIR/ ;;
+         scp -q -r -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY $VM_USER@$VM_HOST:$FROM_STATS_DIR/*.gfs $STATS_DIR/ ;;
    esac
 done
 
-echo ""
-echo "Downloaded directories:"
-echo "   $LOG_DIR"
-case $CLUSTER_TYPE in
-   geode|gemfire)
-      echo "   $STATS_DIR"
-   esac
-echo ""
-echo "Download complete."
+if [ "$REMOTE_SPECIFIED" == "false" ]; then
+   echo ""
+   echo "Downloaded directories:"
+   echo "   $LOG_DIR"
+   case $CLUSTER_TYPE in
+      geode|gemfire)
+         echo "   $STATS_DIR"
+      esac
+   echo ""
+   echo "Download complete."
+fi
diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/vm_exec b/padogrid-deployment/src/main/resources/common/bin_sh/vm_exec
--- a/padogrid-deployment/src/main/resources/common/bin_sh/vm_exec
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/vm_exec
@@ -171,12 +171,10 @@ for i in $*; do
    PREV_VAL=$i
 done
 
-# Replace , with space
-__VM_HOSTS=$(echo "$VM_HOSTS" | sed "s/,/ /g")
-DEFAULT_USER=$(whoami)
-VM_USER=`getClusterProperty "vm.user" "$DEFAULT_USER"`
+VM_USER=`getVmUser`
+
 KEY_FILE=`getClusterProperty "vm.privateKeyFile"`
-if [ "$KEY_FILE" == "" ]; then 
+if [ "$KEY_FILE" == "" ]; then
    # Set the first private key file found in the workspace directory if exists
    __VM_PRIVATE_KEY_FILE_FOUND="false"
    if [ "$VM_PRIVATE_KEY_FILE" == "" ]; then
@@ -194,18 +192,46 @@ if [ "$KEY_FILE" == "" ]; then
          done
       fi
    fi
+   # Replace '~' with the VM home path
+   KEY_FILE=$(echo $VM_PRIVATE_KEY_FILE | sed "s|\~|$HOME|")
+fi
+if [ "$KEY_FILE" == "" ]; then 
    KEY_FILE="$VM_PRIVATE_KEY_FILE"
 fi
-if [ ! -f "$KEY_FILE" ]; then
-   echo >&2 "ERROR: Private key does not exist [$KEY_FILE]."
-   echo >&2 "       Command aborted."
-   exit 1
-fi
-if [ "$KEY_FILE" == "" ]; then
-   VM_KEY=""
-else
+VM_KEY=""
+if [ "$KEY_FILE" != "" ]; then 
+   if [ ! -f "$KEY_FILE" ]; then
+      echo -e >&2 "${CError}ERROR:${CNone} Specified private key does not exist [$KEY_FILE]."
+      echo >&2 "       Command aborted."
+      exit 1
+   fi
    VM_KEY="-i $KEY_FILE"
 fi
+
+if [ "$(isVmPrivateHostReachable "$VM_USER" "$VM_KEY")" == "true" ]; then
+   # If private hosts are reachable then execute from here.
+   # Replace , with space
+   __VM_HOSTS=$(echo "$VM_HOSTS" | sed "s/,/ /g")
+else
+   # If private hosts are not reachable then copy to the first public host and then
+   # use that public host as a proxy to execute this command.
+   VM_PUBLIC_HOSTS=`getClusterProperty "vm.public.hosts"`
+   if [ "$VM_PUBLIC_HOSTS" == "" ]; then
+      echo -e "${CLightRed}ERROR:${CNone} Unable to connect to VM hosts. Please set 'vm.public.hosts' in 'etc/cluster.properties."
+      echo "       Command aborted."
+      exit 1
+   fi
+   #RWE_NAME=$(basename $PADOGRID_WORKSPACES_HOME)
+   #WORKSPACE=$(basename $PADOGRID_WORKSPACE)
+   RWE_NAME=$(basename $VM_PADOGRID_WORKSPACES_HOME)
+   WORKSPACE=$(basename $VM_PADOGRID_WORKSPACE)
+   VM_HOST=$(echo "$VM_PUBLIC_HOSTS" | sed "s/,.*//g")
+
+   # Execute on public vm
+   ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "switch_rwe $RWE_NAME/$WORKSPACE && $COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/$EXECUTABLE -cluster $CLUSTER -all $@"
+   exit
+fi
+
 THIS_VM_HOSTNAME=`hostname`
 if [ "$BG_SPECIFIED" == "true" ]; then
    SSH_OPTIONS="-f"
@@ -213,16 +239,16 @@ else
    SSH_OPTIONS=""
 fi
 for VM_HOST in $__VM_HOSTS; do
-     HOST_NAME=`ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "hostname"`
+     HOST_NAME=`ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "hostname"`
      if [ "$ALL" != "true" ] && [ "$HOST_NAME" == "$THIS_VM_HOSTNAME" ]; then
         continue
      fi
 
      echo "---------- $VM_HOST ----------"
      if [ "$SIMULATE" == "true" ]; then
-         echo "ssh -q -n $SSH_OPTIONS $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT $COMMAND"
+         echo "ssh -n $SSH_OPTIONS $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT $COMMAND"
      else
-        ssh -q -n $SSH_OPTIONS $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT $COMMAND
+        ssh -n $SSH_OPTIONS $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT $COMMAND
      fi
      echo ""
 done
diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/vm_show_products b/padogrid-deployment/src/main/resources/common/bin_sh/vm_show_products
--- a/padogrid-deployment/src/main/resources/common/bin_sh/vm_show_products
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/vm_show_products
@@ -121,56 +121,60 @@ fi
 
 WORKSPACE_NAME=$(basename "$PADOGRID_WORKSPACE")
 
-# Replace , with space
-__VM_HOSTS=$(echo "$VM_HOSTS" | sed "s/,/ /g")
-DEFAULT_USER=$(whoami)
-if [ "VM_USER" == "" ]; then
-   VM_USER=`getClusterProperty "vm.user" "$DEFAULT_USER"`
-fi
-
-if [ "$KEY" == "" ]; then
+VM_USER=`getVmUser`
+__VM_PRIVATE_KEY_FILE=`getClusterProperty "vm.privateKeyFile"`
+KEY_FILE=$__VM_PRIVATE_KEY_FILE
+if [ "$KEY_FILE" == "" ]; then
    # Set the first private key file found in the workspace directory if exists
-   __VM_PRIVATE_KEY_FILE_FOUND="false"
    if [ "$VM_PRIVATE_KEY_FILE" == "" ]; then
       if [ -f $PADOGRID_WORKSPACE/*.pem ]; then
          for i in $PADOGRID_WORKSPACE/*.pem; do
-            VM_PRIVATE_KEY_FILE=$i
-            __VM_PRIVATE_KEY_FILE_FOUND="true"
+            KEY_FILE=$i
             break
          done
       elif [ -f $PADOGRID_WORKSPACE/*.key ]; then
          for i in $PADOGRID_WORKSPACE/*.key; do
-            VM_PRIVATE_KEY_FILE=$i
-            __VM_PRIVATE_KEY_FILE_FOUND="true"
+            KEY_FILE=$i
             break
          done
       fi
    fi
-   KEY=`getClusterProperty "vm.privateKeyFile"`
 fi
-if [ "$KEY" == "" ]; then 
-   KEY="$VM_PRIVATE_KEY_FILE"
+if [ "$KEY_FILE" == "" ]; then 
+   KEY_FILE="$VM_PRIVATE_KEY_FILE"
 fi
+# Replace '~' with the VM home path
+KEY_FILE=$(echo $KEY_FILE | sed "s|\~|$HOME|")
 VM_KEY=""
-if [ "$KEY" != "" ]; then 
-   if [ ! -f "$KEY" ]; then
-      echo >&2 "ERROR: Specified private key does not exist [$KEY]."
+if [ "$KEY_FILE" != "" ]; then 
+   if [ ! -f "$KEY_FILE" ]; then
+      echo -e >&2 "${CError}ERROR:${CNone} Specified private key does not exist [$KEY_FILE]."
       echo >&2 "       Command aborted."
       exit 1
    fi
-   VM_KEY="-i $KEY"
+   VM_KEY="-i $KEY_FILE"
+fi
+
+VM_KEY=""
+if [ "$KEY_FILE" != "" ]; then 
+   if [ ! -f "$KEY_FILE" ]; then
+      echo -e >&2 "${CError}ERROR:${CNone} Specified private key does not exist [$KEY_FILE]."
+      echo >&2 "       Command aborted."
+      exit 1
+   fi
+   VM_KEY="-i $KEY_FILE"
 fi
 
 # Fail fast: Exit if any of the hosts is not reachable
-for VM_HOST in $__VM_HOSTS; do
-   REPLY=$(ssh -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT -o PasswordAuthentication=no "echo hello" 2>&1)
-   EXIT_CODE=$?
-   if [ "$EXIT_CODE" != "0" ]; then
-      echo -e "${CError}ERROR:${CNone} $VM_HOST - $REPLY"
-      echo "       Command aborted."
-      exit 1
-   fi
-done
+#for VM_HOST in $__VM_HOSTS; do
+#   REPLY=$(ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT -o PasswordAuthentication=no "echo hello" 2>&1)
+#   EXIT_CODE=$?
+#   if [ "$EXIT_CODE" != "0" ]; then
+#      echo -e "${CError}ERROR:${CNone} $VM_HOST - $REPLY"
+#      echo "       Command aborted."
+#      exit 1
+#   fi
+#done
 
 # Show each VM
 if [ "$RAW_SPECIFIED" != "true" ] && [ "$REMOTE_SPECIFIED" != "true" ]; then
@@ -179,34 +183,60 @@ if [ "$RAW_SPECIFIED" != "true" ] && [ "$REMOTE_SPECIFIED" != "true" ]; then
    else
       COMMAND="vm_show_products -remote"
    fi
-   for VM_HOST in $__VM_HOSTS; do
-      vm_products=$(ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$COMMAND")
-      total=0
-      for i in $vm_products; do
-         if [ "$i" == ";" ]; then
-           let total=total+1
-         fi
-      done
-      delimiter_count=0
-      echo "$VM_HOST"
-      for i in $vm_products; do
-         if [ "$i" == ";" ]; then
-            let delimiter_count=delimiter_count+1
-            if [ $delimiter_count -eq $total ]; then
-               echo -e "$TLel $line"
-            else
-               echo -e "$TTee $line"
+   if [ "$(isVmPrivateHostReachable "$VM_USER" "$VM_KEY")" == "true" ]; then
+      # If private hosts are reachable then execute from here.
+      # Replace , with space
+      __VM_HOSTS=$(echo "$VM_HOSTS" | sed "s/,/ /g")
+
+      for VM_HOST in $__VM_HOSTS; do
+         vm_products=$(ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$COMMAND")
+         total=0
+         for i in $vm_products; do
+            if [ "$i" == ";" ]; then
+              let total=total+1
             fi
-            line=""
-         else
-            if [[ "$i" == "_"* ]]; then
-               line="$line ${CGo}${i:1}${CNone}"
+         done
+         delimiter_count=0
+         echo "$VM_HOST"
+         for i in $vm_products; do
+            if [ "$i" == ";" ]; then
+               let delimiter_count=delimiter_count+1
+               if [ $delimiter_count -eq $total ]; then
+                  echo -e "$TLel $line"
+               else
+                  echo -e "$TTee $line"
+               fi
+               line=""
             else
-               line="$line $i"
+               if [[ "$i" == "_"* ]]; then
+                  line="$line ${CGo}${i:1}${CNone}"
+               else
+                  line="$line $i"
+               fi
             fi
-         fi
+         done
       done
-   done
+   else
+      VM_PUBLIC_HOSTS=`getClusterProperty "vm.public.hosts"`
+      if [ "$VM_PUBLIC_HOSTS" == "" ]; then
+         echo -e "${CLightRed}ERROR:${CNone} Unable to connect to VM hosts. Please set 'vm.public.hosts' in 'etc/cluster.properties."
+         echo "       Command aborted."
+         exit 1
+      fi
+
+      # If private hosts are not reachable then use a public host as a proxy to execute this command.
+      #RWE_NAME=$(basename $PADOGRID_WORKSPACES_HOME)
+      #WORKSPACE=$(basename $PADOGRID_WORKSPACE)
+      RWE_NAME=$(basename $VM_PADOGRID_WORKSPACES_HOME)
+      WORKSPACE=$(basename $VM_PADOGRID_WORKSPACE)
+
+      # Replace , with space
+      __VM_HOSTS=$(echo "$VM_PUBLIC_HOSTS" | sed "s/,/ /g")
+      for VM_HOST in $__VM_HOSTS; do
+         ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "switch_rwe $RWE_NAME/$WORKSPACE && $COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/$EXECUTABLE -cluster $CLUSTER $@"
+         break;
+      done
+   fi
    exit 0
 fi
 
@@ -247,6 +277,37 @@ function printProductVersions
    done
    echo "$LINE ;"
 }
+
+if [ "$(isVmPrivateHostReachable "$VM_USER" "$VM_KEY")" == "true" ]; then
+   # If private hosts are reachable then execute from here.
+   # Replace , with space
+   __VM_HOSTS=$(echo "$VM_HOSTS" | sed "s/,/ /g")
+else
+   # If private hosts are not reachable then sync the first public host and then
+   # use that public as a proxy to execute this command.
+
+   VM_PUBLIC_HOSTS=`getClusterProperty "vm.public.hosts"`
+   if [ "$VM_PUBLIC_HOSTS" == "" ]; then
+      echo -e >&2 "${CError}ERROR:${CNone} Unable to connect to VM hosts. Please set 'vm.public.hosts' in 'etc/cluster.properties."
+      echo "       Command aborted."
+      exit 1
+   fi
+
+   # Sync the first public host
+   VM_HOST=$(echo "$VM_PUBLIC_HOSTS" | sed "s/,.*//g")
+   __VM_HOSTS=$VM_HOST
+
+   # Use the public host a proxy to sync the rest of hosts
+   #RWE_NAME=$(basename $PADOGRID_WORKSPACES_HOME)
+   #WORKSPACE=$(basename $PADOGRID_WORKSPACE)
+   RWE_NAME=$(basename $VM_PADOGRID_WORKSPACES_HOME)
+   WORKSPACE=$(basename $VM_PADOGRID_WORKSPACE)
+   ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "switch_rwe $RWE_NAME/$WORKSPACE && $COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/$EXECUTABLE -cluster $CLUSTER $@"
+
+   # Clean tmp files and exit
+   cleanExit "$EXECUTABLE" "vm" "true"
+   exit
+fi
 
 determineInstalledProductVersions
 getCurrentProductVersions
diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/vm_test b/padogrid-deployment/src/main/resources/common/bin_sh/vm_test
--- a/padogrid-deployment/src/main/resources/common/bin_sh/vm_test
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/vm_test
@@ -149,55 +149,50 @@ fi
 
 WORKSPACE_NAME=$(basename "$PADOGRID_WORKSPACE")
 
-# Replace , with space
-__VM_HOSTS=$(echo "$VM_HOSTS" | sed "s/,/ /g")
-DEFAULT_USER=$(whoami)
-if [ "$VM_USER" == "" ]; then
-   VM_USER=$DEFAULT_USER
-fi
-
-KEY_FILE=`getClusterProperty "vm.privateKeyFile"`
-if [ "$KEY_FILE" == "" ]; then 
+VM_USER=`getVmUser`
+__VM_PRIVATE_KEY_FILE=`getClusterProperty "vm.privateKeyFile"`
+KEY_FILE=$__VM_PRIVATE_KEY_FILE
+if [ "$KEY_FILE" == "" ]; then
    # Set the first private key file found in the workspace directory if exists
-   __VM_PRIVATE_KEY_FILE_FOUND="false"
    if [ "$VM_PRIVATE_KEY_FILE" == "" ]; then
       if [ -f $PADOGRID_WORKSPACE/*.pem ]; then
          for i in $PADOGRID_WORKSPACE/*.pem; do
-            VM_PRIVATE_KEY_FILE=$i
-            __VM_PRIVATE_KEY_FILE_FOUND="true"
+            KEY_FILE=$i
             break
          done
       elif [ -f $PADOGRID_WORKSPACE/*.key ]; then
          for i in $PADOGRID_WORKSPACE/*.key; do
-            VM_PRIVATE_KEY_FILE=$i
-            __VM_PRIVATE_KEY_FILE_FOUND="true"
+            KEY_FILE=$i
             break
          done
       fi
    fi
+fi
+if [ "$KEY_FILE" == "" ]; then 
    KEY_FILE="$VM_PRIVATE_KEY_FILE"
 fi
-if [ ! -f "$KEY_FILE" ]; then
-   echo >&2 "ERROR: Private key does not exist [$KEY_FILE]."
-   echo >&2 "       Command aborted."
-   exit 1
-fi
-if [ "$KEY_FILE" == "" ]; then
-   VM_KEY=""
-else
+# Replace '~' with the VM home path
+KEY_FILE=$(echo $KEY_FILE | sed "s|\~|$HOME|")
+VM_KEY=""
+if [ "$KEY_FILE" != "" ]; then 
+   if [ ! -f "$KEY_FILE" ]; then
+      echo -e >&2 "${CError}ERROR:${CNone} Specified private key does not exist [$KEY_FILE]."
+      echo >&2 "       Command aborted."
+      exit 1
+   fi
    VM_KEY="-i $KEY_FILE"
 fi
 
 # Fail fast: Exit if any of the hosts is not reachable
-for VM_HOST in $__VM_HOSTS; do
-   REPLY=$(ssh -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT -o PasswordAuthentication=no "echo hello" 2>&1)
-   EXIT_CODE=$?
-   if [ "$EXIT_CODE" != "0" ]; then
-      echo -e "ERROR: $VM_HOST - ${CError}Failed${CNone} ($REPLY)"
-      echo "       Command aborted."
-      exit 1
-   fi
-done
+#for VM_HOST in $__VM_HOSTS; do
+#   REPLY=$(ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT -o PasswordAuthentication=no "echo hello" 2>&1)
+#   EXIT_CODE=$?
+#   if [ "$EXIT_CODE" != "0" ]; then
+#      echo -e "ERROR: $VM_HOST - ${CError}Failed${CNone} ($REPLY)"
+#      echo "       Command aborted."
+#      exit 1
+#   fi
+#done
 
 if [ "$VM_ENABLED" == "true" ]; then
    ISSUES_FOUND="false"
@@ -213,6 +208,7 @@ Workspace: $WORKSPACE
 Environment:
                   VM_ENABLED=$VM_ENABLED
                     VM_HOSTS=$VM_HOSTS
+             VM_PUBLIC_HOSTS=$VM_PUBLIC_HOSTS
                      VM_USER=$VM_USER
          VM_PRIVATE_KEY_FILE=$VM_PRIVATE_KEY_FILE
    VM_PADOGRID_ENV_BASE_PATH=$VM_PADOGRID_ENV_BASE_PATH
@@ -221,6 +217,29 @@ Environment:
        VM_PADOGRID_WORKSPACE=$VM_PADOGRID_WORKSPACE
 ------------------------------------------------------------------------------------------
 EOF
+
+IS_PUBLIC_HOST="false"
+if [ "$(isVmPrivateHostReachable "$VM_USER" "$VM_KEY")" == "true" ]; then
+   # If private hosts are reachable then execute from here.
+   # Replace , with space
+   __VM_HOSTS=$(echo "$VM_HOSTS" | sed "s/,/ /g")
+else
+   # If private hosts are not reachable then test the first public host and then
+   # use that public as a proxy to execute this command.
+
+   VM_PUBLIC_HOSTS=`getClusterProperty "vm.public.hosts"`
+   if [ "$VM_PUBLIC_HOSTS" == "" ]; then
+      echo -e >&2 "${CError}ERROR:${CNone} Unable to connect to VM hosts. Please set 'vm.public.hosts' in 'etc/cluster.properties."
+      echo "       Command aborted."
+      exit 1
+   fi
+
+   # Use the first public host
+   VM_HOST=$(echo "$VM_PUBLIC_HOSTS" | sed "s/,.*//g")
+   __VM_HOSTS=$VM_HOST
+
+   IS_PUBLIC_HOST="true"
+fi
 
 # Check ssh sessions
 NETWORK_ISSUES_VM_HOSTS=""
@@ -243,7 +262,7 @@ SOFTWARE_ISSUES_FOUND="false"
 COMMAND="vm_show_products -raw -active"
 echo "Determining active products... Please wait."
 for VM_HOST in $__VM_HOSTS; do
-   vm_products=$(ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$COMMAND")
+   vm_products=$(ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$COMMAND")
    if [ "$vm_products" == "" ]; then
       PADOGRID_HOME_NOT_FOUND_LIST="$PADOGRID_HOME_NOT_FOUND_LIST $VM_HOST"
       JAVA_HOME_NOT_FOUND_LIST="$JAVA_HOME_NOT_FOUND_LIST $VM_HOST"
@@ -302,8 +321,7 @@ done
 # Display cluster info
 __VM_ENABLED=`getClusterProperty "vm.enabled" "false"`
 __VM_HOSTS_CLUSTER=`getClusterProperty "vm.hosts"`
-__VM_USER=`getClusterProperty "vm.user" "$DEFAULT_USER"`
-__VM_PRIVATE_KEY_FILE=`getClusterProperty "vm.privateKeyFile"`
+
 cat <<EOF
 ------------------------------------------------------------------------------------------
 Cluster: $CLUSTER
@@ -356,19 +374,26 @@ fi
 
 # Check if the cluster has been deployed
 CLUSTER_NOT_FOUND_LIST=""
-# Replace , with space
-__VM_HOSTS=$(echo "$__VM_HOSTS_CLUSTER" | sed "s/,/ /g")
 if [ "$NETWORK_ISSUES_VM_HOSTS" == "" ]; then
    CLUSTER_COMMAND="if [ -d "$VM_PADOGRID_WORKSPACE/clusters/$CLUSTER" ]; then echo true; else echo false; fi"
    for VM_HOST in $__VM_HOSTS; do
-      CLUSTER_EXISTS=$(ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$CLUSTER_COMMAND")
+      CLUSTER_EXISTS=$(ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$CLUSTER_COMMAND")
       if [[ "$CLUSTER_EXISTS" == *"false" ]]; then
-	 CLUSTER_NOT_FOUND_LIST="$CLUSTER_NOT_FOUND_LIST $VM_HOST"
-	 CLUSTER_ISSUES_FOUND=true
+          CLUSTER_NOT_FOUND_LIST="$CLUSTER_NOT_FOUND_LIST $VM_HOST"
+          CLUSTER_ISSUES_FOUND=true
       fi
    done
 fi
 echo "------------------------------------------------------------------------------------------"
+
+if [ "$IS_PUBLIC_HOST" == "true" ]; then
+   # Use the public host a proxy to sync the rest of hosts
+   #RWE_NAME=$(basename $PADOGRID_WORKSPACES_HOME)
+   #WORKSPACE=$(basename $PADOGRID_WORKSPACE)
+   RWE_NAME=$(basename $VM_PADOGRID_WORKSPACES_HOME)
+   WORKSPACE=$(basename $VM_PADOGRID_WORKSPACE)
+   ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "switch_rwe $RWE_NAME/$WORKSPACE && $COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/$EXECUTABLE -cluster $CLUSTER $@"
+fi
 
 # Summary
 echo "------------------------------------------------------------------------------------------"
diff --git a/padogrid-deployment/src/main/resources/geode/bin_sh/remove_locator b/padogrid-deployment/src/main/resources/geode/bin_sh/remove_locator
--- a/padogrid-deployment/src/main/resources/geode/bin_sh/remove_locator
+++ b/padogrid-deployment/src/main/resources/geode/bin_sh/remove_locator
@@ -98,14 +98,14 @@ POD=`getClusterProperty "pod.name" "local"`
 if [ "$REMOTE_SPECIFIED" == "false" ]; then
    VM_ENABLED=`getClusterProperty "vm.enabled" "false"`
    if [ "$VM_ENABLED" == "true" ]; then
-      VM_HOSTS=`getClusterProperty "vm.hosts"`
-      if [ "$VM_HOSTS" == "" ]; then
-         echo "----------------------------------------------------------------"
-         echo "WORKSPACE $PADOGRID_WORKSPACE"
-         echo "    ERROR: VM hosts undefined. Set 'vm.hosts' in the following cluster.properties file."  
-         echo "           $ETC_DIR/cluster.properties"
-         echo "           Command aborted."
-         echo "----------------------------------------------------------------"
+      VM_LOCATOR_HOSTS=$(getClusterProperty "vm.locator.hosts")
+      if [ "$STANDALONE" != "true" ] && [ "$VM_LOCATOR_HOSTS" == "" ]; then
+         echo >&2 "----------------------------------------------------------------"
+         echo >&2 "WORKSPACE: $PADOGRID_WORKSPACE"
+         echo >&2 "    ERROR: VM locator hosts undefined. Set 'vm.locator.hosts' in the following cluster.properties file."  
+         echo >&2 "           $ETC_DIR/cluster.properties"
+         echo >&2 "           Command aborted."
+         echo >&2 "----------------------------------------------------------------"
          exit 1
       fi
 
@@ -117,36 +117,55 @@ if [ "$REMOTE_SPECIFIED" == "false" ]; then
          fi
       fi
 
-      # Replace , with space
-      __VM_HOSTS=$(echo "$VM_HOSTS" | sed "s/,/ /g")
       DEFAULT_USER=$(whoami)
       VM_USER=`getClusterProperty "vm.user" "$DEFAULT_USER"`
       VM_KEY=`getClusterProperty "vm.privateKeyFile"`
       if [ "$VM_KEY" != "" ]; then 
          VM_KEY="-i $VM_KEY"
       fi
-      if [ "$ALL" == "true" ]; then
-         for VM_HOST in $__VM_HOSTS; do
-            ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$COMMAND_PREFIX $SCRIPT_DIR/remove_locator -cluster $CLUSTER -remote $VM_HOST -workspace $PADOGRID_WORKSPACE"
-         done
-      else
-         # Determine the host
-         __LOCATOR_NUMBER=0
-         __FOUND="false"
-         
-         for VM_HOST in $__VM_HOSTS; do
-            let __LOCATOR_NUMBER=__LOCATOR_NUMBER+1
-            if [ $__LOCATOR_NUMBER -eq $LOCATOR_NUM_NO_LEADING_ZERO ]; then
-               __FOUND="true"
-               ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$COMMAND_PREFIX $SCRIPT_DIR/remove_locator -cluster $CLUSTER -remote $VM_HOST -workspace $PADOGRID_WORKSPACE"
-               break;
+
+      if [ "$(isVmPrivateHostReachable "$VM_USER" "$VM_KEY")" == "true" ]; then
+         # If private hosts are reachable then execute from here.
+
+         # Replace , with space
+         __VM_HOSTS=$(echo "$VM_LOCATOR_HOSTS" | sed "s/,/ /g")
+         if [ "$ALL" == "true" ]; then
+            for VM_HOST in $__VM_HOSTS; do
+               ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$COMMAND_PREFIX $SCRIPT_DIR/remove_locator -cluster $CLUSTER -remote $VM_HOST -workspace $PADOGRID_WORKSPACE"
+            done
+         else
+            # Determine the host
+            __LOCATOR_NUMBER=0
+            __FOUND="false"
+            
+            for VM_HOST in $__VM_HOSTS; do
+               let __LOCATOR_NUMBER=__LOCATOR_NUMBER+1
+               if [ $__LOCATOR_NUMBER -eq $LOCATOR_NUM_NO_LEADING_ZERO ]; then
+                  __FOUND="true"
+                  ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$COMMAND_PREFIX $SCRIPT_DIR/remove_locator -cluster $CLUSTER -remote $VM_HOST -workspace $PADOGRID_WORKSPACE"
+                  break;
+               fi
+            done
+            FIRST_NUMBER=1
+            LAST_NUMBER=$__LOCATOR_NUMBER
+            if [ "$__FOUND" == "false" ]; then
+               echo "ERROR: Invalid locator number. Valid range is [$FIRST_NUMBER, $LAST_NUMBER]. Command aborted." 
             fi
-         done
-         FIRST_NUMBER=1
-         LAST_NUMBER=$__LOCATOR_NUMBER
-         if [ "$__FOUND" == "false" ]; then
-            echo "ERROR: Invalid locator number. Valid range is [$FIRST_NUMBER, $LAST_NUMBER]. Command aborted." 
          fi
+      else
+         # If private hosts are not reachable then use a public host as a proxy to execute this command.
+         #RWE_NAME=$(basename $PADOGRID_WORKSPACES_HOME)
+         #WORKSPACE=$(basename $PADOGRID_WORKSPACE)
+         RWE_NAME=$(basename $VM_PADOGRID_WORKSPACES_HOME)
+         WORKSPACE=$(basename $VM_PADOGRID_WORKSPACE)
+
+         VM_PUBLIC_HOSTS=`getClusterProperty "vm.public.hosts"`
+         # Replace , with space
+         __VM_HOSTS=$(echo "$VM_PUBLIC_HOSTS" | sed "s/,/ /g")
+         for VM_HOST in $__VM_HOSTS; do
+            ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "switch_rwe $RWE_NAME/$WORKSPACE && $COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/$EXECUTABLE -cluster $CLUSTER $@"
+            break;
+         done
       fi
       exit
    fi
diff --git a/padogrid-deployment/src/main/resources/hazelcast/bin_sh/clean_cluster b/padogrid-deployment/src/main/resources/hazelcast/bin_sh/clean_cluster
--- a/padogrid-deployment/src/main/resources/hazelcast/bin_sh/clean_cluster
+++ b/padogrid-deployment/src/main/resources/hazelcast/bin_sh/clean_cluster
@@ -89,6 +89,14 @@ POD=`getClusterProperty "pod.name" "local"`
 #
 VM_ENABLED=`getClusterProperty "vm.enabled" "false"`
 if [ "$VM_ENABLED" == "true" ] && [ "$POD" == "local" ] && [ "$REMOTE_SPECIFIED" == "false" ]; then
+   VM_HOSTS=`getClusterProperty "vm.hosts"`
+   if [ "$VM_HOSTS" == "" ]; then
+      echo "ERROR: VM hosts undefined. Set 'vm.hosts' in the following cluster.properties file."  
+      echo "       $ETC_DIR/cluster.properties"
+      echo "       Command aborted."
+      exit 1
+   fi
+
    DEFAULT_USER=$(whoami)
    VM_USER=`getClusterProperty "vm.user" "$DEFAULT_USER"`
    VM_KEY=`getClusterProperty "vm.privateKeyFile"`
@@ -98,13 +106,30 @@ if [ "$VM_ENABLED" == "true" ] && [ "$POD" == "local" ] && [ "$REMOTE_SPECIFIED"
    if [ "$VM_KEY" != "" ]; then 
       VM_KEY="-i $VM_KEY"
    fi
-   VM_HOSTS=`getClusterProperty "vm.hosts"`
-   # Replace , with space
-   __VM_HOSTS=$(echo "$VM_HOSTS" | sed "s/,/ /g")
-   __MEMBER_NUMBER=0
-   for VM_HOST in $__VM_HOSTS; do
-      ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/clean_cluster -cluster $CLUSTER -remote $VM_HOST -workspace $VM_PADOGRID_WORKSPACE $@"
-   done
+
+   if [ "$(isVmPrivateHostReachable "$VM_USER" "$VM_KEY")" == "true" ]; then
+      # If private hosts are reachable then execute from here.
+      # Replace , with space
+      __VM_HOSTS=$(echo "$VM_HOSTS" | sed "s/,/ /g")
+      __MEMBER_NUMBER=0
+      for VM_HOST in $__VM_HOSTS; do
+         ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/$EXECUTABLE -cluster $CLUSTER -remote $VM_HOST -workspace $VM_PADOGRID_WORKSPACE $@"
+      done
+   else
+      # If private hosts are not reachable then use a public host as a proxy to execute this command.
+      #RWE_NAME=$(basename $PADOGRID_WORKSPACES_HOME)
+      #WORKSPACE=$(basename $PADOGRID_WORKSPACE)
+      RWE_NAME=$(basename $VM_PADOGRID_WORKSPACES_HOME)
+      WORKSPACE=$(basename $VM_PADOGRID_WORKSPACE)
+
+      VM_PUBLIC_HOSTS=`getClusterProperty "vm.public.hosts"`
+      # Replace , with space
+      __VM_HOSTS=$(echo "$VM_PUBLIC_HOSTS" | sed "s/,/ /g")
+      for VM_HOST in $__VM_HOSTS; do
+         ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "switch_rwe $RWE_NAME/$WORKSPACE && $COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/$EXECUTABLE -cluster $CLUSTER $@"
+         break;
+      done
+   fi
    exit
 fi
 
diff --git a/padogrid-deployment/src/main/resources/hazelcast/bin_sh/show_log b/padogrid-deployment/src/main/resources/hazelcast/bin_sh/show_log
--- a/padogrid-deployment/src/main/resources/hazelcast/bin_sh/show_log
+++ b/padogrid-deployment/src/main/resources/hazelcast/bin_sh/show_log
@@ -114,17 +114,18 @@ POD=`getClusterProperty "pod.name" "local"`
 #
 VM_ENABLED=`getClusterProperty "vm.enabled" "false"`
 if [ "$VM_ENABLED" == "true" ] && [ "$REMOTE_SPECIFIED" == "false" ]; then
-   DEFAULT_USER=$(whoami)
-   VM_USER=`getClusterProperty "vm.user" "$DEFAULT_USER"`
-   VM_KEY=`getClusterProperty "vm.privateKeyFile"`
-   if [ "$VM_KEY" != "" ]; then 
-      VM_KEY="-i $VM_KEY"
-   elif [ "$VM_PRIVATE_KEY_FILE" != "" ]; then
-      VM_KEY="-i $VM_PRIVATE_KEY_FILE"
-   fi
-
+   # Determine VM_HOST
    if [ "$LOG" == "mc" ]; then
       VM_HOST=`getClusterProperty "mc.host" $DEFAULT_MC_HOST`
+      if [ "$VM_HOST" == "" ]; then
+         echo "----------------------------------------------------------------"
+         echo "WORKSPACE: $PADOGRID_WORKSPACE"
+         echo "    ERROR: VM Management Center host undefined. Set 'mc.hosts' in the following cluster.properties file."  
+         echo "           $ETC_DIR/cluster.properties"
+         echo "           Command aborted."
+         echo "----------------------------------------------------------------"
+         exit 1
+      fi
    else
       VM_HOSTS=`getClusterProperty "vm.hosts"`
       if [ "$VM_HOSTS" == "" ]; then
@@ -136,32 +137,40 @@ if [ "$VM_ENABLED" == "true" ] && [ "$REMOTE_SPECIFIED" == "false" ]; then
          echo "----------------------------------------------------------------"
          exit 1
       fi
+      # Replace , with space
+      __VM_HOSTS=$(echo "$VM_HOSTS" | sed "s/,/ /g")
+      __MEMBER_NUMBER=0
+      VM_HOST=""
+      for __VM_HOST in $__VM_HOSTS; do
+         let __MEMBER_NUMBER=__MEMBER_NUMBER+1
+         if [ $__MEMBER_NUMBER -eq $MEMBER_NUM ]; then
+            VM_HOST=$__VM_HOST
+            break;
+         fi
+      done
+      if [ "$VM_HOST" == "" ]; then
+         echo "----------------------------------------------------------------"
+         echo "WORKSPACE: $PADOGRID_WORKSPACE"
+         echo "ERROR: Invalid member number [$MEMBER_NUM]. Command aborted."
+         echo "----------------------------------------------------------------"
+         exit 1
+      fi
+   fi
+
+   DEFAULT_USER=$(whoami)
+   VM_USER=`getClusterProperty "vm.user" "$DEFAULT_USER"`
+   VM_KEY=`getClusterProperty "vm.privateKeyFile"`
+   if [ "$VM_KEY" != "" ]; then 
+      VM_KEY="-i $VM_KEY"
+   elif [ "$VM_PRIVATE_KEY_FILE" != "" ]; then
+      VM_KEY="-i $VM_PRIVATE_KEY_FILE"
+   fi
 
    # If pod cluster, then source in the pod env vars to set the VM specific variables
    OS_ENV=`getOsEnv`
    if [ "$OS_ENV" == "gh" ] && [ "$POD" != "local" ]; then
       if [ -f "$PODS_DIR/$POD/.nodeenv.sh" ]; then
          . "$PODS_DIR/$POD/.nodeenv.sh"
-      fi
-   fi
-
-      # Replace , with space
-      __VM_HOSTS=$(echo "$VM_HOSTS" | sed "s/,/ /g")
-      __MEMBER_NUMBER=0
-      __VM_HOST=""
-      for VM_HOST in $__VM_HOSTS; do
-         let __MEMBER_NUMBER=__MEMBER_NUMBER+1
-         if [ $__MEMBER_NUMBER -eq $MEMBER_NUM ]; then
-            __VM_HOST=$VM_HOST
-            break;
-         fi
-      done
-      if [ "$__VM_HOST" == "" ]; then
-         echo "----------------------------------------------------------------"
-         echo "WORKSPACE: $PADOGRID_WORKSPACE"
-         echo "ERROR: Invalid member number [$MEMBER_NUM]. Command aborted."
-         echo "----------------------------------------------------------------"
-         exit 1
       fi
    fi
 
@@ -176,8 +185,25 @@ if [ "$VM_ENABLED" == "true" ] && [ "$REMOTE_SPECIFIED" == "false" ]; then
    # For Vagrant VMs, run local if '.local' is suffix
    THIS_HOST_NAME=`hostname`
    if [ "$VM_HOST" != "${THIS_HOST_NAME}.local" ] ;  then
-      ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/show_log -cluster $CLUSTER -remote $VM_HOST -workspace $VM_PADOGRID_WORKSPACE $@ $COMMAND_TAIL"
-   exit
+      if [ "$(isVmPrivateHostReachable "$VM_USER" "$VM_KEY")" == "true" ]; then
+         # If private hosts are reachable then execute from here.
+         ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/show_log -cluster $CLUSTER -remote $VM_HOST -workspace $VM_PADOGRID_WORKSPACE $@ $COMMAND_TAIL"
+      else
+         # If private hosts are not reachable then use a public host as a proxy to execute this command.
+         #RWE_NAME=$(basename $PADOGRID_WORKSPACES_HOME)
+         #WORKSPACE=$(basename $PADOGRID_WORKSPACE)
+         RWE_NAME=$(basename $VM_PADOGRID_WORKSPACES_HOME)
+         WORKSPACE=$(basename $VM_PADOGRID_WORKSPACE)
+
+         VM_PUBLIC_HOSTS=`getClusterProperty "vm.public.hosts"`
+         # Replace , with space
+         __VM_HOSTS=$(echo "$VM_PUBLIC_HOSTS" | sed "s/,/ /g")
+         for VM_HOST in $__VM_HOSTS; do
+            ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "switch_rwe $RWE_NAME/$WORKSPACE && $COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/$EXECUTABLE -cluster $CLUSTER $@"
+            break;
+         done
+      fi
+      exit
    fi
 fi
 
diff --git a/padogrid-deployment/src/main/resources/hazelcast/bin_sh/stop_mc b/padogrid-deployment/src/main/resources/hazelcast/bin_sh/stop_mc
--- a/padogrid-deployment/src/main/resources/hazelcast/bin_sh/stop_mc
+++ b/padogrid-deployment/src/main/resources/hazelcast/bin_sh/stop_mc
@@ -69,10 +69,19 @@ fi
 # VM cluster
 #
 THIS_HOST_NAME=`hostname`
-MC_HOST=`getClusterProperty "mc.host" $DEFAULT_MC_HOST`
 if [ "$REMOTE_SPECIFIED" == "false" ]; then
    VM_ENABLED=`getClusterProperty "vm.enabled" "false"`
    if [ "$VM_ENABLED" == "true" ] && [ "$THIS_HOST_NAME" != "$DEFAULT_MC_HOST" ]; then
+      VM_HOST=`getClusterProperty "mc.host" $DEFAULT_MC_HOST`
+      if [ "$VM_HOST" == "" ]; then
+         echo "----------------------------------------------------------------"
+         echo "WORKSPACE: $PADOGRID_WORKSPACE"
+         echo "    ERROR: VM Management Center host undefined. Set 'mc.hosts' in the following cluster.properties file."  
+         echo "           $ETC_DIR/cluster.properties"
+         echo "           Command aborted."
+         echo "----------------------------------------------------------------"
+         exit 1
+      fi
 
       # If pod cluster, then source in the pod env vars to set the VM specific variables
       OS_ENV=`getOsEnv`
@@ -92,8 +101,25 @@ if [ "$REMOTE_SPECIFIED" == "false" ]; then
          VM_KEY="-i $VM_KEY"
       fi
       # For Vagrant VMs, run local if '.local' is suffix
-      if [ "$MC_HOST" != "${THIS_HOST_NAME}.local" ] ;  then
-         ssh -q -n $VM_KEY $VM_USER@$MC_HOST -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/stop_mc -remote $MC_HOST -workspace $VM_PADOGRID_WORKSPACE -cluster $CLUSTER $@"
+      if [ "$VM_HOST" != "${THIS_HOST_NAME}.local" ] ;  then
+         if [ "$(isVmPrivateHostReachable "$VM_USER" "$VM_KEY")" == "true" ]; then
+            # If private hosts are reachable then execute from here.
+            ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/stop_mc -remote $VM_HOST -workspace $VM_PADOGRID_WORKSPACE -cluster $CLUSTER $@"
+         else
+            # If private hosts are not reachable then use a public host as a proxy to execute this command.
+            #RWE_NAME=$(basename $PADOGRID_WORKSPACES_HOME)
+            #WORKSPACE=$(basename $PADOGRID_WORKSPACE)
+            RWE_NAME=$(basename $VM_PADOGRID_WORKSPACES_HOME)
+            WORKSPACE=$(basename $VM_PADOGRID_WORKSPACE)
+
+            VM_PUBLIC_HOSTS=`getClusterProperty "vm.public.hosts"`
+            # Replace , with space
+            __VM_HOSTS=$(echo "$VM_PUBLIC_HOSTS" | sed "s/,/ /g")
+            for VM_HOST in $__VM_HOSTS; do
+               ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "switch_rwe $RWE_NAME/$WORKSPACE && $COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/$EXECUTABLE -cluster $CLUSTER $@"
+               break;
+            done
+         fi
          exit
       fi
    fi
