Fixed a vm key issue

diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/vm_deploy_padogrid b/padogrid-deployment/src/main/resources/common/bin_sh/vm_deploy_padogrid
--- a/padogrid-deployment/src/main/resources/common/bin_sh/vm_deploy_padogrid
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/vm_deploy_padogrid
@@ -167,10 +167,18 @@ echo "----------------------------------------------------------------"
 __VM_HOSTS=$(echo "$VM_HOSTS" | sed "s/,/ /g")
 DEFAULT_USER=$(whoami)
 VM_USER=`getClusterProperty "vm.user" "$DEFAULT_USER"`
-VM_KEY=`getClusterProperty "vm.privateKeyFile"`
-if [ "$VM_KEY" != "" ]; then 
-   VM_KEY="-i $VM_KEY"
+KEY_FILE=`getClusterProperty "vm.privateKeyFile"`
+if [ "$KEY_FILE" != "" ]; then 
+   VM_KEY="$KEY_FILE"
+elif [ "$VM_PRIVATE_KEY_FILE" != "" ]; then
+   KEY_FILE="$VM_PRIVATE_KEY_FILE"
 fi
+if [ ! -f "$KEY_FILE" ]; then
+   echo >&2 "ERROR: Specified private key does not exist [$KEY_FILE]."
+   echo >&2 "       Command aborted."
+   exit 1
+fi
+VM_KEY="-i $KEY_FILE"
 
 # Fail fast: Exit if any of the hosts is not reachable
 for VM_HOST in $__VM_HOSTS; do
diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/vm_exec b/padogrid-deployment/src/main/resources/common/bin_sh/vm_exec
--- a/padogrid-deployment/src/main/resources/common/bin_sh/vm_exec
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/vm_exec
@@ -168,16 +168,20 @@ done
 
 # Replace , with space
 __VM_HOSTS=$(echo "$VM_HOSTS" | sed "s/,/ /g")
-if [ "$CLUSTER_SPECIFIED" == "true" ]; then
-   VM_USER=`getClusterProperty "vm.user"`
-   VM_KEY=`getClusterProperty "vm.privateKeyFile"`
+DEFAULT_USER=$(whoami)
+VM_USER=`getClusterProperty "vm.user" "$DEFAULT_USER"`
+KEY_FILE=`getClusterProperty "vm.privateKeyFile"`
+if [ "$KEY_FILE" != "" ]; then 
+   VM_KEY="$KEY_FILE"
+elif [ "$VM_PRIVATE_KEY_FILE" != "" ]; then
+   KEY_FILE="$VM_PRIVATE_KEY_FILE"
 fi
-if [ "$VM_USER" == "" ]; then
-   VM_USER=$(whoami)
+if [ ! -f "$KEY_FILE" ]; then
+   echo >&2 "ERROR: Specified private key does not exist [$KEY_FILE]."
+   echo >&2 "       Command aborted."
+   exit 1
 fi
-if [ "$VM_KEY" != "" ]; then 
-   VM_KEY="-i $VM_KEY"
-fi
+VM_KEY="-i $KEY_FILE"
 THIS_VM_HOSTNAME=`hostname`
 for VM_HOST in $__VM_HOSTS; do
      HOST_NAME=`ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "hostname"`
diff --git a/padogrid-deployment/src/main/resources/hazelcast/bin_sh/vm_test b/padogrid-deployment/src/main/resources/hazelcast/bin_sh/vm_test
--- a/padogrid-deployment/src/main/resources/hazelcast/bin_sh/vm_test
+++ b/padogrid-deployment/src/main/resources/hazelcast/bin_sh/vm_test
@@ -164,18 +164,18 @@ if [ "$VM_PRIVATE_KEY_FILE" == "" ]; then
       done
    fi
 fi
-if [ "$KEY" == "" ]; then
-   KEY=$VM_PRIVATE_KEY_FILE
+KEY_FILE=`getClusterProperty "vm.privateKeyFile"`
+if [ "$KEY_FILE" != "" ]; then 
+   VM_KEY="$KEY_FILE"
+elif [ "$VM_PRIVATE_KEY_FILE" != "" ]; then
+   KEY_FILE="$VM_PRIVATE_KEY_FILE"
 fi
-VM_KEY=""
-if [ "$KEY" != "" ]; then 
-   if [ ! -f "$KEY" ]; then
-      echo >&2 "ERROR: Specified private key does not exist [$KEY]."
-      echo >&2 "       Command aborted."
-      exit 1
-   fi
-   VM_KEY="-i $KEY"
+if [ ! -f "$KEY_FILE" ]; then
+   echo >&2 "ERROR: Specified private key does not exist [$KEY_FILE]."
+   echo >&2 "       Command aborted."
+   exit 1
 fi
+VM_KEY="-i $KEY_FILE"
 
 # Fail fast: Exit if any of the hosts is not reachable
 for VM_HOST in $__VM_HOSTS; do
