Fixed multi command issues in vm_exec

diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/vm_deploy_bundle b/padogrid-deployment/src/main/resources/common/bin_sh/vm_deploy_bundle
--- a/padogrid-deployment/src/main/resources/common/bin_sh/vm_deploy_bundle
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/vm_deploy_bundle
@@ -249,7 +249,7 @@ else
    VM_PUBLIC_HOSTS=`getClusterProperty "vm.public.hosts"`
    if [ "$VM_PUBLIC_HOSTS" == "" ]; then
       echo -e >&2 "${CError}ERROR:${CNone} Unable to connect to VM hosts. Please set 'vm.public.hosts' in 'etc/cluster.properties."
-      echo "       Command aborted."
+      echo >&2 "       Command aborted."
       exit 1
    fi
 
@@ -333,7 +333,7 @@ if [ "$EXISTING_HOSTS" != "" ]; then
 fi
 
 if [ "$IS_PUBLIC_HOST" == "true" ]; then
-   # Use the public host a proxy to sync the rest of hosts
+   # Use the public host as a proxy to sync the rest of hosts
    #RWE_NAME=$(basename $PADOGRID_WORKSPACES_HOME)
    #WORKSPACE=$(basename $PADOGRID_WORKSPACE)
    RWE_NAME=$(basename $VM_PADOGRID_WORKSPACES_HOME)
diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/vm_download b/padogrid-deployment/src/main/resources/common/bin_sh/vm_download
--- a/padogrid-deployment/src/main/resources/common/bin_sh/vm_download
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/vm_download
@@ -177,7 +177,7 @@ else
    VM_PUBLIC_HOSTS=`getClusterProperty "vm.public.hosts"`
    if [ "$VM_PUBLIC_HOSTS" == "" ]; then
       echo -e >&2 "${CError}ERROR:${CNone} Unable to connect to VM hosts. Please set 'vm.public.hosts' in 'etc/cluster.properties."
-      echo "       Command aborted."
+      echo >&2 "       Command aborted."
       exit 1
    fi
 
diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/vm_exec b/padogrid-deployment/src/main/resources/common/bin_sh/vm_exec
--- a/padogrid-deployment/src/main/resources/common/bin_sh/vm_exec
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/vm_exec
@@ -156,8 +156,9 @@ fi
 #
 # Reconstruct command
 #
-COMMAND=
-PREV_VAL=
+COMMAND_OPTS=""
+COMMAND=""
+PREV_VAL=""
 for i in $*; do
    if [[ "$i" == "${CLUSTER}" ]]; then
        if [ -z $CLUSTER_SPECIFIED ]; then
@@ -167,6 +168,8 @@ for i in $*; do
       if [ "$PREV_VAL" != "-vm" ]; then
          COMMAND="$COMMAND $i"
       fi
+   else
+      COMMAND_OPTS="$COMMAND_OPTS $i"
    fi
    PREV_VAL=$i
 done
@@ -217,8 +220,8 @@ else
    # use that public host as a proxy to execute this command.
    VM_PUBLIC_HOSTS=`getClusterProperty "vm.public.hosts"`
    if [ "$VM_PUBLIC_HOSTS" == "" ]; then
-      echo -e "${CLightRed}ERROR:${CNone} Unable to connect to VM hosts. Please set 'vm.public.hosts' in 'etc/cluster.properties."
-      echo "       Command aborted."
+      echo -e >&2 "${CLightRed}ERROR:${CNone} Unable to connect to VM hosts. Please set 'vm.public.hosts' in 'etc/cluster.properties."
+      echo >&2 "       Command aborted."
       exit 1
    fi
    #RWE_NAME=$(basename $PADOGRID_WORKSPACES_HOME)
@@ -228,7 +231,12 @@ else
    VM_HOST=$(echo "$VM_PUBLIC_HOSTS" | sed "s/,.*//g")
 
    # Execute on public vm
-   ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "switch_rwe $RWE_NAME/$WORKSPACE && $COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/$EXECUTABLE -cluster $CLUSTER -all $@"
+  if [ "$SIMULATE" == "true" ]; then
+      echo ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "switch_rwe $RWE_NAME/$WORKSPACE && $COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/$EXECUTABLE -cluster $CLUSTER -all $COMMAND_OPTS \"$COMMAND\""
+      ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "switch_rwe $RWE_NAME/$WORKSPACE && $COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/$EXECUTABLE -cluster $CLUSTER -all $COMMAND_OPTS \"$COMMAND\""
+  else
+      ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "switch_rwe $RWE_NAME/$WORKSPACE && $COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/$EXECUTABLE -cluster $CLUSTER -all $COMMAND_OPTS \"$COMMAND\""
+  fi
    exit
 fi
 
@@ -246,9 +254,9 @@ for VM_HOST in $__VM_HOSTS; do
 
      echo "---------- $VM_HOST ----------"
      if [ "$SIMULATE" == "true" ]; then
-         echo "ssh -n $SSH_OPTIONS $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT $COMMAND"
+        echo ssh -n $SSH_OPTIONS $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$COMMAND"
      else
-        ssh -n $SSH_OPTIONS $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT $COMMAND
+        ssh -n $SSH_OPTIONS $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$COMMAND"
      fi
      echo ""
 done
diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/vm_show_products b/padogrid-deployment/src/main/resources/common/bin_sh/vm_show_products
--- a/padogrid-deployment/src/main/resources/common/bin_sh/vm_show_products
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/vm_show_products
@@ -219,8 +219,8 @@ if [ "$RAW_SPECIFIED" != "true" ] && [ "$REMOTE_SPECIFIED" != "true" ]; then
    else
       VM_PUBLIC_HOSTS=`getClusterProperty "vm.public.hosts"`
       if [ "$VM_PUBLIC_HOSTS" == "" ]; then
-         echo -e "${CLightRed}ERROR:${CNone} Unable to connect to VM hosts. Please set 'vm.public.hosts' in 'etc/cluster.properties."
-         echo "       Command aborted."
+         echo -e >&2 "${CLightRed}ERROR:${CNone} Unable to connect to VM hosts. Please set 'vm.public.hosts' in 'etc/cluster.properties."
+         echo >&2 "       Command aborted."
          exit 1
       fi
 
@@ -297,7 +297,7 @@ else
    VM_HOST=$(echo "$VM_PUBLIC_HOSTS" | sed "s/,.*//g")
    __VM_HOSTS=$VM_HOST
 
-   # Use the public host a proxy to sync the rest of hosts
+   # Use the public host as a proxy to sync the rest of hosts
    #RWE_NAME=$(basename $PADOGRID_WORKSPACES_HOME)
    #WORKSPACE=$(basename $PADOGRID_WORKSPACE)
    RWE_NAME=$(basename $VM_PADOGRID_WORKSPACES_HOME)
diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/vm_test b/padogrid-deployment/src/main/resources/common/bin_sh/vm_test
--- a/padogrid-deployment/src/main/resources/common/bin_sh/vm_test
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/vm_test
@@ -226,11 +226,10 @@ if [ "$(isVmPrivateHostReachable "$VM_USER" "$VM_KEY")" == "true" ]; then
 else
    # If private hosts are not reachable then test the first public host and then
    # use that public host as a proxy to execute this command.
-
    VM_PUBLIC_HOSTS=`getClusterProperty "vm.public.hosts"`
    if [ "$VM_PUBLIC_HOSTS" == "" ]; then
       echo -e >&2 "${CError}ERROR:${CNone} Unable to connect to VM hosts. Please set 'vm.public.hosts' in 'etc/cluster.properties."
-      echo "       Command aborted."
+      echo >&2 "       Command aborted."
       exit 1
    fi
 
@@ -387,7 +386,7 @@ fi
 echo "------------------------------------------------------------------------------------------"
 
 if [ "$IS_PUBLIC_HOST" == "true" ]; then
-   # Use the public host a proxy to sync the rest of hosts
+   # Use the public host as a proxy to sync the rest of hosts
    #RWE_NAME=$(basename $PADOGRID_WORKSPACES_HOME)
    #WORKSPACE=$(basename $PADOGRID_WORKSPACE)
    RWE_NAME=$(basename $VM_PADOGRID_WORKSPACES_HOME)
