Tidied up vm_* commands

diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/vm_deploy_padogrid b/padogrid-deployment/src/main/resources/common/bin_sh/vm_deploy_padogrid
--- a/padogrid-deployment/src/main/resources/common/bin_sh/vm_deploy_padogrid
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/vm_deploy_padogrid
@@ -236,42 +236,90 @@ else
 fi
 
 # Find all existing and new hosts
-EXISTING_HOSTS=
-NEW_HOSTS=
+EXISTING_PADOGRID_BASE_HOSTS=""
+EXISTING_PADOGRID_HOSTS=""
+NEW_PADOGRID_BASE_HOSTS=""
+NEW_PADOGRID_HOSTS=""
+EXISTING_PADOGRID_BASE_HOST_COUNT=0
+EXISTING_PADOGRID_HOST_COUNT=0
+NEW_PADOGRID_BASE_HOST_COUNT=0
+NEW_PADOGRID_HOST_COUNT=0
 THIS_VM_HOSTNAME=`hostname`
-COMMAND="if [ -d "$VM_PADOGRID_HOME" ]; then echo true; else echo false; fi"
-EXISTING_HOST_COUNT=0
-NEW_HOST_COUNT=0
 for VM_HOST in $__VM_HOSTS; do
-   HOST_NAME=`ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "hostname"`
+   REPLY=`ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "hostname && echo \\$HOME"`
+   index=0
+   HOST_NAME=""
+   VM_HOME=""
+   for i in $REPLY; do
+      case $i in
+         0) HOST_NAME=$i;;
+         1) VM_HOME=$i;;
+      esac
+      let index=index+1
+   done
    if [ "$HOST_NAME" == "$THIS_VM_HOSTNAME" ]; then
       continue
    fi
+
+   if [ "$VM_HOME" != "" ]; then
+      # Replace '~' with the VM home path
+      __VM_PADOGRID_HOME=$(echo $VM_PADOGRID_HOME | sed "s|\~|$VM_HOME|")
+      __VM_PADOGRID_ENV_BASE_PATH=$(echo $VM_PADOGRID_ENV_BASE_PATH | sed "s|\~|$VM_HOME|")
+   else
+      __VM_PADOGRID_HOME=$VM_PADOGRID_HOME
+      __VM_PADOGRID_ENV_BASE_PATH=$VM_PADOGRID_ENV_BASE_PATH
+   fi
+
+   # padogrid base
+   COMMAND="[ -d "$__VM_PADOGRID_ENV_BASE_PATH" ] && echo true || echo false"
    DIR_EXISTS=`ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT $COMMAND`
    if [ "$DIR_EXISTS" == "true" ]; then
-      EXISTING_HOSTS="$EXISTING_HOSTS $VM_HOST"
-      let EXISTING_HOST_COUNT=EXISTING_HOST_COUNT+1
+      EXISTING_PADOGRID_BASE_HOSTS="$EXISTING_PADOGRID_BASE_HOSTS $VM_HOST"
+      let EXISTING_PADOGRID_BASE_HOST_COUNT=EXISTING_PADOGRID_BASE_HOST_COUNT+1
    else
-      NEW_HOSTS="$NEW_HOSTS $VM_HOST"
-      let NEW_HOST_COUNT=NEW_HOST_COUNT+1
+      NEW_PADOGRID_BASE_HOSTS="$NEW_PADOGRID_BASE_HOSTS $VM_HOST"
+      let NEW_PADOGRID_BASE_HOST_COUNT=NEW_PADOGRID_BASE_HOST_COUNT+1
+   fi
+
+   # padogrid
+   if [ "$DIR_EXISTS" == "true" ]; then
+      COMMAND="[ -d "$__VM_PADOGRID_HOME" ] && echo true || echo false"
+      DIR_EXISTS=`ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT $COMMAND`
+      if [ "$DIR_EXISTS" == "true" ]; then
+         EXISTING_PADOGRID_HOSTS="$EXISTING_PADOGRID_HOSTS $VM_HOST"
+         let EXISTING_PADOGRID_HOST_COUNT=EXISTING_PADOGRID_HOST_COUNT+1
+      else
+         NEW_PADOGRID_HOSTS="$NEW_PADOGRID_HOSTS $VM_HOST"
+         let NEW_PADOGRID_HOST_COUNT=NEW_PADOGRID_HOST_COUNT+1
+      fi
    fi
 done
 
-if [ "$EXISTING_HOSTS" != "" ]; then
+if [ "$EXISTING_PADOGRID_BASE_HOSTS" != "" ]; then
    echo ""
-   echo "padogrid installation found in the following host(s):"
-   echo "   $EXISTING_HOSTS"
+   echo "padogrid base found in the following host(s):"
+   echo "   $EXISTING_PADOGRID_BASE_HOSTS"
+fi
+if [ "$NEW_PADOGRID_BASE_HOSTS" != "" ]; then
+   echo ""
+   echo "padogrid base not found in the following host(s):"
+   echo "   $NEW_PADOGRID_BASE_HOSTS"
 fi
 
-if [ "$NEW_HOSTS" != "" ]; then
+if [ "$EXISTING_PADOGRID_HOSTS" != "" ]; then
+   echo ""
+   echo "padogrid installation found in the following host(s):"
+   echo "   $EXISTING_PADOGRID_HOSTS"
+fi
+if [ "$NEW_PADOGRID_HOSTS" != "" ]; then
    echo ""
    echo "padogrid installation not found in the following host(s):"
-   echo "   $NEW_HOSTS"
+   echo "   $NEW_PADOGRID_HOSTS"
 fi
-DEPLOYMENT_HOST_COUNT=$NEW_HOST_COUNT
+let DEPLOYMENT_HOST_COUNT=NEW_PADOGRID_BASE_HOST_COUNT+NEW_PADOGRID_HOST_COUNT
 INPUT=
 if [ "$QUIET" == "false" ] && [ "$OVERWRITE" != "true" ]; then
-   if [ "$EXISTING_HOSTS" != "" ]; then
+   if [ "$EXISTING_PADOGRID_HOSTS" != "" ]; then
       echo "Do you want to overwrite the existing installations?"
       echo "('overwrite' + Enter to overwrite the installations, other keys to continue.)"
       read INPUT
@@ -282,7 +330,7 @@ if [ "$QUIET" == "false" ] && [ "$OVERWRITE" != "true" ]; then
    if [ "$INPUT" == "overwrite" ]; then
       OVERWRITE="true"
       echo "This installation will be deployed to both existing and new hosts."
-   else
+   elif [ "$EXISTING_PADOGRID_HOSTS" != "" ]; then
       echo "Existing installations will be skipped."
    fi
    echo "Do you want to continue?"
@@ -298,7 +346,7 @@ if [ "$QUIET" == "false" ] && [ "$OVERWRITE" != "true" ]; then
 fi
 
 if [ "$OVERWRITE" == "true" ]; then
-   let DEPLOYMENT_HOST_COUNT=DEPLOYMENT_HOST_COUNT+EXISTING_HOST_COUNT
+   let DEPLOYMENT_HOST_COUNT=DEPLOYMENT_HOST_COUNT+EXISTING_PADOGRID_HOST_COUNT
 fi
 
 if [ "$IS_PUBLIC_HOST" != "true" ]; then
@@ -313,45 +361,58 @@ DOWNLOADS_DIR="$PADOGRID_ENV_BASE_PATH/downloads"
 ROOT_DIR_NAME=$(basename $PADOGRID_HOME)
 TAR_BALL_NAME=$ROOT_DIR_NAME.tar
 TAR_BALL_GZ_NAME=$ROOT_DIR_NAME.tar.gz
-TAR_BALL_GZ_PATH="$DOWNLOADS_DIR/$TAR_BALL_GZ_NAME"
+PADOGRID_TARBALL_GZ_PATH="$DOWNLOADS_DIR/$TAR_BALL_GZ_NAME"
 TAR_BALL_PATH=$PADOGRID_WORKSPACE/bundles/$TAR_BALL_NAME
 VM_PADOGRID_HOME_PARENT_DIR="$(dirname "$VM_PADOGRID_HOME")"
 
-echo "Creating a tar ball: [$TAR_BALL_GZ_PATH]..."
-if [ "$SIMULATE" != "true" ]; then
-   pushd $PADOGRID_HOME/..  > /dev/null 2>&1
-   tar czf $TAR_BALL_GZ_PATH $ROOT_DIR_NAME
+# Create padogrid tar ball if it does not exist in the downloads directory
+if [ ! -f "$PADOGRID_TARBALL_GZ_PATH" ]; then
+   pushd $PADOGRID_HOME/.. > /dev/null 2>&1
+   tar czf $PADOGRID_TARBALL_GZ_PATH $ROOT_DIR_NAME
    popd > /dev/null 2>&1
 fi
 
 ROOT_DIR_NAME=$(basename $PADOGRID_HOME)
 VM_PADOGRID_TARBALL_GZ_PATH="$VM_PADOGRID_ENV_BASE_PATH/downloads/$TAR_BALL_GZ_NAME"
 
-if [ "$NEW_HOSTS" != "" ]; then
+if [ "$NEW_PADOGRID_BASE_HOSTS" != "" ]; then
+   # Upload and execute install_padogrid 
+   for VM_HOST in $NEW_PADOGRID_BASE_HOSTS; do
+      if [ "$SIMULATE" == "true" ]; then
+         echo scp -q -o stricthostkeychecking=no -o LogLevel=error -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY `which install_padogrid` "$PADOGRID_TARBALL_GZ_PATH" $VM_USER@$VM_HOST:/tmp/
+         echo ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "/tmp/install_padogrid -file /tmp/$TAR_BALL_GZ_NAME && rm /tmp/install_padogrid && mv /tmp/$PADOGRID_TARBALL_GZ_PATH $VM_PADOGRID_ENV_BASE_PATH/downloads/"
+      else
+         scp -q -o stricthostkeychecking=no -o LogLevel=error -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY `which install_padogrid` "$PADOGRID_TARBALL_GZ_PATH" $VM_USER@$VM_HOST:/tmp/
+         ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "/tmp/install_padogrid -file /tmp/$TAR_BALL_GZ_NAME && rm /tmp/install_padogrid && mv /tmp/$TAR_BALL_GZ_NAME $VM_PADOGRID_ENV_BASE_PATH/downloads/"
+      fi
+   done
+fi
+
+if [ "$NEW_PADOGRID_HOSTS" != "" ]; then
    echo "New Hosts:"
-   for VM_HOST in $NEW_HOSTS; do
+   for VM_HOST in $NEW_PADOGRID_HOSTS; do
       echo "   Deploying to $VM_HOST..."
       if [ "$SIMULATE" == "true" ]; then
          echo ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "mkdir -p $VM_PADOGRID_HOME_PARENT_DIR"
-         echo scp -q -o stricthostkeychecking=no -o LogLevel=error -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY $TAR_BALL_GZ_PATH $VM_USER@$VM_HOST:$VM_PADOGRID_TARBALL_GZ_PATH
+         echo scp -q -o stricthostkeychecking=no -o LogLevel=error -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY $PADOGRID_TARBALL_GZ_PATH $VM_USER@$VM_HOST:$VM_PADOGRID_TARBALL_GZ_PATH
          echo ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "tar -C $VM_PADOGRID_HOME_PARENT_DIR -xzf $VM_PADOGRID_TARBALL_GZ_PATH"
       else
          ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "mkdir -p $VM_PADOGRID_HOME_PARENT_DIR"
-         scp -q -o stricthostkeychecking=no -o LogLevel=error -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY $TAR_BALL_GZ_PATH $VM_USER@$VM_HOST:$VM_PADOGRID_TARBALL_GZ_PATH
+         scp -q -o stricthostkeychecking=no -o LogLevel=error -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY $PADOGRID_TARBALL_GZ_PATH $VM_USER@$VM_HOST:$VM_PADOGRID_TARBALL_GZ_PATH
          ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "tar -C $VM_PADOGRID_HOME_PARENT_DIR -xzf $VM_PADOGRID_TARBALL_GZ_PATH"
       fi
    done
 fi
 
-if [ "$EXISTING_HOSTS" != "" ] && [ "$OVERWRITE" == "true" ] ; then
+if [ "$EXISTING_PADOGRID_HOSTS" != "" ] && [ "$OVERWRITE" == "true" ] ; then
    echo "Existing Hosts:"
-   for VM_HOST in $EXISTING_HOSTS; do
+   for VM_HOST in $EXISTING_PADOGRID_HOSTS; do
       echo "   Deploying to $VM_HOST..."
       if [ "$SIMULATE" == "true" ]; then
-         echo scp -q -o stricthostkeychecking=no -o LogLevel=error -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY $TAR_BALL_GZ_PATH $VM_USER@$VM_HOST:$VM_PADOGRID_TARBALL_GZ_PATH
+         echo scp -q -o stricthostkeychecking=no -o LogLevel=error -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY $PADOGRID_TARBALL_GZ_PATH $VM_USER@$VM_HOST:$VM_PADOGRID_TARBALL_GZ_PATH
          echo ssh -n $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "tar -C $VM_PADOGRID_HOME_PARENT_DIR -xzf $VM_PADOGRID_TARBALL_GZ_PATH"
       else
-         scp -q -o stricthostkeychecking=no -o LogLevel=error -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY $TAR_BALL_GZ_PATH $VM_USER@$VM_HOST:$VM_PADOGRID_TARBALL_GZ_PATH
+         scp -q -o stricthostkeychecking=no -o LogLevel=error -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY $PADOGRID_TARBALL_GZ_PATH $VM_USER@$VM_HOST:$VM_PADOGRID_TARBALL_GZ_PATH
          ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "tar -C $VM_PADOGRID_HOME_PARENT_DIR -xzf $VM_PADOGRID_TARBALL_GZ_PATH"
       fi
    done
@@ -367,9 +428,12 @@ if [ "$IS_PUBLIC_HOST" == "true" ]; then
       COMMAND_OPTS="-overwrite"
    fi
    if [ "$SIMULATE" == "true" ]; then
-      echo ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "switch_rwe $RWE_NAME/$WORKSPACE && $COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/$EXECUTABLE $COMMAND_OPTS -remote -cluster $CLUSTER $@"
+      #echo ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "switch_rwe $RWE_NAME/$WORKSPACE && $COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/$EXECUTABLE $COMMAND_OPTS -remote -cluster $CLUSTER $@"
+      echo ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/$EXECUTABLE $COMMAND_OPTS -remote $@"
+      ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/$EXECUTABLE $COMMAND_OPTS -remote $@"
    else
-      ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "switch_rwe $RWE_NAME/$WORKSPACE && $COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/$EXECUTABLE $COMMAND_OPTS -remote -cluster $CLUSTER $@"
+      #ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "switch_rwe $RWE_NAME/$WORKSPACE && $COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/$EXECUTABLE $COMMAND_OPTS -remote -cluster $CLUSTER $@"
+      ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/$EXECUTABLE $COMMAND_OPTS -remote $@"
    fi
 fi
 
diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/vm_sync b/padogrid-deployment/src/main/resources/common/bin_sh/vm_sync
--- a/padogrid-deployment/src/main/resources/common/bin_sh/vm_sync
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/vm_sync
@@ -229,10 +229,22 @@ trap 'cleanExit "$EXECUTABLE" "vm" "false"' INT
 PADOGRID_ENV_BASE_PATH="$(dirname $(dirname $PADOGRID_WORKSPACES_HOME))"
 THIS_VM_HOSTNAME=`hostname`
 
+#TMP_RWE_SETENV_FILE="$PADOGRID_WORKSPACE/tmp/padogrid-$EXECUTABLE-vm-rwe_setenv.sh"
+#TMP_SETENV_FILE="$PADOGRID_WORKSPACE/tmp/padogrid-$EXECUTABLE-vm-setenv.sh"
+#TMP_VM_SYNC_TARBALL_FILE="$PADOGRID_WORKSPACE/tmp/padogrid-$EXECUTABLE-vm-vm_sync.tar.gz"
+#TMP_ADDONENV_FILE="$PADOGRID_WORKSPACE/tmp/padogrid-$EXECUTABLE-vm-.addonenv.sh"
+#VM_TMP_VM_SYNC_TARBALL_FILE="/tmp/padogrid-$EXECUTABLE-vm-vm_sync.tar.gz"
+
 TMP_RWE_SETENV_FILE="/tmp/padogrid-$EXECUTABLE-vm-rwe_setenv.sh"
 TMP_SETENV_FILE="/tmp/padogrid-$EXECUTABLE-vm-setenv.sh"
 TMP_VM_SYNC_TARBALL_FILE="/tmp/padogrid-$EXECUTABLE-vm-vm_sync.tar.gz"
 TMP_ADDONENV_FILE="/tmp/padogrid-$EXECUTABLE-vm-.addonenv.sh"
+
+# Clean up tmp
+#if [ ! -d "$PADOGRID_WORKSPACE/tmp" ]; then
+#   mkdir -p "$PADOGRID_WORKSPACE/tmp"
+#fi
+rm $TMP_RWE_SETENV_FILE $TMP_SETENV_FILE $TMP_VM_SYNC_TARBALL_FILE $TMP_ADDONENV_FILE > /dev/null 2>&1
 
 # Replace '~' with the VM home path in 'vmenv.sh'
 VM_HOME=""
@@ -246,38 +258,89 @@ VM_PADOGRID_WORKSPACES_HOME=$(echo $VM_PADOGRID_WORKSPACES_HOME | sed -e "s|\~|$
 VM_JAVA_HOME=$(echo $VM_JAVA_HOME | sed -e "s|\~|$VM_HOME|")
 
 # Check if we need to deploy padogrid to any of the VMs
+PADOGRID_BASE_COMMAND="[ -d "$VM_PADOGRID_ENV_BASE_PATH" ] && echo true || echo false"
 PADOGRID_COMMAND="[ -d "$VM_PADOGRID_HOME" ] && echo true || echo false"
 JAVA_COMMAND="[ -d "$VM_JAVA_HOME" ] && echo true || echo false"
+RWE_SETENV_COMMAND="[ -f "$VM_PADOGRID_WORKSPACES_HOME/setenv.sh" ] && echo true || echo false"
+WORKSPACE_SETENV_COMMAND="[ -f "$VM_PADOGRID_WORKSPACE/setenv.sh" ] && echo true || echo false"
+
+INSTALL_PADOGRID_BASE_HOST_LIST=""
 INSTALL_PADOGRID_HOST_LIST=""
 INSTALL_JAVA_HOST_LIST=""
 SETENV_DOWNLOADED="false"
 for VM_HOST in $__VM_HOSTS; do
-   # padogrid
-   PADOGRID_EXISTS=$(ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$PADOGRID_COMMAND")
-   if [[ "$PADOGRID_EXISTS" == *"false" ]]; then
+   REPLY=$(ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$PADOGRID_BASE_COMMAND; $PADOGRID_COMMAND; $JAVA_COMMAND; $RWE_SETENV_COMMAND; $WORKSPACE_SETENV_COMMAND")
+   index=0
+   for i in $REPLY; do
+      case $index in
+         0) PADOGRID_BASE_EXISTS="$i" ;;
+         1) PADOGRID_EXISTS="$i" ;;
+         2) JAVA_EXISTS="$i" ;;
+         3) RWE_SETENV_EXISTS="$i" ;;
+         4) WORKSPACE_SETENV_EXISTS="$i" ;;
+      esac
+      let index=index+1
+   done
+   # padogrid base
+   if [[ "$PADOGRID_BASE_EXISTS" == *"false" ]]; then
+      INSTALL_PADOGRID_BASE_HOST_LIST="$INSTALL_PADOGRID_BASE_HOST_LIST $VM_HOST"
+   elif [[ "$PADOGRID_EXISTS" == *"false" ]]; then
+      # padogrid - set this only if padgrid base exists
       INSTALL_PADOGRID_HOST_LIST="$INSTALL_PADOGRID_HOST_LIST $VM_HOST"
    fi
    # java - for user info only
-   JAVA_EXISTS=$(ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$JAVA_COMMAND")
    if [[ "$JAVA_EXISTS" == *"false" ]]; then
       INSTALL_JAVA_HOST_LIST="$INSTALL_JAVA_HOST_LIST $VM_HOST"
    fi
 
    # Download the first VM's setenv.sh files. We'll use these later to update the remaining VMs.
-   if [ "$SETENV_DOWNLOADED" == "false" ]; then
-      # That could happen if new VMs were added or there were network issues.
-      if [ "$SIMULATE" == "true" ]; then
-        echo "scp -q -o stricthostkeychecking=no -o LogLevel=error -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY $VM_USER@$VM_HOST:$VM_PADOGRID_WORKSPACES_HOME/setenv.sh $TMP_RWE_SETENV_FILE > /dev/null 2>&1"
-        echo "scp -q -o stricthostkeychecking=no -o LogLevel=error -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY $VM_USER@$VM_HOST:$VM_PADOGRID_WORKSPACE/setenv.sh $TMP_SETENV_FILE > /dev/null 2>&1"
-      else
-         scp -q -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY $VM_USER@$VM_HOST:$VM_PADOGRID_WORKSPACES_HOME/setenv.sh $TMP_RWE_SETENV_FILE > /dev/null 2>&1
-         scp -q -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY $VM_USER@$VM_HOST:$VM_PADOGRID_WORKSPACE/setenv.sh $TMP_SETENV_FILE > /dev/null 2>&1
+   if [ "$SETENV_DOWNLOADED" == "false" ]; then 
+      if [ "$RWE_SETENV_EXISTS" == "true" ]; then
+         if [ "$SIMULATE" == "true" ]; then
+           echo "scp -q -o stricthostkeychecking=no -o LogLevel=error -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY $VM_USER@$VM_HOST:$VM_PADOGRID_WORKSPACES_HOME/setenv.sh $TMP_RWE_SETENV_FILE > /dev/null 2>&1"
+         else
+            scp -q -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY $VM_USER@$VM_HOST:$VM_PADOGRID_WORKSPACES_HOME/setenv.sh $TMP_RWE_SETENV_FILE > /dev/null 2>&1
+         fi
+      fi
+      if [ "$WORKSPACE_SETENV_EXISTS" == "true" ]; then
+         if [ "$SIMULATE" == "true" ]; then
+           echo "scp -q -o stricthostkeychecking=no -o LogLevel=error -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY $VM_USER@$VM_HOST:$VM_PADOGRID_WORKSPACE/setenv.sh $TMP_SETENV_FILE > /dev/null 2>&1"
+         else
+            scp -q -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY $VM_USER@$VM_HOST:$VM_PADOGRID_WORKSPACE/setenv.sh $TMP_SETENV_FILE > /dev/null 2>&1
+         fi
       fi
       if [ -f $TMP_RWE_SETENV_FILE ] && [ -f $TMP_SETENV_FILE ]; then
          SETENV_DOWNLOADED="true"
       fi
    fi
 done
+
+# Install the PadoGrid base on VMs that do not have it installed
+if [ "$INSTALL_PADOGRID_BASE_HOST_LIST" != "" ]; then
+   ROOT_DIR_NAME=$(basename $PADOGRID_HOME)
+   TAR_BALL_GZ_NAME=$ROOT_DIR_NAME.tar.gz
+   PADOGRID_TARBALL_GZ_PATH="$PADOGRID_ENV_BASE_PATH/downloads/$TAR_BALL_GZ_NAME"
+   VM_PADOGRID_HOME_PARENT_DIR="$(dirname "$VM_PADOGRID_HOME")"
+   VM_PADOGRID_TARBALL_GZ_PATH="$VM_PADOGRID_ENV_BASE_PATH/downloads/$TAR_BALL_GZ_NAME"
+
+   # Create padogrid tar ball if it does not exist in the downloads directory
+   if [ ! -f "$PADOGRID_TARBALL_GZ_PATH" ]; then
+      pushd $PADOGRID_HOME/.. > /dev/null 2>&1
+      tar czf $PADOGRID_TARBALL_GZ_PATH $ROOT_DIR_NAME
+      popd > /dev/null 2>&1
+   fi
+
+   # Upload and execute install_padogrid 
+   for VM_HOST in $INSTALL_PADOGRID_BASE_HOST_LIST; do
+      if [ "$SIMULATE" == "true" ]; then
+         echo scp -q -o stricthostkeychecking=no -o LogLevel=error -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY `which install_padogrid` "$PADOGRID_TARBALL_GZ_PATH" $VM_USER@$VM_HOST:/tmp/
+         echo ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "/tmp/install_padogrid -file /tmp/$TAR_BALL_GZ_NAME && rm /tmp/install_padogrid && mv /tmp/$PADOGRID_TARBALL_GZ_PATH $VM_PADOGRID_ENV_BASE_PATH/downloads/"
+      else
+         scp -q -o stricthostkeychecking=no -o LogLevel=error -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY `which install_padogrid` "$PADOGRID_TARBALL_GZ_PATH" $VM_USER@$VM_HOST:/tmp/
+         ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "/tmp/install_padogrid -file /tmp/$TAR_BALL_GZ_NAME && rm /tmp/install_padogrid && mv /tmp/$TAR_BALL_GZ_NAME $VM_PADOGRID_ENV_BASE_PATH/downloads/"
+      fi
+   done
+fi
 
 # Install PadoGrid on VMs that do not have it installed
 if [ "$INSTALL_PADOGRID_HOST_LIST" != "" ]; then
@@ -293,7 +356,6 @@ if [ "$INSTALL_PADOGRID_HOST_LIST" != "" ]; then
       tar czf $PADOGRID_TARBALL_GZ_PATH $ROOT_DIR_NAME
       popd > /dev/null 2>&1
    fi
-
 
    for VM_HOST in $INSTALL_PADOGRID_HOST_LIST; do
       echo "Deploying $ROOT_DIR_NAME to $VM_HOST..."
@@ -314,7 +376,43 @@ THIS_VM_HOSTNAME=`hostname`
 ABS_PATH="$PADOGRID_WORKSPACE"
 INITENV_COMMAND="[ -f "$VM_PADOGRID_WORKSPACES_HOME/initenv.sh" ] && echo true || echo false"
 ADDONENV_COMMAND="[ -f "$VM_PADOGRID_WORKSPACES_HOME/.addonenv.sh" ] && echo true || echo false"
-SETENV_COMMAND="[ -f "$VM_PADOGRID_WORKSPACES_HOME/setenv.sh" ] && echo true || echo false"
+RWE_SETENV_COMMAND="[ -f "$VM_PADOGRID_WORKSPACES_HOME/setenv.sh" ] && echo true || echo false"
+
+# Create RWE setenv.sh file if downloading it from the first VM failed earlier
+if [ ! -f "$TMP_RWE_SETENV_FILE" ]; then
+   cp $PADOGRID_WORKSPACES_HOME/setenv.sh $TMP_RWE_SETENV_FILE
+   # Reset all exported variables
+   EXPORT_HOME_LIST_RWE=$(grep "export .*HOME=" $TMP_RWE_SETENV_FILE | sed -e 's/^.*export //' -e 's/HOME=.*/HOME/')
+   for i in $EXPORT_HOME_LIST_RWE; do
+      sed -i$__SED_BACKUP -e "s/export $i=.*$/#export $i="\"\""/" -e 's/##/#/' $TMP_RWE_SETENV_FILE
+   done
+   sed -i$__SED_BACKUP -e 's|^.*export PADOGRID_HOME=.*$|   export PADOGRID_HOME='\"${VM_PADOGRID_HOME}\"'|' $TMP_RWE_SETENV_FILE
+
+   # Create VM workspace setenv.sh
+   for VM_PRODUCT_HOME_VAR in $VM_INSTALLED_PRODUCT_HOMES; do
+      VM_PRODUCT_HOME_DIR_NAME="${vm_installed_product_home_array[$VM_PRODUCT_HOME_VAR]}"
+      VM_PRODUCT_HOME_PATH="$VM_PADOGRID_PRODUCTS_PATH/$VM_PRODUCT_HOME_DIR_NAME"
+      sed -i$__SED_BACKUP -e "s|^.*export $VM_PRODUCT_HOME_VAR=.*$|   export $VM_PRODUCT_HOME_VAR="\"${VM_PRODUCT_HOME_PATH}\""|" $TMP_RWE_SETENV_FILE
+   done 
+fi
+
+# Create workspace setenv.sh file if downloading it from the first VM failed earlier
+if [ ! -f "$TMP_SETENV_FILE" ]; then
+   cp $PADOGRID_WORKSPACE/setenv.sh $TMP_SETENV_FILE
+   # Reset all exported variables
+   EXPORT_HOME_LIST_WORKSPACE=$(grep "export .*HOME=" $TMP_SETENV_FILE | sed -e 's/^.*export //' -e 's/HOME=.*/HOME/')
+   for i in $EXPORT_HOME_LIST_WORKSPACE; do
+      sed -i$__SED_BACKUP -e "s/export $i=.*$/#export $i="\"\""/" -e 's/##/#/' $TMP_SETENV_FILE
+   done
+   sed -i$__SED_BACKUP -e 's|^.*export PADOGRID_HOME=.*$|   export PADOGRID_HOME='\"${VM_PADOGRID_HOME}\"'|' $TMP_SETENV_FILE
+
+   # Create VM workspace setenv.sh
+   for VM_PRODUCT_HOME_VAR in $VM_INSTALLED_PRODUCT_HOMES; do
+      VM_PRODUCT_HOME_DIR_NAME="${vm_installed_product_home_array[$VM_PRODUCT_HOME_VAR]}"
+      VM_PRODUCT_HOME_PATH="$VM_PADOGRID_PRODUCTS_PATH/$VM_PRODUCT_HOME_DIR_NAME"
+      sed -i$__SED_BACKUP -e "s|^.*export $VM_PRODUCT_HOME_VAR=.*$|   export $VM_PRODUCT_HOME_VAR="\"${VM_PRODUCT_HOME_PATH}\""|" $TMP_SETENV_FILE
+   done
+fi
 
 # Set the found private key in 'setenv.sh'
 if [ -f "$VM_PRIVATE_KEY_FILE" ]; then
@@ -322,7 +420,7 @@ if [ -f "$VM_PRIVATE_KEY_FILE" ]; then
 else
    PRIVATE_KEY_FILE_NAME=""
 fi
-if [ "$__VM_PRIVATE_KEY_FILE_FOUND" == "true" ]; then
+if [ "$PRIVATE_KEY_FILE_NAME" != "" ]; then
    if [ "$SIMULATE" == "true" ]; then
       echo sed -i$__SED_BACKUP -e "s|VM_PRIVATE_KEY_FILE=.*$|VM_PRIVATE_KEY_FILE=\"$VM_PRIVATE_KEY_FILE\"|" -e "s|^.*#.*VM_PRIVATE_KEY_FILE|VM_PRIVATE_KEY_FILE|" "$PADOGRID_WORKSPACE/setenv.sh"
       echo sed -i$__SED_BACKUP -e "s|VM_PRIVATE_KEY_FILE=.*$|VM_PRIVATE_KEY_FILE=\"$REMOTE_PRIVATE_KEY_FILE\"|" -e "s|^.*#.*VM_PRIVATE_KEY_FILE|VM_PRIVATE_KEY_FILE|" "$TMP_SETENV_FILE"
@@ -375,9 +473,16 @@ for VM_HOST in $__VM_HOSTS; do
    fi
 
    # Configure the rwe directory if not configured already
-   INITENV_EXISTS=$(ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$INITENV_COMMAND")
-   ADDONENV_EXISTS=$(ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$ADDONENV_COMMAND")
-   SETENV_EXISTS=$(ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$SETENV_COMMAND")
+   REPLY=$(ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$INITENV_COMMAND; $ADDONENV_COMMAND; $RWE_SETENV_COMMAND")
+   index=0
+   for i in $REPLY; do
+      case $index in
+         0) INITENV_EXISTS="$i" ;;
+         1) ADDONENV_EXISTS="$i" ;;
+         2) RWE_SETENV_EXISTS="$i" ;;
+      esac
+      let index=index+1
+   done
 
    if [[ "$INITENV_EXISTS" == *"false" ]]; then
       scp -q -r -o stricthostkeychecking=no -o LogLevel=error -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY $PADOGRID_WORKSPACES_HOME/initenv.sh $VM_USER@$VM_HOST:$VM_PADOGRID_WORKSPACES_HOME/initenv.sh
@@ -390,7 +495,7 @@ for VM_HOST in $__VM_HOSTS; do
          scp -q -r -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY $TMP_ADDONENV_FILE $VM_USER@$VM_HOST:$VM_PADOGRID_WORKSPACES_HOME/.addonenv.sh
       fi
    fi
-   if [ "$RWE_SPECIFIED" == "true" ] || [[ "$SETENV_EXISTS" == *"false" ]]; then
+   if [ "$RWE_SPECIFIED" == "true" ] || [[ "$RWE_SETENV_EXISTS" == *"false" ]]; then
       if [ "$SIMULATE" == "true" ]; then
          echo scp -q -r -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT $VM_KEY $TMP_RWE_SETENV_FILE $VM_USER@$VM_HOST:$VM_PADOGRID_WORKSPACES_HOME/setenv.sh
       else
