Added more thorough VM validation logic

diff --git a/padogrid-deployment/src/main/resources/common/bin_sh/vm_test b/padogrid-deployment/src/main/resources/common/bin_sh/vm_test
--- a/padogrid-deployment/src/main/resources/common/bin_sh/vm_test
+++ b/padogrid-deployment/src/main/resources/common/bin_sh/vm_test
@@ -231,17 +231,30 @@ done
 echo "------------------------------------------------------------------------------------------"
 
 # Determine and display all VMs that do not have Java and the current cluster installed.
+PRODUCT_NAME=$(getProductName $PRODUCT $CLUSTER_TYPE)
+PRODUCT_HOME_VAR=$(getProductHome $PRODUCT_NAME)
+#   line=$(grep "export .*$PRODUCT_HOME_VAR" $TMP_SETENV_FILE)
+#   commented_line=$(echo $line | grep "^.*#")
 SOFTWARE_ISSUES_FOUND="false"
 PADOGRID_HOME_COMMAND="[ -d "$VM_PADOGRID_HOME" ] && echo true || echo false"
 JAVA_HOME_COMMAND="[ -d "$VM_JAVA_HOME" ] && echo true || echo false"
+PRODUCT_HOME_COMMAND="grep \"export .*$PRODUCT_HOME_VAR\" $VM_PADOGRID_WORKSPACE/setenv.sh"
 ADDON_NOT_FOUND_LIST=""
-JAVA_HOME_NOT_FOUND_LIST=""
 PADOGRID_HOME_NOT_FOUND_LIST=""
+JAVA_HOME_NOT_FOUND_LIST=""
+PRODUCT_HOME_NOT_FOUND_LIST=""
 echo "Determining installed products... Please wait."
 for VM_HOST in $__VM_HOSTS; do
    PADOGRID_HOME_EXISTS=$(ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$PADOGRID_HOME_COMMAND")
    JAVA_HOME_EXISTS=$(ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$JAVA_HOME_COMMAND")
-   PADOGRID_HOME_EXISTS=$(ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$PADOGRID_HOME_COMMAND")
+   line=$(ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$PRODUCT_HOME_COMMAND")
+   if [ "$line" != "" ]; then
+      commented_line=$(echo $line | grep "^.*#")
+      PRODUCT_HOME_EXISTS=$([ "$commented_line" == "" ] && echo "true" || echo "false" )
+   else
+      PRODUCT_HOME_EXISTS="false"
+   fi
+
    if [ "$PADOGRID_HOME_EXISTS" == "false" ]; then
       PADOGRID_HOME_NOT_FOUND_LIST="$PADOGRID_HOME_NOT_FOUND_LIST $VM_HOST"
       ISSUES_FOUND="true"
@@ -252,12 +265,28 @@ for VM_HOST in $__VM_HOSTS; do
       ISSUES_FOUND="true"
       SOFTWARE_ISSUES_FOUND="true"
    fi
+   if [ "$PRODUCT_HOME_EXISTS" == "false" ]; then
+      PRODUCT_HOME_NOT_FOUND_LIST="$PRODUCT_HOME_NOT_FOUND_LIST $VM_HOST"
+      ISSUES_FOUND="true"
+      SOFTWARE_ISSUES_FOUND="true"
+   fi
 done
 
+if [ "$PADOGRID_HOME_NOT_FOUND_LIST" != "" ]; then
+   echo "------------------------------------------------------------------------------------------"
+   echo -e "${CWarning}WARNING:${CNone}"
+   echo "   PadoGrid is not installed on the following VMs. Please execute 'vm_sync' to resolve"
+   echo "   this issue."
+   echo -e "      ${CHighlight}$PADOGRID_HOME_NOT_FOUND_LIST${CNone}"
+   echo ""
+   echo "VM PadoGrid Home Path:"
+   echo "      $VM_PADOGRID_HOME"
+   echo "------------------------------------------------------------------------------------------"
+fi
 if [ "$JAVA_HOME_NOT_FOUND_LIST" != "" ]; then
    JAVA_DIR_NAME=$(basename $VM_JAVA_HOME)
    echo "------------------------------------------------------------------------------------------"
-   echo -e "${CBrownOrange}WARNING:${CNone}"
+   echo -e "${CWarning}WARNING:${CNone}"
    echo "   Java is not installed on the following VMs. The workspace will not be operational"
    echo "   until you have installed Java on these VMs."
    echo -e "      ${CError}$JAVA_HOME_NOT_FOUND_LIST${CNone}"
@@ -271,23 +300,21 @@ if [ "$JAVA_HOME_NOT_FOUND_LIST" != "" ]; then
    echo "      vm_install -product $JAVA_DIR_NAME.tar.gz"
    echo "------------------------------------------------------------------------------------------"
 fi
-if [ "$PADOGRID_HOME_NOT_FOUND_LIST" != "" ]; then
+if [ "$PRODUCT_HOME_NOT_FOUND_LIST" != "" ]; then
    echo "------------------------------------------------------------------------------------------"
-   echo -e "${CBrownOrange}WARNING:${CNone}"
-   echo "   PadoGrid is not installed on the following VMs. Please execute 'vm_sync' to resolve"
-   echo "   this issue."
-   echo -e "      ${CHighlight}$PADOGRID_HOME_NOT_FOUND_LIST${CNone}"
-   echo ""
-   echo "VM PadoGrid Home Path:"
-   echo "      $VM_PADOGRID_HOME"
+   echo -e "${CWarning}WARNING:${CNone}"
+   echo "   The product [$PRODUCT_NAME] is not configured for the following VMs. Please install it"
+   echo "   with 'vm_install'."
+   echo -e "      ${CHighlight}$PRODUCT_HOME_NOT_FOUND_LIST${CNone}"
    echo "------------------------------------------------------------------------------------------"
 fi
 
-# Determine all products installed on VMs
+# Determine all products installed on the first VM
+__VM_HOST_FIRST=$(echo $__VM_HOSTS | sed 's/ .*//')
 if [ "$PADOGRID_HOME_NOT_FOUND_LIST" == "" ]; then
    declare -A vm_installed_product_array
    declare -A vm_installed_product_home_array
-   getVmProductArray vm_installed_product_array vm_installed_product_home_array
+   getVmProductArray $__VM_HOST_FIRST vm_installed_product_array vm_installed_product_home_array
    VM_INSTALLED_PRODUCTS=${!vm_installed_product_array[@]}
    VM_INSTALLED_PRODUCTS="$(echo $(printf '%s\n' $VM_INSTALLED_PRODUCTS|sort -u))"
 
@@ -298,14 +325,10 @@ if [ "$PADOGRID_HOME_NOT_FOUND_LIST" == "" ]; then
    done
    echo "------------------------------------------------------------------------------------------"
 fi
-PRODUCT_TYPE=$PRODUCT
-if [ "$CLUSTER_TYPE" == "gemfire" ]; then
-   PRODUCT_TYPE="gemfire"
-fi
-if [[ "$VM_INSTALLED_PRODUCTS" != *"$PRODUCT_TYPE"* ]]; then
+if [[ "$VM_INSTALLED_PRODUCTS" != *"$PRODUCT_NAME"* ]]; then
    echo "------------------------------------------------------------------------------------------"
    echo -e "${CBrownOrange}WARNING:${CNone}"
-   echo "   The cluster product [$PRODUCT_TYPE] is not installed in the VMs. The workspace will"
+   echo "   The cluster product [$PRODUCT_NAME] is not installed in the VMs. The workspace will"
    echo "   not be operational until you have installed the product."
    echo ""
    echo "To install the product in the VMs, download the correct version of the product and"
@@ -420,8 +443,12 @@ else
       echo "     when you execute 'vm_sync'."
       echo "       $PADOGRID_HOME_NOT_FOUND_LIST"
    fi
-   if [[ "$VM_INSTALLED_PRODUCTS" != *"$PRODUCT_TYPE"* ]]; then
-      echo -e "   - ${CError}$PRODUCT_TYPE not installed${CNone}. Please install $PRODUCT_TYPE with 'vm_install'."
+   if [ "$PRODUCT_HOME_NOT_FOUND_LIST" != "" ]; then
+      echo -e "   - ${CHighlight}[$PRODUCT_NAME] not configured${CNone} for following VMs. Please install/configure it with 'vm_install'."
+      echo "       $PRODUCT_HOME_NOT_FOUND_LIST"
+   fi
+   if [[ "$VM_INSTALLED_PRODUCTS" != *"$PRODUCT_NAME"* ]]; then
+      echo -e "   - ${CError}$PRODUCT_NAME not installed${CNone}. Please install $PRODUCT_NAME with 'vm_install'."
    fi
 fi
 if [ "$CLUSTER_SPECIFIED" == "true" ]; then
@@ -440,4 +467,3 @@ else
 fi
 fi
 echo "------------------------------------------------------------------------------------------"
-
