Added -product option to create_app

diff --git a/padogrid-deployment/src/main/resources/coherence/bin_sh/create_app b/padogrid-deployment/src/main/resources/coherence/bin_sh/create_app
--- a/padogrid-deployment/src/main/resources/coherence/bin_sh/create_app
+++ b/padogrid-deployment/src/main/resources/coherence/bin_sh/create_app
@@ -23,13 +23,18 @@ EXECUTABLE="`basename $0`"
 
 __options()
 {
-   echo "-app -name -?"
+   echo "-product -app -name -?"
 }
 
 if [ "$OPTIONS" == "true" ]; then
    __options
    exit
 fi
+
+PRODUCT_OPTIONS=$(echo "$APP_PRODUCT_LIST" | sed 's/ /|/g')
+PRODUCTS_SUPPORTED=$(echo "$APP_PRODUCT_LIST" | sed 's/ /, /g')
+THIS_PRODUCT="$(basename $(dirname $SCRIPT_DIR))"
+APP_OPTIONS="$(echo $(getAppOptions $THIS_PRODUCT) | sed 's/ /|/g')"
 
 if [ "$HELP" == "true" ]; then
 cat <<EOF
@@ -42,26 +47,30 @@ NAME
                  padogrid distribution
 
 SYNOPSIS
-   $EXECUTABLE [-app <app-name>] [-name <new-app-name>] [-?]
+   $EXECUTABLE [-product $PRODUCT_OPTIONS]
+              [-app app_name]
+              [-name new_app_name]
+              [-?]
 
 DESCRIPTION
-   Creates a new app by installing the specified app that is part of the
-   padogrid distribution. This command creates a new app directory in 
-   the workspace 'apps' directory.
+   Creates a new app by installing the specified app that is part of the padogrid
+   distribution. This command creates a new app directory in the workspace 'apps' directory.
 
-   You are encouraged to create as many apps as you need and configure them
-   to work with a specific Coherence cluster. By doing so, you minimize
-   reconfiguration efforts and your apps and the cluster can be bundled
-   together for easier deployment.
+   You are encouraged to create and configure as many apps as you need by specifying
+   different names using the '-name' option. By doing so, you minimize the reconfiguration
+   efforts.
 
 OPTIONS
+   -product $PRODUCT_OPTIONS
+             Product name. Supported products are $PRODUCTS_SUPPORTED.
+
    -app app_name
-             Name of the app to create. Use <tab><tab> to see available
-             apps. If not specified, then it defaults to 'perf_test'.
+             Name of the app to create. Use <tab><tab> to see available apps. If not
+             specified, then it defaults to 'perf_test'.
 
    -name new_app_name
-             New name of the app. If not specified, then it defaults
-             to app_name.
+             New name of the app. If not specified, then it defaults to 'perf_test' or
+             the specified app_name.
 
 DEFAULT
 EOF
@@ -84,6 +93,24 @@ SEE ALSO
 EOF
    printSeeAlsoList "*app*" $EXECUTABLE
    exit
+fi
+
+#
+# Run the target app command if the product is different.
+#
+PRODUCT="THIS_PRODUCT"
+if [ "$PRODUCT_ARG" != "" ]; then
+   if [ "$(containsWord "$APP_PRODUCT_LIST" "$PRODUCT_ARG")" == "false" ]; then
+      >&2 echo -e "${CLightRed}ERROR:${CNone} Specified product is not supported: [$PRODUCT_ARG]. Command aborted."
+      exit 1
+   fi
+   if [ "$THIS_PRODUCT" != "$PRODUCT_ARG" ]; then
+      if [ "$PRODUCT_ARG" == "jet" ]; then
+         PRODUCT_ARG="hazelcast"
+      fi
+      $PADOGRID_HOME/$PRODUCT_ARG/bin_sh/$EXECUTABLE "$@"
+      exit
+   fi
 fi
 
 if [ "$APP_SPECIFIED" == "false" ]; then
@@ -124,7 +151,9 @@ if [ -d "$APP_DIR/bin_sh" ]; then
 fi
 
 echo ""
-echo "App created in the following directory:"
-echo ""
-echo -e "   ${CLightGreen}$APP_DIR${CNone}"
+echo "App created as follows."
+echo -e "  Product: ${CLightGreen}$PRODUCT${CNone}"
+echo -e "      App: $APP"
+echo -e "     Name: $NAME_ARG"
+echo -e "Directory: ${CLightGreen}$APP_DIR${CNone}"
 echo ""
diff --git a/padogrid-deployment/src/main/resources/hazelcast/bin_sh/create_app b/padogrid-deployment/src/main/resources/hazelcast/bin_sh/create_app
--- a/padogrid-deployment/src/main/resources/hazelcast/bin_sh/create_app
+++ b/padogrid-deployment/src/main/resources/hazelcast/bin_sh/create_app
@@ -23,13 +23,18 @@ EXECUTABLE="`basename $0`"
 
 __options()
 {
-   echo "-app -name -?"
+   echo "-product -app -name -?"
 }
 
 if [ "$OPTIONS" == "true" ]; then
    __options
    exit
 fi
+
+PRODUCT_OPTIONS=$(echo "$APP_PRODUCT_LIST" | sed 's/ /|/g')
+PRODUCTS_SUPPORTED=$(echo "$APP_PRODUCT_LIST" | sed 's/ /, /g')
+THIS_PRODUCT="$(basename $(dirname $SCRIPT_DIR))"
+APP_OPTIONS="$(echo $(getAppOptions $THIS_PRODUCT) | sed 's/ /|/g')"
 
 if [ "$HELP" == "true" ]; then
 cat <<EOF
@@ -42,7 +47,10 @@ NAME
                  padogrid distribution
 
 SYNOPSIS
-   $EXECUTABLE [-app <app_name>] [-name new_app_name] [-?]
+   $EXECUTABLE [-product $PRODUCT_OPTIONS]
+              [-app app_name]
+              [-name new_app_name]
+              [-?]
 
 DESCRIPTION
    Creates a new app by installing the specified app that is part of the
@@ -55,15 +63,19 @@ DESCRIPTION
    together for easier deployment.
 
 OPTIONS
+   -product $PRODUCT_OPTIONS
+             Product name. Supported products are $PRODUCTS_SUPPORTED.
+
    -app app_name
-             Name of the app to create. Uset <tab><tab> to see available
-             apps. If not specified, then it defaults to 'perf_test'
-             if CLUSTER_TYPE is "imdg" or 'jet_demo' if CLUSTER_TYPE
-             is "jet".
+             Name of the app to create. Uset <tab><tab> to see available apps. If not 
+             specified, then it defaults to 'perf_test' if the specified product is 'hazelcast'
+             or 'jet_demo' if the specified product is 'jet'.
 
    -name new_app_name
-             New name of the app. If not specified, then it defaults
-             to app_name.
+             New name of the app. If not specified and the -product option is not specified,
+             then it defaults to 'perf_test' if the specified product is 'hazelcast' or 'jet_demo'
+             if the specified product is 'jet'. If the '-product' option is not specified, then
+             it defaults to 'perf_test' or the specified app_name.
 
 EOF
 if [ "$MAN_SPECIFIED" == "false" ]; then
@@ -92,6 +104,29 @@ SEE ALSO
 EOF
    printSeeAlsoList "*app*" $EXECUTABLE
    exit
+fi
+
+#
+# Run the target k8s command if the product is different.
+#
+PRODUCT="$THIS_PRODUCT"
+if [ "$PRODUCT_ARG" != "" ]; then
+   if [ "$(containsWord "$APP_PRODUCT_LIST" "$PRODUCT_ARG")" == "false" ]; then
+      >&2 echo -e "${CLightRed}ERROR:${CNone} Specified product is not supported: [$PRODUCT_ARG]. Command aborted."
+      exit 1
+   fi
+   if [ "$THIS_PRODUCT" != "$PRODUCT_ARG" ] && [ "$PRODUCT_ARG" != "jet" ]; then
+      $PADOGRID_HOME/$PRODUCT_ARG/bin_sh/$EXECUTABLE "$@"
+      exit
+   fi
+   if [ "$PRODUCT_ARG" == "jet" ]; then
+      CLUSTER_TYPE="jet"
+    else
+      CLUSTER_TYPE="imdg"
+    fi
+else
+   # Default product is hazelcast and hence CLUSTER_TYPE is "imdg"
+   CLUSTER_TYPE="imdg"
 fi
 
 if [ "$APP_SPECIFIED" == "false" ]; then
@@ -148,8 +183,9 @@ if [ -d "$APP_DIR/bin_sh" ]; then
    chmod 755 $APP_DIR/bin_sh/*
 fi
 
-echo ""
-echo "App created in the following directory:"
-echo ""
-echo -e "   ${CLightGreen}$APP_DIR${CNone}"
+echo "App created as follows."
+echo -e "  Product: ${CLightGreen}$CLUSTER_TYPE${CNone}"
+echo -e "      App: $APP"
+echo -e "     Name: $NAME_ARG"
+echo -e "Directory: ${CLightGreen}$APP_DIR${CNone}"
 echo ""
diff --git a/padogrid-deployment/src/main/resources/snappydata/bin_sh/create_k8s b/padogrid-deployment/src/main/resources/snappydata/bin_sh/create_k8s
--- a/padogrid-deployment/src/main/resources/snappydata/bin_sh/create_k8s
+++ b/padogrid-deployment/src/main/resources/snappydata/bin_sh/create_k8s
@@ -21,18 +21,20 @@ SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
 
 EXECUTABLE="`basename $0`"
 
-echo "$EXECUTABLE not supported for SnappyData for this release."
-exit
-
 __options()
 {
-   echo "-k8s -cluster -?"
+   echo "-product -k8s -cluster -?"
 }
 
 if [ "$OPTIONS" == "true" ]; then
    __options
    exit
 fi
+
+PRODUCT_OPTIONS=$(echo "$K8S_PRODUCT_LIST" | sed 's/ /|/g')
+PRODUCTS_SUPPORTED=$(echo "$K8S_PRODUCT_LIST" | sed 's/ /, /g')
+THIS_PRODUCT="$(basename $(dirname $SCRIPT_DIR))"
+K8S_OPTIONS="$(echo $(getK8sOptions $THIS_PRODUCT) | sed 's/ /|/g')"
 
 if [ "$HELP" == "true" ]; then
 cat <<EOF
@@ -44,7 +46,10 @@ NAME
    $EXECUTABLE - Create a Kubernetes environment in the current padogrid workspace
 
 SYNOPSIS
-   $EXECUTABLE [-k8s minikube] -cluster cluster_name [-?]
+   $EXECUTABLE [-product $PRODUCT_OPTIONS]
+              [-k8s $K8S_OPTIONS]
+              -cluster cluster_name
+              [-?]
 
 DESCRIPTION
    Creates a Kubernetes environment that includes SnappyData deployment files for
@@ -57,6 +62,9 @@ DESCRIPTION
    comes with a document describing the prerequisites and detailed instructions.
 
 OPTIONS
+   -product $PRODUCT_OPTIONS
+             Kubernetes cluster product name. Supported products are $PRODUCTS_SUPPORTED.
+
    -k8s minikube
              Minikube on your local machine.
 
@@ -68,7 +76,7 @@ EOF
 if [ "$MAN_SPECIFIED" == "false" ]; then
 cat <<EOF
 DEFAULT
-   $EXECUTABLE -k8s $DEFAULT_K8S -cluster cluster_name
+   $EXECUTABLE -product $THIS_PRODUCT -k8s $DEFAULT_K8S -cluster cluster_name
 
 FILES
    $PADOGRID_WORKSPACE/k8s
@@ -79,104 +87,21 @@ fi
    exit
 fi
 
-if [ "$CLUSTER_SPECIFIED" == "false" ]; then
-   >&2 echo "ERROR: The -cluster option is not specified. Command aborted."
-   exit
-fi
-
-if [ "$K8S" == "" ]; then
-   K8S=$DEFAULT_K8S
-fi
-if [ "$K8S" != "minikube" ]; then
-   >&2 echo "ERROR: Unsupported Kubernetes cloud platform. Please use the '-?' option"
-   >&2 echo "       to see the usage. Command aborted."
-   exit
-fi
-
 #
-# k8s directory
+# Run the target k8s command if the product is different.
 #
-K8S_DIR=$PADOGRID_WORKSPACE/k8s
-CLUSTER_DIR=$K8S_DIR/$CLUSTER
-
-if [ -d $CLUSTER_DIR ]; then
-   >&2 echo "ERROR: The specified Kubernetes cluster exists. Command aborted."
-   exit
-fi
-   
-
-if [ ! -d $CLUSTER_DIR ]; then
-   mkdir -p $CLUSTER_DIR
-fi
-
-create_setenv_file()
-{
-  echo "#" > $SETENV_FILE
-  echo "# Enter app specifics in this file." >> $SETENV_FILE
-  echo "#" >> $SETENV_FILE
-  echo "" >> $SETENV_FILE
-  echo "# Cluster level variables:" >> $SETENV_FILE
-  echo "# ------------------------" >> $SETENV_FILE
-  echo "# BASE_DIR - padogrid base dir" >> $SETENV_FILE
-  echo "# ETC_DIR - Cluster etc dir" >> $SETENV_FILE
-  echo "" >> $SETENV_FILE
-  echo "# App level variables:" >> $SETENV_FILE
-  echo "# --------------------" >> $SETENV_FILE
-  echo "# APPS_DIR - <padogrid>/apps dir" >> $SETENV_FILE
-  echo "# APP_DIR - App base dir" >> $SETENV_FILE
-  echo "# APP_ETC_DIR - App etc dir" >> $SETENV_FILE
-}
-
-SETENV_FILE="$CLUSTER_DIR/bin_sh/setenv.sh"
-
-if [ "$K8S" == "minikube" ]; then
-
-  K8S_DOC="README-Minikube.md"
-  cp -rf $BASE_DIR/k8s/kustom/bin_sh $CLUSTER_DIR
-  cp -rf $BASE_DIR/k8s/kustom/etc $CLUSTER_DIR
-  cp -rf $BASE_DIR/k8s/kustom/README-Minikube.md $CLUSTER_DIR
-  create_setenv_file
-  echo "" >> $SETENV_FILE
-  echo "#" >> $SETENV_FILE
-  echo "# Follow the instructions in $K8S_DOC using the following" >> $SETENV_FILE
-  echo "# environment variable." >> $SETENV_FILE
-  echo "#" >> $SETENV_FILE
-  echo "export SNAPPYDATA_KUSTOM_DIR=\$PADOGRID_WORKSPACE/k8s/$CLUSTER" >> $SETENV_FILE
-
-elif [ "$K8S" == "gke" ]; then
-
-  K8S_DOC="README-GKE.md"
-  cp -rf $BASE_DIR/k8s/kustom/bin_sh $CLUSTER_DIR
-  cp -rf $BASE_DIR/k8s/kustom/etc $CLUSTER_DIR
-  cp -rf $BASE_DIR/k8s/kustom/README-GKE.md $CLUSTER_DIR
-  rm -r $CLUSTER_DIR/etc/padogrid/storage/minikube
-  rm $CLUSTER_DIR/bin_sh/setenv.sh
-  create_setenv_file
-  echo "" >> $SETENV_FILE
-  echo "#" >> $SETENV_FILE
-  echo "# Set the following variables with your values and follow the instructions" >> $SETENV_FILE
-  echo "# in $K8S_DOC. Note that you would need to create a GKE cluster" >> $SETENV_FILE
-  echo "# first before you can set INSTANCE_NAME." >> $SETENV_FILE
-  echo "#" >> $SETENV_FILE
-  echo "export SNAPPYDATA_KUSTOM_DIR=\$PADOGRID_WORKSPACE/k8s/$CLUSTER" >> $SETENV_FILE
-  echo "export CLUSTER_NAME=$CLUSTER" >> $SETENV_FILE
-  echo "export GCR_HOSTNAME=gcr.io" >> $SETENV_FILE
-  echo "export PROJECT_ID=my-project" >> $SETENV_FILE
-  echo "export REGION=us-east1" >> $SETENV_FILE
-  echo "export ZONE=us-east1-b" >> $SETENV_FILE
-  echo "export INSTANCE_NAME=gke-kustomize-test-default-pool-c82eb23e-bzft" >> $SETENV_FILE
-
+if [ "$PRODUCT_ARG" != "" ]; then
+   if [ "$(containsWord "$K8S_PRODUCT_LIST" "$PRODUCT_ARG")" == "false" ]; then
+      >&2 echo -e "${CLightRed}ERROR:${CNone} Specified product is not supported: [$PRODUCT_ARG]. Command aborted."
+      exit 1
+   fi
+   if [ "$THIS_PRODUCT" != "$PRODUCT_ARG" ]; then
+      if [ "$PRODUCT_ARG" == "jet" ]; then
+         PRODUCT_ARG="hazelcast"
+      fi
+      $PADOGRID_HOME/$PRODUCT_ARG/bin_sh/$EXECUTABLE "$@"
+      exit
+   fi
 fi
 
-#
-# Display K8S Environment
-#
-echo ""
-echo "     WORKSPACE: $PADOGRID_WORKSPACE"
-echo "    Kubernetes: $K8S"
-echo "Kubernetes Environment:"
-echo "   $CLUSTER_DIR"
-echo ""
-echo "Please follow the instructions in the $K8S_DOC document in the"
-echo "above directory."
-echo ""
+echo "$EXECUTABLE not supported for $THIS_PRODUCT in this PadoGrid release. Use '-product' to specify another product."
