Added -all support in show_log

diff --git a/padogrid-deployment/src/main/resources/coherence/bin_sh/show_log b/padogrid-deployment/src/main/resources/coherence/bin_sh/show_log
--- a/padogrid-deployment/src/main/resources/coherence/bin_sh/show_log
+++ b/padogrid-deployment/src/main/resources/coherence/bin_sh/show_log
@@ -23,7 +23,7 @@ EXECUTABLE="`basename $0`"
 
 __options()
 {
-   echo "-cluster -num -full -log -?"
+   echo "-cluster -num -all -full -log -?"
 }
 
 if [ "$OPTIONS" == "true" ]; then
@@ -42,7 +42,7 @@ NAME
 
 SYNOPSIS
    $EXECUTABLE [-cluster <cluster-name>] [-num <member-number>]
-               [-full] [-log [data|gc]] [-?]
+               [-all | -full] [-log [data|gc]] [-?]
 
 DESCRIPTION
    Displays the specified member's log file. By default, follows the tail
@@ -58,6 +58,10 @@ DESCRIPTION
 
    -num member_number
               Member number 1-99
+
+   -all       
+              Display all log files. This option is applicable to local clusters only.
+              The '-num' option overrides this this option.
 
    -full
               Display the entire log file using 'less'
@@ -81,6 +85,15 @@ FILES
 EOF
 fi
    exit
+fi
+
+if [ "$ALL" == "true" ] && [ "$FULL" == "true" ]; then 
+   echo >&2 "${CLightRed}ERROR:${CNone} '-all' and '-full' cannot be specified together. Command aborted ."
+   exit 1
+fi
+# -num overrides -all
+if [ "$MEMBER_NUM_SPECIFIED" == "true" ]; then
+   ALL="false"
 fi
 
 # 
@@ -134,6 +147,7 @@ POD=`getClusterProperty "pod.name" "local"`
 NODE_NAME_PREFIX=`getPodProperty "node.name.prefix" $NODE_NAME_PREFIX`
 
 MEMBER_NUMBER=$MEMBER_NUM_NO_LEADING_ZERO
+MEMBER_PREFIX=`getMemberPrefix`
 MEMBER=`getMemberName $MEMBER_NUMBER`
 MEMBER_DIR=$RUN_DIR/$MEMBER
 
@@ -157,11 +171,19 @@ fi
 
 case "$LOG" in 
 gc)
-   LOG_FILE=$LOG_DIR/${MEMBER}-gc.log
+   if [ "$ALL" == "true" ]; then
+      LOG_FILE=$LOG_DIR/${MEMBER_PREFIX}??-gc.log
+   else
+      LOG_FILE=$LOG_DIR/${MEMBER}-gc.log
+   fi
    ;;
 
 *)
-   LOG_FILE=$LOG_DIR/${MEMBER}.log
+   if [ "$ALL" == "true" ]; then
+      LOG_FILE=$LOG_DIR/${MEMBER_PREFIX}??.log
+   else
+      LOG_FILE=$LOG_DIR/${MEMBER}.log
+   fi
    ;;
 
 esac
@@ -169,7 +191,9 @@ esac
 echo ""
 echo -e "Showing log: ${CLightGreen}$LOG_FILE${CNone}"
 echo ""
-if [ "$LOG_FILE" != "" ] && [ -f "$LOG_FILE" ]; then
+if [ "$ALL" == "true" ]; then
+   eval "tail -f $LOG_FILE"
+elif [ "$LOG_FILE" != "" ] && [ -f "$LOG_FILE" ]; then
    if [ "$FULL" == "true" ]; then 
       less $LOG_FILE
    else
diff --git a/padogrid-deployment/src/main/resources/hazelcast/bin_sh/show_log b/padogrid-deployment/src/main/resources/hazelcast/bin_sh/show_log
--- a/padogrid-deployment/src/main/resources/hazelcast/bin_sh/show_log
+++ b/padogrid-deployment/src/main/resources/hazelcast/bin_sh/show_log
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 # ========================================================================
-# Copyright (c) 2020 Netcrest Technologies, LLC. All rights reserved.
+# Copyright (c) 2020-2021 Netcrest Technologies, LLC. All rights reserved.
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
@@ -23,7 +23,7 @@ EXECUTABLE="`basename $0`"
 
 __options()
 {
-   echo "-cluster -num -full -log -?"
+   echo "-cluster -num -all -full -log -?"
 }
 
 if [ "$OPTIONS" == "true" ]; then
@@ -42,7 +42,7 @@ NAME
 
 SYNOPSIS
    $EXECUTABLE [-cluster <cluster-name>] [-num <member-number>]
-               [-full] [-log [data|gc|diag|mc]] [-?]
+               [-all | -full] [-log [data|gc|diag|mc]] [-?]
 
 DESCRIPTION
    Displays the specified member's log file. By default, follows the tail
@@ -57,10 +57,14 @@ DESCRIPTION
              Cluster name.
 
    -num member_number
-              Member number 1-99
+              Member number 1-99.
+
+   -all       
+              Display all log files. This option is applicable to local clusters only.
+              The '-num' option overrides this this option.
 
    -full
-              Display the entire log file using 'less'
+              Display the entire log file using 'less'.
 
    -log [data|gc|diag|mc]
               Display data, GC, or diagnostics file. Default: data
@@ -81,6 +85,15 @@ FILES
 EOF
 fi
    exit
+fi
+
+if [ "$ALL" == "true" ] && [ "$FULL" == "true" ]; then 
+   echo >&2 "${CLightRed}ERROR:${CNone} '-all' and '-full' cannot be specified together. Command aborted ."
+   exit 1
+fi
+# -num overrides -all
+if [ "$MEMBER_NUM_SPECIFIED" == "true" ]; then
+   ALL="false"
 fi
 
 # 
@@ -148,6 +161,7 @@ NODE_NAME_PREFIX=`getPodProperty "node.name.prefix" $NODE_NAME_PREFIX`
 retrieveClusterEnvFile $PADOGRID_WORKSPACE/clusters/$CLUSTER
 
 MEMBER_NUMBER=$MEMBER_NUM_NO_LEADING_ZERO
+MEMBER_PREFIX=`getMemberPrefix`
 MEMBER=`getMemberName $MEMBER_NUMBER`
 MEMBER_DIR=$RUN_DIR/$MEMBER
 MC_HTTP_PORT=`getClusterProperty "mc.http.port" $DEFAULT_MC_HTTP_PORT`
@@ -192,16 +206,24 @@ fi
 
 case "$LOG" in 
 gc)
-   LOG_FILE=$LOG_DIR/${MEMBER}-gc.log
+   if [ "$ALL" == "true" ]; then
+      LOG_FILE=$LOG_DIR/${MEMBER_PREFIX}??-gc.log
+   else
+      LOG_FILE=$LOG_DIR/${MEMBER}-gc.log
+   fi
    ;;
 
 diag)
-   # Find the lastest diagnositcs file
-   DIAG_FILES=`ls -t $LOG_DIR/${MEMBER}-diagnostics*`
-   for i in $DIAG_FILES; do
-      LOG_FILE=$i
-      break;
-   done
+   if [ "$ALL" == "true" ]; then
+      LOG_FILE=$LOG_DIR/${MEMBER_PREFIX}??-diagnostics*
+   else
+      # Find the lastest diagnositcs file
+      DIAG_FILES=`ls -t $LOG_DIR/${MEMBER}-diagnostics*`
+      for i in $DIAG_FILES; do
+         LOG_FILE=$i
+         break;
+      done
+   fi
    ;;
 
 mc)
@@ -209,11 +231,19 @@ mc)
    ;;
 
 data)
-   LOG_FILE=$LOG_DIR/${MEMBER}.log
+   if [ "$ALL" == "true" ]; then
+      LOG_FILE=$LOG_DIR/${MEMBER_PREFIX}??.log
+   else
+      LOG_FILE=$LOG_DIR/${MEMBER}.log
+   fi
    ;;
 
 *)
-   LOG_FILE=$LOG_DIR/${MEMBER}.log
+   if [ "$ALL" == "true" ]; then
+      LOG_FILE=$LOG_DIR/${MEMBER_PREFIX}??.log
+   else
+      LOG_FILE=$LOG_DIR/${MEMBER}.log
+   fi
    ;;
 
 esac
@@ -221,11 +251,13 @@ esac
 echo ""
 echo "Showing log: $LOG_FILE"
 echo ""
-if [ "$LOG_FILE" != "" ] && [ -f "$LOG_FILE" ]; then
+if [ "$ALL" == "true" ]; then
+   eval "tail -f $LOG_FILE"
+elif [ "$LOG_FILE" != "" ] && [ -f "$LOG_FILE" ]; then
    if [ "$FULL" == "true" ]; then 
       less $LOG_FILE
    else
-      tail -f $LOG_FILE
+      tail -f "$LOG_FILE"
    fi
 else
    echo "----------------------------------------------------------------"
diff --git a/padogrid-deployment/src/main/resources/snappydata/bin_sh/show_log b/padogrid-deployment/src/main/resources/snappydata/bin_sh/show_log
--- a/padogrid-deployment/src/main/resources/snappydata/bin_sh/show_log
+++ b/padogrid-deployment/src/main/resources/snappydata/bin_sh/show_log
@@ -15,15 +15,14 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 # ========================================================================
-  
-SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
+  SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
 . $SCRIPT_DIR/.addonenv.sh
 
 EXECUTABLE="`basename $0`"
 
 __options()
 {
-   echo "-cluster -num -full -log -?"
+   echo "-cluster -num -all -full -log -?"
 }
 
 if [ "$OPTIONS" == "true" ]; then
@@ -42,7 +41,7 @@ NAME
 
 SYNOPSIS
    $EXECUTABLE [-cluster <cluster-name>] [-num <member-number>]
-               [-full] [-log [data|gc|locator|leader]] [-?]
+               [-all | -full] [-log [data|gc|locator|leader]] [-?]
 
 DESCRIPTION
    Displays the specified member's log file. By default, follows the tail
@@ -58,6 +57,10 @@ DESCRIPTION
 
    -num member_number
               Member number 1-99
+
+   -all       
+              Display all log files. This option is applicable to local clusters only.
+              The '-num' option overrides this this option.
 
    -full
               Display the entire log file using 'less'
@@ -81,6 +84,15 @@ FILES
 EOF
 fi
    exit
+fi
+
+if [ "$ALL" == "true" ] && [ "$FULL" == "true" ]; then 
+   echo >&2 "${CLightRed}ERROR:${CNone} '-all' and '-full' cannot be specified together. Command aborted ."
+   exit 1
+fi
+# -num overrides -all
+if [ "$MEMBER_NUM_SPECIFIED" == "true" ]; then
+   ALL="false"
 fi
 
 # 
@@ -146,6 +158,7 @@ locator)
    # For pod clusters. If non-pod, the following variables are ignored.
    PRIMARY_NODE_NAME=`getPodProperty "node.name.primary" "$DEFAULT_NODE_NAME_PRIMARY"`
    NODE_NAME_PREFIX=$PRIMARY_NODE_NAME
+   LOCATOR_PREFIX=`getLocatorPrefix`
    MEMBER_NUMBER=$LOCATOR_NUM_NO_LEADING_ZERO
    LOCATOR=`getLocatorName $MEMBER_NUMBER`
    MEMBER_DIR=$RUN_DIR/$LOCATOR
@@ -155,6 +168,7 @@ leader)
    # For pod clusters. If non-pod, the following variables are ignored.
    PRIMARY_NODE_NAME=`getPodProperty "node.name.primary" "$DEFAULT_NODE_NAME_PRIMARY"`
    NODE_NAME_PREFIX=$PRIMARY_NODE_NAME
+   LEADER_PREFIX=`getLeaderPrefix`
    MEMBER_NUMBER=$MEMBER_NUM_NO_LEADING_ZERO
    LEADER=`getLeaderName $MEMBER_NUMBER`
    MEMBER_DIR=$RUN_DIR/$LEADER
@@ -162,6 +176,7 @@ leader)
 
 *)
    NODE_NAME_PREFIX=`getPodProperty "node.name.prefix" $NODE_NAME_PREFIX`
+   MEMBER_PREFIX=`getMemberPrefix`
    MEMBER_NUMBER=$MEMBER_NUM_NO_LEADING_ZERO
    MEMBER=`getMemberName $MEMBER_NUMBER`
    MEMBER_DIR=$RUN_DIR/$MEMBER
@@ -202,19 +217,35 @@ fi
 
 case "$LOG" in 
 locator)
-   LOG_FILE=$LOG_DIR/${LOCATOR}.log
+   if [ "$ALL" == "true" ]; then
+      LOG_FILE=$LOG_DIR/${LOCATOR_PREFIX}??.log
+   else
+      LOG_FILE=$LOG_DIR/${LOCATOR}.log
+   fi
    ;;
 
 leader)
-   LOG_FILE=$LOG_DIR/${LEADER}.log
+   if [ "$ALL" == "true" ]; then
+      LOG_FILE=$LOG_DIR/${LEADER_PREFIX}??.log
+   else
+      LOG_FILE=$LOG_DIR/${LEADER}.log
+   fi
    ;;
 
 gc)
-   LOG_FILE=$LOG_DIR/${MEMBER}-gc.log
+   if [ "$ALL" == "true" ]; then
+      LOG_FILE=$LOG_DIR/${MEMBER_PREFIX}??-gc.log
+   else
+      LOG_FILE=$LOG_DIR/${MEMBER}-gc.log
+   fi
    ;;
 
 *)
-   LOG_FILE=$LOG_DIR/${MEMBER}.log
+   if [ "$ALL" == "true" ]; then
+      LOG_FILE=$LOG_DIR/${MEMBER_PREFIX}??.log
+   else
+      LOG_FILE=$LOG_DIR/${MEMBER}.log
+   fi
    ;;
 
 esac
@@ -222,7 +253,9 @@ esac
 echo ""
 echo -e "Showing log: ${CLightGreen}$LOG_FILE${CNone}"
 echo ""
-if [ "$LOG_FILE" != "" ] && [ -f "$LOG_FILE" ]; then
+if [ "$ALL" == "true" ]; then
+   eval "tail -f $LOG_FILE"
+elif [ "$LOG_FILE" != "" ] && [ -f "$LOG_FILE" ]; then
    if [ "$FULL" == "true" ]; then 
       less $LOG_FILE
    else
diff --git a/padogrid-deployment/src/main/resources/spark/bin_sh/show_log b/padogrid-deployment/src/main/resources/spark/bin_sh/show_log
--- a/padogrid-deployment/src/main/resources/spark/bin_sh/show_log
+++ b/padogrid-deployment/src/main/resources/spark/bin_sh/show_log
@@ -23,7 +23,7 @@ EXECUTABLE="`basename $0`"
 
 __options()
 {
-   echo "-cluster -num -full -log -?"
+   echo "-cluster -num -all -full -log -?"
 }
 
 if [ "$OPTIONS" == "true" ]; then
@@ -42,7 +42,7 @@ NAME
 
 SYNOPSIS
    $EXECUTABLE [-cluster <cluster-name>] [-num <member-number>]
-               [-full] [-log [data|gc|locator]] [-?]
+               [-all | -full] [-log [data|gc|locator]] [-?]
 
 DESCRIPTION
    Displays the specified member's log file. By default, follows the tail
@@ -58,6 +58,10 @@ DESCRIPTION
 
    -num member_number
               Member number 1-99
+
+   -all       
+              Display all log files. This option is applicable to local clusters only.
+              The '-num' option overrides this this option.
 
    -full
               Display the entire log file using 'less'
@@ -81,6 +85,15 @@ FILES
 EOF
 fi
    exit
+fi
+
+if [ "$ALL" == "true" ] && [ "$FULL" == "true" ]; then 
+   echo >&2 "${CLightRed}ERROR:${CNone} '-all' and '-full' cannot be specified together. Command aborted ."
+   exit 1
+fi
+# -num overrides -all
+if [ "$MEMBER_NUM_SPECIFIED" == "true" ]; then
+   ALL="false"
 fi
 
 # 
@@ -153,6 +166,7 @@ master)
    ;;
 
 *)
+   MEMBER_PREFIX=`getMemberPrefix`
    MEMBER_NUMBER=$MEMBER_NUM_NO_LEADING_ZERO
    MEMBER=`getMemberName $MEMBER_NUMBER`
    MEMBER_DIR=$RUN_DIR/$MEMBER
@@ -176,7 +190,7 @@ if [ ! -d $MEMBER_DIR ]; then
    echo "  Cluster: $CLUSTER"
    if [ "$LOG" == "locator" ]; then
    echo "  Master: $MEMBER"
-   echo "   Status: This locator has not been configured. Please run the add_locator command to configure"
+   echo "   Status: This master has not been configured. Please run the add_master command to configure"
    echo "           new locators."
    else
    echo "   Member: $MEMBER"
@@ -189,17 +203,31 @@ fi
 
 case "$LOG" in 
 master)
-   MASTER_LOG="spark--org.apache.spark.deploy.master.Master-$MEMBER_NUMBER-`hostname`.out"
-   LOG_FILE=$LOG_DIR/${MASTER_LOG}
+   if [ "$ALL" == "true" ]; then
+      MASTER_LOG="spark--org.apache.spark.deploy.master.Master-*-`hostname`.out"
+      LOG_FILE=$LOG_DIR/${MASTER_LOG}
+   else
+      MASTER_LOG="spark--org.apache.spark.deploy.master.Master-$MEMBER_NUMBER-`hostname`.out"
+      LOG_FILE=$LOG_DIR/${MASTER_LOG}
+   fi
    ;;
 
 gc)
-   LOG_FILE=$LOG_DIR/${MEMBER}-gc.log
+   if [ "$ALL" == "true" ]; then
+      LOG_FILE=$LOG_DIR/${MEMBER_PREFIX}??-gc.log
+   else
+      LOG_FILE=$LOG_DIR/${MEMBER}-gc.log
+   fi
    ;;
 
 *)
-   MEMBER_LOG="spark--org.apache.spark.deploy.worker.Worker-$MEMBER_NUMBER-`hostname`.out"
-   LOG_FILE=$LOG_DIR/${MEMBER_LOG}
+   if [ "$ALL" == "true" ]; then
+      MEMBER_LOG="spark--org.apache.spark.deploy.worker.Worker-*-`hostname`.out"
+      LOG_FILE=$LOG_DIR/${MEMBER_PREFIX}*.log
+   else
+      MEMBER_LOG="spark--org.apache.spark.deploy.worker.Worker-$MEMBER_NUMBER-`hostname`.out"
+      LOG_FILE=$LOG_DIR/${MEMBER_LOG}
+   fi
    ;;
 
 esac
@@ -207,7 +235,9 @@ esac
 echo ""
 echo -e "Showing log: ${CLightGreen}$LOG_FILE${CNone}"
 echo ""
-if [ "$LOG_FILE" != "" ] && [ -f "$LOG_FILE" ]; then
+if [ "$ALL" == "true" ]; then
+   eval "tail -f $LOG_FILE"
+elif [ "$LOG_FILE" != "" ] && [ -f "$LOG_FILE" ]; then
    if [ "$FULL" == "true" ]; then 
       less $LOG_FILE
    else
