Fixed getMemberPid issues

diff --git a/padogrid-deployment/src/main/resources/redis/bin_sh/remove_cluster b/padogrid-deployment/src/main/resources/redis/bin_sh/remove_cluster
--- a/padogrid-deployment/src/main/resources/redis/bin_sh/remove_cluster
+++ b/padogrid-deployment/src/main/resources/redis/bin_sh/remove_cluster
@@ -73,7 +73,7 @@ retrieveClusterEnvFile $PADOGRID_WORKSPACE/clusters/$CLUSTER
 if [ "$CLUSTER_SPECIFIED" == "false" ]; then
    echo >&2 "----------------------------------------------------------------"
    echo >&2 "WORKSPACE: $PADOGRID_WORKSPACE"
-   echo >&2 "    ERROR: Cluster name is not specified. Command aborted." 
+   echo -e >&2 "    ${CLightRed}ERROR:${CNone} Cluster name is not specified. Command aborted."
    echo >&2 "----------------------------------------------------------------"
    exit 1
 fi
@@ -95,7 +95,7 @@ if [ -d $CLUSTER_DIR ]; then
 else
    echo >&2 "----------------------------------------------------------------"
    echo >&2 "WORKSPACE: $PADOGRID_WORKSPACE"
-   echo >&2 "    ERROR: The specified cluster does not exist: [$CLUSTER]. Command aborted."
+   echo -e >&2 "    ${CLightRed}ERROR:${CNone} The specified cluster does not exist: [$CLUSTER]. Command aborted."
    echo >&2 "----------------------------------------------------------------"
    exit 1
 fi
@@ -181,7 +181,7 @@ fi
 if [ $MEMBER_RUNNING_COUNT -gt 0 ]; then
    echo >&2 "----------------------------------------------------------------"
    echo >&2 "WORKSPACE: $PADOGRID_WORKSPACE"
-   echo >&2 "    ERROR: ${MEMBER_RUNNING_COUNT} member(s) are still running in the cluster. Please stop them first."
+   echo -e >&2 "    ${CLightRed}ERROR:${CNone} ${MEMBER_RUNNING_COUNT} member(s) are still running in the cluster. Please stop them first."
    echo >&2 "           Command aborted."
    echo >&2 "----------------------------------------------------------------"
    exit 1
