Fixed pod cluster remote invocation issues

diff --git a/padogrid-deployment/src/main/resources/snappydata/bin_sh/kill_leader b/padogrid-deployment/src/main/resources/snappydata/bin_sh/kill_leader
--- a/padogrid-deployment/src/main/resources/snappydata/bin_sh/kill_leader
+++ b/padogrid-deployment/src/main/resources/snappydata/bin_sh/kill_leader
@@ -159,17 +159,13 @@ fi
 #
 # Local cluster
 #
+
+NODE_NAME_PREFIX=`getPodProperty "node.name.prefix" $NODE_NAME_PREFIX`
+
 if [ "$POD" != "local" ]; then
    PRIMARY_NODE_NAME=`getPodProperty "node.name.primary" "$DEFAULT_NODE_NAME_PRIMARY"`
    NODE_LOCAL="${PRIMARY_NODE_NAME}.local"
    NODE_NAME_PREFIX=$PRIMARY_NODE_NAME
-fi
-
-if [ "$POD" != "local" ] && [ "$REMOTE_SPECIFIED" == "false" ]; then
-   NODE_NAME_PREFIX=`getPodProperty "node.name.prefix" $NODE_NAME_PREFIX`
-   NODE_LOCAL="${NODE_NAME_PREFIX}-${MEMBER_NUM}.local"
-   ssh -q -n $SSH_USER@$NODE_LOCAL -o stricthostkeychecking=no "cd $REMOTE_BASE_DIR/$PRODUCT/bin_sh; $COMMAND_PREFIX ./kill_leader -remote $NODE_LOCAL -workspace $PADOGRID_WORKSPACE $*;"
-   exit
 fi
 
 MEMBER_NUMBER=$MEMBER_NUM
@@ -177,6 +173,28 @@ MEMBER_PREFIX=`getLeaderPrefix`
 MEMBER=${MEMBER_PREFIX}$MEMBER_NUMBER
 MEMBER_DIR=$RUN_DIR/$MEMBER
 
+if  [ ! -d $CLUSTER_DIR ]; then
+   echo "----------------------------------------------------------------"
+   echo "Cluster: $CLUSTER"
+   echo " Status: This cluster has not been created. Please run the create_cluster command to"
+   echo "         to create the cluster before running this command."
+   echo "----------------------------------------------------------------"
+   exit 1
+fi
+
+if [ "$MEMBER_NUM_SPECIFIED" == "false" ]; then
+   echo "ERROR: Member number not specified. Run 'stop_leader -?' to see usage. Command aborted."
+   exit 1
+fi
+
+# If the command is executed in the pod then execute a remote command and exit.
+if [ "$POD" != "local" ] && [ "$REMOTE_SPECIFIED" == "false" ]; then
+   NODE_LOCAL="${NODE_NAME_PREFIX}-${MEMBER_NUM}.local"
+   ssh -q -n $SSH_USER@$NODE_LOCAL -o stricthostkeychecking=no "cd $REMOTE_BASE_DIR/$PRODUCT/bin_sh; $COMMAND_PREFIX ./kill_leader -remote $NODE_LOCAL -workspace $PADOGRID_WORKSPACE $*;"
+   exit
+fi
+
+# Local execution
 PID=`getLeaderPid $MEMBER $WORKSPACE`
 if [ -z $PID ]; then
    echo "Leader not running [$MEMBER]. Command aborted."
