Renamed mqtt commands

diff --git a/padogrid-deployment/src/main/resources/geode/bin_sh/tools/t_generate_avro_pdx b/padogrid-deployment/src/main/resources/geode/bin_sh/tools/t_generate_avro_pdx
--- a/padogrid-deployment/src/main/resources/geode/bin_sh/tools/t_generate_avro_pdx
+++ b/padogrid-deployment/src/main/resources/geode/bin_sh/tools/t_generate_avro_pdx
@@ -28,7 +28,7 @@ fi
 if [ "$PRODUCT" == "geode" ]; then
    "$JAVA" -Dexecutable.name=$EXECUTABLE com.netcrest.padogrid.tools.AvroPdxClassGenerator $@
 else
-   echo >&2 "ERROR: Avro-to-PDX class grenerator is not available for this product: [$PRODUCT]. Command aborted."
+   echo >&2 "ERROR: Avro-to-PDX class generator is not available for this product: [$PRODUCT]. Command aborted."
 fi
 exit
 
diff --git a/padogrid-deployment/src/main/resources/tools/bin_sh/t_generate_kryo_serializer b/padogrid-deployment/src/main/resources/tools/bin_sh/t_generate_kryo_serializer
--- a/padogrid-deployment/src/main/resources/tools/bin_sh/t_generate_kryo_serializer
+++ b/padogrid-deployment/src/main/resources/tools/bin_sh/t_generate_kryo_serializer
@@ -46,7 +46,7 @@ if [ "$PRODUCT" == "geode" ]; then
 elif [ "$PRODUCT" == "hazelcast" ]; then
    "$JAVA" -Dexecutable.name=$EXECUTABLE com.netcrest.padogrid.tools.HazelcastKryoGenerator $@
 else
-   echo >&2 "ERROR: Kryo grenerator is not available for this product: [$PRODUCT]. Command aborted."
+   echo >&2 "ERROR: Kryo generator is not available for this product: [$PRODUCT]. Command aborted."
 fi
 exit
 
