Added support for -count in add_member/remove_member

diff --git a/padogrid-deployment/src/main/resources/kafka/bin_sh/add_member b/padogrid-deployment/src/main/resources/kafka/bin_sh/add_member
--- a/padogrid-deployment/src/main/resources/kafka/bin_sh/add_member
+++ b/padogrid-deployment/src/main/resources/kafka/bin_sh/add_member
@@ -23,7 +23,7 @@ EXECUTABLE="`basename $0`"
 
 __options()
 {
-   echo "-cluster -num -all -?"
+   echo "-cluster -num -all -count -?"
 }
 
 if [ "$OPTIONS" == "true" ]; then
@@ -60,7 +60,10 @@ OPTIONS
              cluster; otherwise, it starts the member in the default cluster.
 
    -num member_number
-              number starting from 1.
+             Member number starting from 1.
+
+   -count member_count
+             Number of new menbers to add. If not specified, it adds one (1) member.
 
    -all      
              This option applies to VM clusters only. If specified, it adds a member
@@ -89,6 +92,24 @@ SEE ALSO
 EOF
    printSeeAlsoList "*member* *worker*" $EXECUTABLE
    exit
+fi
+
+#
+# If '-count' specified then recursively execute this command
+#
+if [ "$COUNT" != "" ]; then
+   if [ "$(isNumber $COUNT)" == "false" ]; then
+      echo -e "${CLightRed}ERROR:${CNone} Invalid number [$COUNT]. Command aborted."
+      exit 1
+   fi
+   if [ $COUNT -eq 0 ]; then
+     exit
+   elif [ $COUNT -gt 1 ]; then
+      for i in $(seq $COUNT); do
+         $EXECUTABLE
+      done
+      exit
+   fi
 fi
 
 #
