Added perf_test to Kafka

diff --git a/padogrid-deployment/src/main/resources/kafka/bin_sh/create_app b/padogrid-deployment/src/main/resources/kafka/bin_sh/create_app
--- a/padogrid-deployment/src/main/resources/kafka/bin_sh/create_app
+++ b/padogrid-deployment/src/main/resources/kafka/bin_sh/create_app
@@ -110,4 +110,64 @@ if [ "$PRODUCT_ARG" != "" ]; then
    fi
 fi
 
-echo "$EXECUTABLE not supported for $THIS_PRODUCT in this PadoGrid release. Use '-product' to specify another product."
+if [ "$APP_SPECIFIED" == "false" ]; then
+   APP="perf_test"
+fi
+if [ "$NAME_ARG" == "" ]; then
+   NAME_ARG=$APP
+fi
+
+if [ ! -d "$PADOGRID_HOME/$PRODUCT/apps/$APP" ]; then
+   >&2 echo "ERROR: The specified app does not exist: [$APP]. Command aborted."
+   exit 1
+fi
+
+# Create apps dir if it does not exist
+if [ ! -d "$APPS_DIR" ]; then
+   mkdir $APPS_DIR
+fi
+
+# Abort if the app dir already exists
+APP_DIR="$APPS_DIR/$NAME_ARG"
+if [ -d "$APP_DIR" ]; then
+   >&2 echo "ERROR: The specified new app name already exists. Command aborted."
+   exit 1
+fi
+
+# Copy all to the new app dir
+cp -r $PADOGRID_HOME/$PRODUCT/apps/$APP $APP_DIR
+#
+# Copy hibernate files to perf_test
+if [ "$APP" == "perf_test" ]; then
+   cp $PADOGRID_HOME/$PRODUCT/etc/template-hibernate.cfg-mysql.xml $APP_DIR/etc/hibernate.cfg-mysql.xml
+   cp $PADOGRID_HOME/$PRODUCT/etc/template-hibernate.cfg-postgresql.xml $APP_DIR/etc/hibernate.cfg-postgresql.xml
+fi
+
+# Make bin_sh scripts executables
+if [ -d "$APP_DIR/bin_sh" ]; then
+   chmod 755 $APP_DIR/bin_sh/*
+fi
+
+# Make bin_sh scripts executables
+if [ "$GROUP_PERMISSIONS_ENABLED" == "true" ]; then
+   # Set group permissions for workspace owner
+   chmod -R g+rw,o-rwx $APP_DIR
+   if [ -d "$APP_DIR/bin_sh" ]; then
+      chmod -R 770 $APP_DIR/bin_sh
+      chmod 660 $APP_DIR/bin_sh/.*.sh $APP_DIR/bin_sh/*.sh
+   fi
+else
+   if [ -d "$APP_DIR/bin_sh" ]; then
+      chmod 755 $APP_DIR/bin_sh/*
+      chmod 644 $APP_DIR/bin_sh/.*.sh $APP_DIR/bin_sh/*.sh
+   fi
+fi
+
+echo ""
+echo "App created as follows."
+echo -e "  Product: ${CGo}$PRODUCT${CNone}"
+echo -e "      App: $APP"
+echo -e "     Name: $NAME_ARG"
+echo -e "Directory: $APP_DIR"
+echo -e "       CD: ${CGo}cd_app $NAME_ARG${CNone}"
+echo ""
