Added derby app

diff --git a/padogrid-deployment/src/main/resources/hadoop/bin_sh/create_app b/padogrid-deployment/src/main/resources/hadoop/bin_sh/create_app
--- a/padogrid-deployment/src/main/resources/hadoop/bin_sh/create_app
+++ b/padogrid-deployment/src/main/resources/hadoop/bin_sh/create_app
@@ -110,4 +110,47 @@ if [ "$PRODUCT_ARG" != "" ]; then
    fi
 fi
 
-echo "$EXECUTABLE not supported for $THIS_PRODUCT in this PadoGrid release. Use '-product' to specify another product."
+if [ "$APP_SPECIFIED" == "false" ]; then
+   APP="derby"
+fi
+if [ "$NAME_ARG" == "" ]; then
+   NAME_ARG=$APP
+fi
+
+if [ ! -d "$PADOGRID_HOME/$PRODUCT/apps/$APP" ] && [ ! -d "$PADOGRID_HOME/apps/$APP" ]; then
+   >&2 echo -e "${CError}ERROR:${CNone} The specified app does not exist. Command aborted."
+   exit 1
+fi
+if [ "$APP" == "padodesktop" ] && [ ! -d "$PADODESKTOP_HOME" ]; then
+   >&2 echo -e "${CError}ERROR:${CNone} Pado Desktop not found. Command aborted."
+   exit 1
+fi
+
+# Create apps dir if it does not exist
+if [ ! -d "$APPS_DIR" ]; then
+   mkdir $APPS_DIR
+fi
+
+# Abort if the app dir already exists
+APP_DIR="$APPS_DIR/$NAME_ARG"
+if [ -d "$APP_DIR" ]; then
+   >&2 echo -e "${CError}ERROR:${CNone}The specified new app name already exists. Command aborted."
+   exit 1
+fi
+
+if [[ "$COMMON_APP_LIST" == *"$APP"* ]]; then
+
+   #
+   # Common apps for all products
+   #
+   cp -r $PADOGRID_HOME/apps/$APP $APP_DIR
+
+else
+
+   #
+   # Hadoop specific apps
+   #
+   
+   echo "App not supported."
+
+fi
diff --git a/padogrid-deployment/src/main/resources/hazelcast/bin_sh/create_app b/padogrid-deployment/src/main/resources/hazelcast/bin_sh/create_app
--- a/padogrid-deployment/src/main/resources/hazelcast/bin_sh/create_app
+++ b/padogrid-deployment/src/main/resources/hazelcast/bin_sh/create_app
@@ -154,8 +154,8 @@ if [ "$NAME_ARG" == "" ]; then
    NAME_ARG=$APP
 fi
 
-if [ ! -d "$PADOGRID_HOME/$PRODUCT/apps/$APP" ]; then
-   >&2 echo "ERROR: The specified app name does not exist. Command aborted."
+if [ ! -d "$PADOGRID_HOME/$PRODUCT/apps/$APP" ] && [ ! -d "$PADOGRID_HOME/apps/$APP" ]; then
+   >&2 echo -e "${CError}ERROR:${CNone} The specified app does not exist: [$APP]. Command aborted."
    exit 1
 fi
 
@@ -167,66 +167,80 @@ fi
 # Abort if the app dir already exists
 APP_DIR="$APPS_DIR/$NAME_ARG"
 if [ -d "$APP_DIR" ]; then
-   >&2 echo "ERROR: The specified new app name already exists. Command aborted."
+   >&2 echo -e "${CError}ERROR:${CNone}The specified new app name already exists: [$NAME_ARG]. Command aborted."
    exit 1
 fi
 
 # Copy all to the new app dir
-cp -r $PADOGRID_HOME/$PRODUCT/apps/$APP $APP_DIR
+if [[ "$COMMON_APP_LIST" == *"$APP"* ]]; then
 
-# Remove version number from src-?
-if [ -d "$APP_DIR/src-$HAZELCAST_MAJOR_VERSION_NUMBER" ]; then
-   mv "$APP_DIR/src-$HAZELCAST_MAJOR_VERSION_NUMBER" "$APP_DIR/src" 
-   rm -r "$APP_DIR/src-"*
-fi
-if [ -f "$APP_DIR/pom-${HAZELCAST_MAJOR_VERSION_NUMBER}.xml" ]; then
-   mv "$APP_DIR/pom-${HAZELCAST_MAJOR_VERSION_NUMBER}.xml" "$APP_DIR/pom.xml" 
-   rm -r "$APP_DIR/pom-"*
-fi
+   #
+   # Common apps for all products
+   #
+   cp -r $PADOGRID_HOME/apps/$APP $APP_DIR
 
-# Copy versioned config files to the etc/ dir
-if [ -d "$APP_DIR/etc/v${HAZELCAST_MAJOR_VERSION_NUMBER}" ]; then
-   cp $APP_DIR/etc/v${HAZELCAST_MAJOR_VERSION_NUMBER}/* $APP_DIR/etc/
-fi
-
-# Copy log4j2 file
-if [ "$APP" != "desktop" ] && [ "$APP" != "jet_demo" ] && [ "$APP" != "grafana" ]; then
-   cp $PADOGRID_HOME/$PRODUCT/etc/template-log4j2.properties $APP_DIR/etc/log4j2.properties
-fi
-
-# Copy hibernate files to perf_test
-if [ "$APP" == "perf_test" ]; then
-   cp $PADOGRID_HOME/$PRODUCT/etc/template-hibernate.cfg-mysql.xml $APP_DIR/etc/hibernate.cfg-mysql.xml
-   cp $PADOGRID_HOME/$PRODUCT/etc/template-hibernate.cfg-postgresql.xml $APP_DIR/etc/hibernate.cfg-postgresql.xml
-fi
-
-# Copy desktop files
-if [ "$APP" == "desktop" ]; then
-   if [ "$HAZELCAST_DESKTOP_HOME" == "" ]; then
-      echo -e "${CBrownOrange}WARNING:${CNone} Hazelcast Desktop is not installed. You can install it by running"
-      echo "         'install_padogrid -product hazelcast-desktop' or build it by running 'bin_sh/build_app'."
-   elif [ ! -d "$HAZELCAST_DESKTOP_HOME" ]; then
-      echo -e "${CBrownOrange}WARNING: ${CNone}Hazelcast Desktop directory does not exist. You can install it by running"
-      echo "         'install_padogrid -product hazelcast-desktop' or build it by running 'bin_sh/build_app'."
-      echo "         [$HAZELCAST_DESKTOP_HOME]"
-   else
-      cp -rf $HAZELCAST_DESKTOP_HOME/etc $APP_DIR/
-   fi
-fi
-
-# Make bin_sh scripts executables
-if [ "$GROUP_PERMISSIONS_ENABLED" == "true" ]; then
-   # Set group permissions for workspace owner
-   chmod -R g+rw,o-rwx $APP_DIR
-   if [ -d "$APP_DIR/bin_sh" ]; then
-      chmod -R 770 $APP_DIR/bin_sh
-      chmod 660 $APP_DIR/bin_sh/.*.sh $APP_DIR/bin_sh/*.sh
-   fi
 else
-   if [ -d "$APP_DIR/bin_sh" ]; then
-      chmod 755 $APP_DIR/bin_sh/*
-      chmod 644 $APP_DIR/bin_sh/.*.sh $APP_DIR/bin_sh/*.sh
+
+   #
+   # Hazelcast specific apps
+   #
+   cp -r $PADOGRID_HOME/$PRODUCT/apps/$APP $APP_DIR
+
+   # Remove version number from src-?
+   if [ -d "$APP_DIR/src-$HAZELCAST_MAJOR_VERSION_NUMBER" ]; then
+      mv "$APP_DIR/src-$HAZELCAST_MAJOR_VERSION_NUMBER" "$APP_DIR/src" 
+      rm -r "$APP_DIR/src-"*
    fi
+   if [ -f "$APP_DIR/pom-${HAZELCAST_MAJOR_VERSION_NUMBER}.xml" ]; then
+      mv "$APP_DIR/pom-${HAZELCAST_MAJOR_VERSION_NUMBER}.xml" "$APP_DIR/pom.xml" 
+      rm -r "$APP_DIR/pom-"*
+   fi
+
+   # Copy versioned config files to the etc/ dir
+   if [ -d "$APP_DIR/etc/v${HAZELCAST_MAJOR_VERSION_NUMBER}" ]; then
+      cp $APP_DIR/etc/v${HAZELCAST_MAJOR_VERSION_NUMBER}/* $APP_DIR/etc/
+   fi
+
+   # Copy log4j2 file
+   if [ "$APP" != "desktop" ] && [ "$APP" != "jet_demo" ] && [ "$APP" != "grafana" ]; then
+      cp $PADOGRID_HOME/$PRODUCT/etc/template-log4j2.properties $APP_DIR/etc/log4j2.properties
+   fi
+
+   # Copy hibernate files to perf_test
+   if [ "$APP" == "perf_test" ]; then
+      cp $PADOGRID_HOME/$PRODUCT/etc/template-hibernate.cfg-mysql.xml $APP_DIR/etc/hibernate.cfg-mysql.xml
+      cp $PADOGRID_HOME/$PRODUCT/etc/template-hibernate.cfg-postgresql.xml $APP_DIR/etc/hibernate.cfg-postgresql.xml
+   fi
+
+   # Copy desktop files
+   if [ "$APP" == "desktop" ]; then
+      if [ "$HAZELCAST_DESKTOP_HOME" == "" ]; then
+         echo -e "${CBrownOrange}WARNING:${CNone} Hazelcast Desktop is not installed. You can install it by running"
+         echo "         'install_padogrid -product hazelcast-desktop' or build it by running 'bin_sh/build_app'."
+      elif [ ! -d "$HAZELCAST_DESKTOP_HOME" ]; then
+         echo -e "${CBrownOrange}WARNING: ${CNone}Hazelcast Desktop directory does not exist. You can install it by running"
+         echo "         'install_padogrid -product hazelcast-desktop' or build it by running 'bin_sh/build_app'."
+         echo "         [$HAZELCAST_DESKTOP_HOME]"
+      else
+         cp -rf $HAZELCAST_DESKTOP_HOME/etc $APP_DIR/
+      fi
+   fi
+
+   # Make bin_sh scripts executables
+   if [ "$GROUP_PERMISSIONS_ENABLED" == "true" ]; then
+      # Set group permissions for workspace owner
+      chmod -R g+rw,o-rwx $APP_DIR
+      if [ -d "$APP_DIR/bin_sh" ]; then
+         chmod -R 770 $APP_DIR/bin_sh
+         chmod 660 $APP_DIR/bin_sh/.*.sh $APP_DIR/bin_sh/*.sh
+      fi
+   else
+      if [ -d "$APP_DIR/bin_sh" ]; then
+         chmod 755 $APP_DIR/bin_sh/*
+         chmod 644 $APP_DIR/bin_sh/.*.sh $APP_DIR/bin_sh/*.sh
+      fi
+   fi
+
 fi
 
 echo ""
diff --git a/padogrid-deployment/src/main/resources/none/bin_sh/create_app b/padogrid-deployment/src/main/resources/none/bin_sh/create_app
--- a/padogrid-deployment/src/main/resources/none/bin_sh/create_app
+++ b/padogrid-deployment/src/main/resources/none/bin_sh/create_app
@@ -124,8 +124,8 @@ if [ "$NAME_ARG" == "" ]; then
    NAME_ARG=$APP
 fi
 
-if [ ! -d "$PADOGRID_HOME/$PRODUCT/apps/$APP" ]; then
-   >&2 echo "ERROR: The specified app does not exist. Command aborted."
+if [ ! -d "$PADOGRID_HOME/$PRODUCT/apps/$APP" ] && [ ! -d "$PADOGRID_HOME/apps/$APP" ]; then
+   >&2 echo -e "${CError}ERROR:${CNone} The specified app does not exist: [$APP]. Command aborted."
    exit 1
 fi
 
@@ -137,36 +137,25 @@ fi
 # Abort if the app dir already exists
 APP_DIR="$APPS_DIR/$NAME_ARG"
 if [ -d "$APP_DIR" ]; then
-   >&2 echo "ERROR: The specified new app name already exists. Command aborted."
+   >&2 echo -e "${CError}ERROR:${CNone}The specified new app name already exists: [$NAME_ARG]. Command aborted."
    exit 1
 fi
 
-# Copy all to the new app dir
-cp -r $PADOGRID_HOME/$PRODUCT/apps/$APP $APP_DIR
+if [[ "$COMMON_APP_LIST" == *"$APP"* ]]; then
 
-# Copy versioned config files to the etc/ dir
-if [ -d "$APP_DIR/etc/v${GEODE_MAJOR_VERSION_NUMBER}" ]; then
-   cp $APP_DIR/etc/v${GEODE_MAJOR_VERSION_NUMBER}/* $APP_DIR/etc/
-fi
+   #
+   # Common apps for all products
+   #
+   cp -r $PADOGRID_HOME/apps/$APP $APP_DIR
 
-# Make bin_sh scripts executables
-if [ -d "$APP_DIR/bin_sh" ]; then
-   chmod 755 $APP_DIR/bin_sh/*
-fi
-
-# Make bin_sh scripts executables
-if [ "$GROUP_PERMISSIONS_ENABLED" == "true" ]; then
-   # Set group permissions for workspace owner
-   chmod -R g+rw,o-rwx $APP_DIR
-   if [ -d "$APP_DIR/bin_sh" ]; then
-      chmod -R 770 $APP_DIR/bin_sh
-      chmod 660 $APP_DIR/bin_sh/.*.sh $APP_DIR/bin_sh/*.sh
-   fi
 else
-   if [ -d "$APP_DIR/bin_sh" ]; then
-      chmod 755 $APP_DIR/bin_sh/*
-      chmod 644 $APP_DIR/bin_sh/.*.sh $APP_DIR/bin_sh/*.sh
-   fi
+
+   #
+   #  None specific apps
+   #
+
+   echo "App not supported."
+
 fi
 
 echo ""
