Added pado executable

diff --git a/padogrid-deployment/src/main/resources/geode/bin_sh/create_cluster b/padogrid-deployment/src/main/resources/geode/bin_sh/create_cluster
--- a/padogrid-deployment/src/main/resources/geode/bin_sh/create_cluster
+++ b/padogrid-deployment/src/main/resources/geode/bin_sh/create_cluster
@@ -146,9 +146,11 @@ if [ "$TYPE_ARG" == "pado" ]; then
   if [ "$PADO_HOME" == "" ]; then
    echo >&2 "----------------------------------------------------------------"
    echo >&2 "WORKSPACE: $PADOGRID_WORKSPACE"
-   echo >&2 "    ERROR: Pado is not found. You must specify the Pado installation path in the workspace 'setenv.sh' file."
-   echo >&2 "           using the PADO_HOME environment variable. Command aborted."
    echo >&2 "----------------------------------------------------------------"
+   echo >&2 "ERROR: Pado is not found. You must set PADO_HOME with the Pado installation path in the following"
+   echo >&2 "       workspace 'setenv.sh' file."
+   echo >&2 -e "       ${CLightRed}$PADOGRID_WORKSPACE/setenv.sh${CNone}"
+   echo >&2 "       Command aborted."
    exit 1
   fi
 fi
