Fixed property and docker issues

diff --git a/padogrid-deployment/src/main/resources/geode/bin_sh/create_grid b/padogrid-deployment/src/main/resources/geode/bin_sh/create_grid
--- a/padogrid-deployment/src/main/resources/geode/bin_sh/create_grid
+++ b/padogrid-deployment/src/main/resources/geode/bin_sh/create_grid
@@ -23,7 +23,7 @@ EXECUTABLE="`basename $0`"
 
 __options()
 {
-   echo "-prefix -count -type -port -?"
+   echo "-group -prefix -count -type -port -?"
 }
 
 if [ "$OPTIONS" == "true" ]; then
@@ -41,7 +41,8 @@ NAME
    $EXECUTABLE - Create multiple clusters
 
 SYNOPSIS
-   $EXECUTABLE [-prefix cluster_prefix_name]
+   $EXECUTABLE [-group group_name]
+               [-prefix cluster_prefix_name]
                [-type default|pado]
                [-count cluster_count]
                [-port first_locator_port_number] [-?]
@@ -53,6 +54,10 @@ DESCRIPTION
    etc/cluster.properties
 
 OPTIONS
+   -group group_name
+             Grid group name. The created clusters (grids) are grouped by this name. If this
+             option is not specified then the group name is assigned to 'default'.
+
    -prefix cluster_prefix_name
              The prefix of each cluster's name. Cluster names are enumuerated starting from
              0 and incremented by 1. For example, if the prefix is 'mycluster' then the first
@@ -61,7 +66,7 @@ OPTIONS
              then the last cluster is named 'mycluster2'.
 
    -type default|pado
-             If the 'pado' option is specified, then it creates Pado cluster that provide
+             If the 'pado' option is specified, then it creates Pado clusters that provide
              full support for grid federation. The 'default' option creates normal clusters
              without federation support and any Pado dependencies.
   
@@ -149,8 +154,23 @@ if [ "$TYPE_ARG" == "pado" ]; then
   fi
 fi
 
+if [ "$GROUP" == "" ]; then
+   GROUP="default"
+fi
+
 if [ "$TYPE_ARG" == "" ]; then
    TYPE_ARG="default"
+fi
+
+GROUP_NAMES=""
+CLUSTER_NAMES=""
+if [ -f "$PADOGRID_WORKSPACE/etc/clusters.properties" ]; then
+   GROUP_NAMES=$(getProperty "$PADOGRID_WORKSPACE/etc/clusters.properties" "clusters.group.names")
+   CLUSTER_NAMES=$(getProperty "$PADOGRID_WORKSPACE/etc/clusters.properties" "clusters.$GROUP.cluster.names")
+   if [ "$CLUSTER_NAMES" != "" ]; then
+      echo -e >&2 "${LightRed}ERROR:${CNone} The cluster group already exists: [$GROUP]. Command aborted."
+      exit 1
+   fi
 fi
 
 #
@@ -159,148 +179,181 @@ fi
 PARENT_LOCATOR_PORT=$DEFAULT_LOCATOR_START_PORT
 LOCATOR_PORT=$PARENT_LOCATOR_PORT
 for i in $(seq 0 $LAST_CLUSTER_NUM); do
-   create_cluster -cluster $PREFIX$i -type $TYPE_ARG -port $LOCATOR_PORT
+   CLUSTER_NAME="$PREFIX$i"
+   create_cluster -cluster $CLUSTER_NAME -type $TYPE_ARG -port $LOCATOR_PORT
    let LOCATOR_PORT=LOCATOR_PORT+10
+   if [ $i -eq 0 ]; then
+      CLUSTER_NAMES="$CLUSTER_NAME"
+   else
+      CLUSTER_NAMES="$CLUSTER_NAMES, $CLUSTER_NAME"
+   fi
 done
 
-if [ "$TYPE_ARG" != "pado" ]; then
-  exit
+if [ "$TYPE_ARG" == "pado" ]; then
+   
+   # Generate pado.xml
+   PARENT_PADO_XML="pado.xml"
+   PARENT_GRID_ID="${PREFIX}0"
+   PARENT_CLUSTER=$PARENT_GRID_ID
+   
+   # sys
+   CHILD_GRIDS=""
+   if [ $LAST_CLUSTER_NUM -gt 0 ]; then
+   for i in $(seq 1 $LAST_CLUSTER_NUM); do
+     CLUSTER="${PREFIX}$i"
+     CHILD_GRID="                \<grid id=\"${CLUSTER}\"\ routing-weight=\"1\">\<\/grid\>"
+     CHILD_GRIDS="                ${CHILD_GRIDS}\|${CHILD_GRID}"
+   done
+   fi
+   
+   # app1
+   APP1=""
+   if [ $LAST_CLUSTER_NUM -eq 0 ]; then
+     CLUSTER_NUM=0
+   else
+     CLUSTER_NUM=1
+   fi
+   CLUSTER=${PREFIX}${CLUSTER_NUM}
+   APP1="        <app id=\"app1\">"
+   APP1="$APP1|            \<grid-list id=\"app1 grid list\" default-grid-id=\"$CLUSTER\">"
+   for i in $(seq 0 $LAST_CLUSTER_NUM); do
+     CLUSTER="${PREFIX}$i"
+     if [ $i -eq 0 ]; then
+       ROUTING_WEIGHT="10"
+     else
+       ROUTING_WEIGHT="1"
+     fi
+     CHILD_GRID="                \<grid id=\"${CLUSTER}\"\ routing-weight=\"${ROUTING_WEIGHT}\">\<\/grid\>"
+     APP1="${APP1}\|${CHILD_GRID}"
+   done
+   APP1="${APP1}|                <description>Allowed grids for app1.<\/description>"
+   APP1="${APP1}|            <\/grid-list>"
+   APP1="${APP1}|       <\/app>"
+   
+   # test
+   TEST="        <app id=\"test\">"
+   TEST="$TEST|            \<grid-list id=\"test grid list\" default-grid-id=\"$CLUSTER\">"
+   for i in $(seq 0 $LAST_CLUSTER_NUM); do
+     CLUSTER="${PREFIX}$i"
+     if [ $i -eq 0 ]; then
+       ROUTING_WEIGHT="10"
+     else
+       ROUTING_WEIGHT="1"
+     fi
+     CHILD_GRID="                \<grid id=\"${CLUSTER}\"\ routing-weight=\"${ROUTING_WEIGHT}\">\<\/grid\>"
+     TEST="${TEST}\|${CHILD_GRID}"
+   done
+   TEST="${TEST}|                <description>Allowed grids for test.<\/description>"
+   TEST="${TEST}|            <\/grid-list>"
+   TEST="${TEST}|            <description>The test app is for running test suites.<\/description>"
+   TEST="${TEST}|        <\/app>"
+   
+   # demo
+   DEMO="            <app id=\"demo\">"
+   DEMO="$DEMO|                \<grid-list id=\"demo grid list\" default-grid-id=\"$CLUSTER\">"
+   for i in $(seq 0 $LAST_CLUSTER_NUM); do
+     CLUSTER="${PREFIX}$i"
+     if [ $i -eq 0 ]; then
+       ROUTING_WEIGHT="10"
+     else
+       ROUTING_WEIGHT="1"
+     fi
+     CHILD_GRID="                \<grid id=\"${CLUSTER}\"\ routing-weight=\"${ROUTING_WEIGHT}\">\<\/grid\>"
+     DEMO="${DEMO}\|${CHILD_GRID}"
+   done
+   DEMO="${DEMO}|                <description>Allowed grids for demo.<\/description>"
+   DEMO="${DEMO}|            <\/grid-list>"
+   DEMO="${DEMO}|        <\/app>"
+   
+   # app2
+   APP2=""
+   if [ $LAST_CLUSTER_NUM -gt 1 ]; then
+   CLUSTER=${PREFIX}2
+   APP2="        <app id=\"app2\">"
+   APP2="$APP2|            \<grid-list id=\"app2 grid list\" default-grid-id=\"$CLUSTER\">"
+   for i in $(seq 0 $LAST_CLUSTER_NUM); do
+     CLUSTER="${PREFIX}$i"
+     if [ $i -eq 0 ]; then
+       ROUTING_WEIGHT="10"
+     else
+       ROUTING_WEIGHT="1"
+     fi
+     CHILD_GRID="                \<grid id=\"${CLUSTER}\"\ routing-weight=\"${ROUTING_WEIGHT}\">\<\/grid\>"
+     APP2="${APP2}\|${CHILD_GRID}"
+   done
+   APP2="${APP2}|                <description>Allowed grids for app2.<\/description>"
+   APP2="${APP2}|            <\/grid-list>"
+   APP2="${APP2}|        <\/app>"
+   fi
+   
+   #
+   # Generate parent pado.xml
+   #
+   PARENT_CLUSTER_DIR=$CLUSTERS_DIR/$PARENT_CLUSTER
+   sed -e "s/\${GRID_ID}/$PARENT_GRID_ID/g" \
+       -e "s/\${CHILD_GRIDS}/$CHILD_GRIDS/g" \
+       -e "s/\${APP1}/$APP1/g" \
+       -e "s/\${APP2}/$APP2/g" \
+       -e "s/\${TEST}/$TEST/g" \
+       -e "s/\${DEMO}/$DEMO/g" \
+       $PADOGRID_HOME/geode/pado/etc/grid/template-pado-parent.xml \
+       | tr '|' '\n' \
+       > $PARENT_CLUSTER_DIR/etc/grid/$PARENT_PADO_XML
+   
+   #
+   # Generate child pado.xml
+   #
+   PARENT_GRID_ID="${PREFIX}0"
+   PARENT_ROOT_PATH="$PARENT_GRID_ID"
+   PARENT_LOCATORS="localhost:$PARENT_LOCATOR_PORT"
+   if [ $LAST_CLUSTER_NUM -gt 0 ]; then
+   for i in $(seq 1 $LAST_CLUSTER_NUM); do
+     CLUSTER="${PREFIX}$i"
+     GRID_ID=$CLUSTER
+     GRID_IDS="$GRID_IDS $GRID_ID"
+     CLUSTER_DIR=$CLUSTERS_DIR/$CLUSTER
+     sed -e "s/\${GRID_ID}/$GRID_ID/g" \
+         -e "s/\${PARENT_GRID_ID}/$PARENT_GRID_ID/g" \
+         -e "s/\${PARENT_ROOT_PATH}/$PARENT_ROOT_PATH/g" \
+         -e "s/\${PARENT_LOCATORS}/$PARENT_LOCATORS/g" \
+         $PADOGRID_HOME/geode/pado/etc/grid/template-pado-child.xml  > $CLUSTER_DIR/etc/grid/pado.xml
+   done
+   fi
+   
+   #
+   # Copy pado.properties to all
+   #
+   GRID_IDS=""
+   for i in $(seq 0 $LAST_CLUSTER_NUM); do
+     CLUSTER="${PREFIX}$i"
+     CLUSTER_DIR=$CLUSTERS_DIR/$CLUSTER
+     cp $PADOGRID_HOME/geode/pado/etc/grid/pado.properties $CLUSTER_DIR/etc/grid/pado.properties
+   done
+
 fi
 
-# Generate pado.xml
-PARENT_PADO_XML="pado.xml"
-PARENT_GRID_ID="${PREFIX}0"
-PARENT_CLUSTER=$PARENT_GRID_ID
+# Group the grid (cluster) IDs
 
-# sys
-CHILD_GRIDS=""
-if [ $LAST_CLUSTER_NUM -gt 0 ]; then
-for i in $(seq 1 $LAST_CLUSTER_NUM); do
-  CLUSTER="${PREFIX}$i"
-  CHILD_GRID="                \<grid id=\"${CLUSTER}\"\ routing-weight=\"1\">\<\/grid\>"
-  CHILD_GRIDS="                ${CHILD_GRIDS}\|${CHILD_GRID}"
-done
-fi
-
-# app1
-APP1=""
-if [ $LAST_CLUSTER_NUM -eq 0 ]; then
-  CLUSTER_NUM=0
+if [ "$GROUP_NAMES" == "" ]; then
+   GROUP_NAMES="$GROUP"
 else
-  CLUSTER_NUM=1
-fi
-CLUSTER=${PREFIX}${CLUSTER_NUM}
-APP1="        <app id=\"app1\">"
-APP1="$APP1|            \<grid-list id=\"app1 grid list\" default-grid-id=\"$CLUSTER\">"
-for i in $(seq 0 $LAST_CLUSTER_NUM); do
-  CLUSTER="${PREFIX}$i"
-  if [ $i -eq 0 ]; then
-    ROUTING_WEIGHT="10"
-  else
-    ROUTING_WEIGHT="1"
-  fi
-  CHILD_GRID="                \<grid id=\"${CLUSTER}\"\ routing-weight=\"${ROUTING_WEIGHT}\">\<\/grid\>"
-  APP1="${APP1}\|${CHILD_GRID}"
-done
-APP1="${APP1}|                <description>Allowed grids for app1.<\/description>"
-APP1="${APP1}|            <\/grid-list>"
-APP1="${APP1}|       <\/app>"
-
-# test
-TEST="        <app id=\"test\">"
-TEST="$TEST|            \<grid-list id=\"test grid list\" default-grid-id=\"$CLUSTER\">"
-for i in $(seq 0 $LAST_CLUSTER_NUM); do
-  CLUSTER="${PREFIX}$i"
-  if [ $i -eq 0 ]; then
-    ROUTING_WEIGHT="10"
-  else
-    ROUTING_WEIGHT="1"
-  fi
-  CHILD_GRID="                \<grid id=\"${CLUSTER}\"\ routing-weight=\"${ROUTING_WEIGHT}\">\<\/grid\>"
-  TEST="${TEST}\|${CHILD_GRID}"
-done
-TEST="${TEST}|                <description>Allowed grids for test.<\/description>"
-TEST="${TEST}|            <\/grid-list>"
-TEST="${TEST}|            <description>The test app is for running test suites.<\/description>"
-TEST="${TEST}|        <\/app>"
-
-# demo
-DEMO="            <app id=\"demo\">"
-DEMO="$DEMO|                \<grid-list id=\"demo grid list\" default-grid-id=\"$CLUSTER\">"
-for i in $(seq 0 $LAST_CLUSTER_NUM); do
-  CLUSTER="${PREFIX}$i"
-  if [ $i -eq 0 ]; then
-    ROUTING_WEIGHT="10"
-  else
-    ROUTING_WEIGHT="1"
-  fi
-  CHILD_GRID="                \<grid id=\"${CLUSTER}\"\ routing-weight=\"${ROUTING_WEIGHT}\">\<\/grid\>"
-  DEMO="${DEMO}\|${CHILD_GRID}"
-done
-DEMO="${DEMO}|                <description>Allowed grids for demo.<\/description>"
-DEMO="${DEMO}|            <\/grid-list>"
-DEMO="${DEMO}|        <\/app>"
-
-# app2
-APP2=""
-if [ $LAST_CLUSTER_NUM -gt 1 ]; then
-CLUSTER=${PREFIX}2
-APP2="        <app id=\"app2\">"
-APP2="$APP2|            \<grid-list id=\"app2 grid list\" default-grid-id=\"$CLUSTER\">"
-for i in $(seq 0 $LAST_CLUSTER_NUM); do
-  CLUSTER="${PREFIX}$i"
-  if [ $i -eq 0 ]; then
-    ROUTING_WEIGHT="10"
-  else
-    ROUTING_WEIGHT="1"
-  fi
-  CHILD_GRID="                \<grid id=\"${CLUSTER}\"\ routing-weight=\"${ROUTING_WEIGHT}\">\<\/grid\>"
-  APP2="${APP2}\|${CHILD_GRID}"
-done
-APP2="${APP2}|                <description>Allowed grids for app2.<\/description>"
-APP2="${APP2}|            <\/grid-list>"
-APP2="${APP2}|        <\/app>"
+   GROUP_NAMES="$GROUP_NAMES, $GROUP"
 fi
 
-#
-# Generate parent pado.xml
-#
-PARENT_CLUSTER_DIR=$CLUSTERS_DIR/$PARENT_CLUSTER
-sed -e "s/\${GRID_ID}/$PARENT_GRID_ID/g" \
-    -e "s/\${CHILD_GRIDS}/$CHILD_GRIDS/g" \
-    -e "s/\${APP1}/$APP1/g" \
-    -e "s/\${APP2}/$APP2/g" \
-    -e "s/\${TEST}/$TEST/g" \
-    -e "s/\${DEMO}/$DEMO/g" \
-    $PADOGRID_HOME/geode/pado/etc/grid/template-pado-parent.xml \
-    | tr '|' '\n' \
-    > $PARENT_CLUSTER_DIR/etc/grid/$PARENT_PADO_XML
-
-#
-# Generate child pado.xml
-#
-PARENT_GRID_ID="${PREFIX}0"
-PARENT_ROOT_PATH="$PARENT_GRID_ID"
-PARENT_LOCATORS="localhost:$PARENT_LOCATOR_PORT"
-if [ $LAST_CLUSTER_NUM -gt 0 ]; then
-for i in $(seq 1 $LAST_CLUSTER_NUM); do
-  CLUSTER="${PREFIX}$i"
-  GRID_ID=$CLUSTER
-  CLUSTER_DIR=$CLUSTERS_DIR/$CLUSTER
-  sed -e "s/\${GRID_ID}/$GRID_ID/g" \
-      -e "s/\${PARENT_GRID_ID}/$PARENT_GRID_ID/g" \
-      -e "s/\${PARENT_ROOT_PATH}/$PARENT_ROOT_PATH/g" \
-      -e "s/\${PARENT_LOCATORS}/$PARENT_LOCATORS/g" \
-      $PADOGRID_HOME/geode/pado/etc/grid/template-pado-child.xml  > $CLUSTER_DIR/etc/grid/pado.xml
-done
+if [ ! -d "$PADOGRID_WORKSPACE/etc" ]; then
+   mkdir "$PADOGRID_WORKSPACE/etc"
 fi
 
-#
-# Copy pado.properties to all
-#
-for i in $(seq 0 $LAST_CLUSTER_NUM); do
-  CLUSTER="${PREFIX}$i"
-  GRID_ID=$CLUSTER
-  CLUSTER_DIR=$CLUSTERS_DIR/$CLUSTER
-  cp $PADOGRID_HOME/geode/pado/etc/grid/pado.properties $CLUSTER_DIR/etc/grid/pado.properties
-done
+if [ ! -f "$PADOGRID_WORKSPACE/etc/clusters.properties" ]; then
+   echo "#" > "$PADOGRID_WORKSPACE/etc/clusters.properties"
+   echo "# This file contains workspace-wide cluster specific properties." >> "$PADOGRID_WORKSPACE/etc/clusters.properties"
+   echo "#" >> "$PADOGRID_WORKSPACE/etc/clusters.properties"
+   echo "" >> "$PADOGRID_WORKSPACE/etc/clusters.properties"
+   echo "# Enter comma separated cluster group names" >> "$PADOGRID_WORKSPACE/etc/clusters.properties"
+   echo "clusters.group.names=$GROUP_NAMES" >> "$PADOGRID_WORKSPACE/etc/clusters.properties"
+else
+   setProperty "$PADOGRID_WORKSPACE/etc/clusters.properties" "clusters.group.names" "$GROUP_NAMES"
+fi
+echo "" >> "$PADOGRID_WORKSPACE/etc/clusters.properties"
+echo "# $GROUP - Enter comma separated cluster names" >> "$PADOGRID_WORKSPACE/etc/clusters.properties"
+echo "clusters.$GROUP.cluster.names=$CLUSTER_NAMES" >> "$PADOGRID_WORKSPACE/etc/clusters.properties"
