Overhauled pod mechanics to run without password and made Avahi optional

diff --git a/padogrid-deployment/src/main/resources/geode/bin_sh/create_cluster b/padogrid-deployment/src/main/resources/geode/bin_sh/create_cluster
--- a/padogrid-deployment/src/main/resources/geode/bin_sh/create_cluster
+++ b/padogrid-deployment/src/main/resources/geode/bin_sh/create_cluster
@@ -407,6 +407,7 @@ if [ "$VM_ENABLED" == "true" ]; then
       VM_HOSTS="$VM_HOSTS_ARG"
    fi
 
+   # Default locator host
    if [ "$LOCATOR" == "" ]; then
       # Extract the first host from the VM host list
       VM_LOCATOR_HOSTS=${VM_HOSTS%%,*}
@@ -494,7 +495,9 @@ if [ "$VM_ENABLED" == "true" ]; then
    MEMBER_1=`getMemberName 1`
    MEMBER_1_DIR=$CLUSTER_DIR/run/$MEMBER_1
    mkdir -p $MEMBER_1_DIR
-   POD_TYPE="local"
+   if [ "POD" == "local" ]; then
+      POD_TYPE="local"
+   fi
 elif [ "$POD" == "local" ]; then
    LOCATOR_1=`getLocatorName 1`
    LOCATOR_1_DIR=$CLUSTER_DIR/run/$LOCATOR_1
@@ -505,12 +508,22 @@ elif [ "$POD" == "local" ]; then
    MEMBER_2_DIR=$CLUSTER_DIR/run/$MEMBER_2
    mkdir -p $MEMBER_1_DIR
    mkdir -p $MEMBER_2_DIR
-   POD_TYPE="local"
-else 
+   POD_TYPE="local" 
+fi
+
+if [ "$POD" != "local" ]; then
+
+   VM_ENABLED="true"
+   AVAHI_ENABLED=`getPodProperty "pod.avahi.enabled" false`
+   NODE_COUNT=`getPodProperty "node.count" "0"`
+   VM_USER="vagrant"
+   POD_TYPE="vagrant"
+   VM_HOSTS=""
+   
    PRIMARY_NODE_NAME=`getPodProperty "node.name.primary" "$DEFAULT_NODE_NAME_PRIMARY"`
    PRIMARY_NODE_LOCAL="${PRIMARY_NODE_NAME}.local"
    BIND_ADDRESS=$PRIMARY_NODE_LOCAL
-   HOSTNAME_FOR_CLIENTS=$NPRIMARY_ODE_LOCAL
+   HOSTNAME_FOR_CLIENTS=$PRIMARY_NODE_LOCAL
 
    # Create locator run directory
    NODE_NAME_PREFIX=$PRIMARY_NODE_NAME
@@ -520,39 +533,78 @@ else
 
    # Create member run directories
    NODE_NAME_PREFIX=`getPodProperty "node.name.prefix" $NODE_NAME_PREFIX`
-   NODE_COUNT=`getPodProperty "node.count" "0"`
    for i in $(seq 1 $NODE_COUNT); do
        MEMBER=`getMemberName $i`
        MEMBER_DIR=$CLUSTER_DIR/run/$MEMBER
        mkdir -p $MEMBER_DIR
    done
-   POD_TYPE="vagrant"
-   NODE_NAME_PRIMARY=`getPodProperty "node.name.primary"`
-   if [ "$NODE_NAME_PRIMARY" != "" ]; then
-      NODE_NAME_PRIMARY=${NODE_NAME_PRIMARY}.local
-   else
-      NODE_NAME_PRIMARY="localhost"
-   fi
    
-   # Vagrant pod VMs
-   VM_ENABLED="true"
-   VM_HOSTS=""
-   for i in $(seq 1 $NODE_COUNT); do
-     __MEMBER_NUM=`getMemberNumWithLeadingZero $i`
-     NODE_LOCAL="${NODE_NAME_PREFIX}-${__MEMBER_NUM}.local"
-     if [ $i -eq 1 ]; then
-        VM_HOSTS="$NODE_LOCAL"
-     else
-        VM_HOSTS="$VM_HOSTS,$NODE_LOCAL"
-     fi
-   done
-   if [ "$LOCATOR_SPECIFIED" == "true" ]; then
-      VM_LOCATOR_HOSTS=$LOCATOR
+   # Vagrant pod VMs   
+   if [ "$AVAHI_ENABLED" == "true" ]; then
+      NODE_NAME_PRIMARY=`getPodProperty "node.name.primary"`
+      if [ "$NODE_NAME_PRIMARY" != "" ]; then
+         NODE_NAME_PRIMARY=${NODE_NAME_PRIMARY}.local
+      else
+         NODE_NAME_PRIMARY="localhost"
+      fi
+      for i in $(seq 1 $NODE_COUNT); do
+        __MEMBER_NUM=`getMemberNumWithLeadingZero $i`
+        NODE_LOCAL="${NODE_NAME_PREFIX}-${__MEMBER_NUM}.local"
+        if [ $i -eq 1 ]; then
+           VM_HOSTS="$NODE_LOCAL"
+        else
+           VM_HOSTS="$VM_HOSTS,$NODE_LOCAL"
+        fi
+      done
+      if [ "$LOCATOR_SPECIFIED" == "true" ]; then
+         VM_LOCATOR_HOSTS=$LOCATOR
+      else
+         # pnode
+         VM_LOCATOR_HOSTS=$PRIMARY_NODE_LOCAL
+      fi
    else
-      # pnode
-      VM_LOCATOR_HOSTS=$PRIMARY_NODE_LOCAL
+      POD_DIR="$PADOGRID_WORKSPACE/pods/$POD"
+      POD_SETENV="$POD_DIR/bin_sh/setenv.sh"
+      HOST_PRIVATE_IP=""
+      if [ -f "$POD_SETENV" ]; then
+         . $POD_SETENV
+      fi
+      if [ "$HOST_PRIVATE_IP" == "" ]; then
+         AVAILABLE_IP_ADDRESSES=`getPrivateNetworkAddresses`
+         if [ "$AVAILABLE_IP_ADDRESSES" == "" ]; then
+            echo >&2 "ERROR: Private IP address not specified and unable to determine. Please add"
+            echo >&2 "       a host-only ethernet adapter to VirtualBox. Command aborted."
+            exit 1
+         fi
+         # Pick the first one in the list
+         for i in $AVAILABLE_IP_ADDRESSES; do
+            HOST_PRIVATE_IP=$i
+            break;
+         done
+      fi
+      IP_LAST_OCTET=`getPodProperty "node.ip.lastOctet" $IP_LAST_OCTET`
+      # Extract the first three octets from the primary IP.
+      BASE_PRIVATE_IP_FIRST_THREE_OCTETS=${HOST_PRIVATE_IP%.*}
+      BASE_PRIVATE_IP_LAST_OCTET=$IP_LAST_OCTET
+      BASE_PRIVATE_IP=${BASE_PRIVATE_IP_FIRST_THREE_OCTETS}.${BASE_PRIVATE_IP_LAST_OCTET}
+      NODE_NAME_PRIMARY=${BASE_PRIVATE_IP}
+      for i in $(seq 1 $NODE_COUNT); do
+         let NODE_OCTET=i+BASE_PRIVATE_IP_LAST_OCTET
+         NODE_IP=${BASE_PRIVATE_IP_FIRST_THREE_OCTETS}.${NODE_OCTET}
+         if [ $i -eq 1 ]; then
+            VM_HOSTS="$NODE_IP"
+         else
+            VM_HOSTS="$VM_HOSTS,$NODE_IP"
+         fi
+      done   
+      if [ "$LOCATOR_SPECIFIED" == "true" ]; then
+         VM_LOCATOR_HOSTS=$LOCATOR
+      else
+         # pnode
+         VM_LOCATOR_HOSTS=$NODE_NAME_PRIMARY
+      fi
    fi
-   VM_USER="vagrant"
+
 fi
 
 # Write cluster files
@@ -666,11 +718,10 @@ else
    echo "      build_pod -pod $POD"
    echo "6. To get the pod details, run the following:"
    echo "      show_pod -pod $POD"
-   echo "7. Login to one of the nodes and start the cluster. For example, to login to the primary node:"
-   echo "      cd $POD_DIR"
-   echo "      vagrant ssh $NODE_NAME_PRIMARY"
-   echo "      password: vagrant"
-   echo "      start_cluster -pod $POD" 
-   echo "8. Execute 'show_cluster' to verify the cluster state."
+   echo "7. To use this pod, attach it to a cluster. For example,"
+   echo "      create_cluster -cluster mycluster -pod $POD"
+   echo "      start_cluster -cluster mycluster"
+   echo "8. You can login to the primary node as follows."
+   echo "      ssh vagrant@$NODE_NAME_PRIMARY"
 fi
 echo "----------------------------------------------------------------"
diff --git a/padogrid-deployment/src/main/resources/hazelcast/bin_sh/create_cluster b/padogrid-deployment/src/main/resources/hazelcast/bin_sh/create_cluster
--- a/padogrid-deployment/src/main/resources/hazelcast/bin_sh/create_cluster
+++ b/padogrid-deployment/src/main/resources/hazelcast/bin_sh/create_cluster
@@ -41,7 +41,8 @@ NAME
    $EXECUTABLE - Create a new cluster in the current padogrid workspace
 
 SYNOPSIS
-   $EXECUTABLE [-cluster cluster_name] [-pod pod_name]
+   $EXECUTABLE [-cluster cluster_name]
+               [-pod pod_name]
                [-vm [comma_separated_hosts]]
                [-mc management_center_host]
                [-port first_port_number] [-?]
@@ -80,6 +81,10 @@ OPTIONS
    -port first_port_number
              First member's port number. Port number is incremented
              starting from this port number for the subsquent members.
+             
+             This option applies only for a cluster running locally. It is ignored
+             for creating non-local pod and VM clusters.
+             
              Default: 5701 for IMDG, 6701 for Jet
 EOF
 if [ "$MAN_SPECIFIED" == "false" ]; then
@@ -579,7 +584,9 @@ if [ "$VM_ENABLED" == "true" ]; then
    MEMBER_1=`getMemberName 1`
    MEMBER_1_DIR=$CLUSTER_DIR/run/$MEMBER_1
    mkdir -p $MEMBER_1_DIR
-   POD_TYPE="local"
+   if [ "POD" == "local" ]; then
+      POD_TYPE="local"
+   fi
    MC_HOST=$VM_MC_HOSTS
 elif [ "$POD" == "local" ]; then
    MEMBER_1=`getMemberName 1`
@@ -590,36 +597,81 @@ elif [ "$POD" == "local" ]; then
    mkdir -p $MEMBER_2_DIR
    POD_TYPE="local"
    MC_HOST="localhost"
-else 
-   NODE_NAME_PREFIX=`getPodProperty "node.name.prefix" $NODE_NAME_PREFIX`
+fi
+
+if [ "$POD" != "local" ]; then
+
+   VM_ENABLED="true"
+   AVAHI_ENABLED=`getPodProperty "pod.avahi.enabled" false`
    NODE_COUNT=`getPodProperty "node.count" "0"`
+   VM_USER="vagrant"
+   POD_TYPE="vagrant"
+   VM_HOSTS=""
+   
+   NODE_NAME_PREFIX=`getPodProperty "node.name.prefix" $NODE_NAME_PREFIX`
    for i in $(seq 1 $NODE_COUNT); do
        MEMBER=`getMemberName $i`
        MEMBER_DIR=$CLUSTER_DIR/run/$MEMBER
        mkdir -p $MEMBER_DIR
    done
-   POD_TYPE="vagrant"
-   NODE_NAME_PRIMARY=`getPodProperty "node.name.primary"`
-   if [ "$NODE_NAME_PRIMARY" != "" ]; then
-      NODE_NAME_PRIMARY=${NODE_NAME_PRIMARY}.local
-   else
-      NODE_NAME_PRIMARY="localhost"
-   fi
-   MC_HOST=$NODE_NAME_PRIMARY
-
+   
    # Vagrant pod VMs
-   VM_ENABLED="true"
-   VM_HOSTS=""
-   for i in $(seq 1 $NODE_COUNT); do
-     __MEMBER_NUM=`getMemberNumWithLeadingZero $i`
-     NODE_LOCAL="${NODE_NAME_PREFIX}-${__MEMBER_NUM}.local"
-     if [ $i -eq 1 ]; then
-        VM_HOSTS="$NODE_LOCAL"
-     else
-        VM_HOSTS="$VM_HOSTS,$NODE_LOCAL"
-     fi
-   done
-   VM_USER="vagrant"
+   if [ "$AVAHI_ENABLED" == "true" ]; then
+      NODE_NAME_PRIMARY=`getPodProperty "node.name.primary"`
+      if [ "$NODE_NAME_PRIMARY" != "" ]; then
+         NODE_NAME_PRIMARY=${NODE_NAME_PRIMARY}.local
+      else
+         NODE_NAME_PRIMARY="localhost"
+      fi
+      MC_HOST=$NODE_NAME_PRIMARY
+
+      for i in $(seq 1 $NODE_COUNT); do
+        __MEMBER_NUM=`getMemberNumWithLeadingZero $i`
+        NODE_LOCAL="${NODE_NAME_PREFIX}-${__MEMBER_NUM}.local"
+        if [ $i -eq 1 ]; then
+           VM_HOSTS="$NODE_LOCAL"
+        else
+           VM_HOSTS="$VM_HOSTS,$NODE_LOCAL"
+        fi
+      done
+   else
+      POD_DIR="$PADOGRID_WORKSPACE/pods/$POD"
+      POD_SETENV="$POD_DIR/bin_sh/setenv.sh"
+      HOST_PRIVATE_IP=""
+      if [ -f "$POD_SETENV" ]; then
+         . $POD_SETENV
+      fi
+      if [ "$HOST_PRIVATE_IP" == "" ]; then
+         AVAILABLE_IP_ADDRESSES=`getPrivateNetworkAddresses`
+         if [ "$AVAILABLE_IP_ADDRESSES" == "" ]; then
+            echo >&2 "ERROR: Private IP address not specified and unable to determine. Please add"
+            echo >&2 "       a host-only ethernet adapter to VirtualBox. Command aborted."
+            exit 1
+         fi
+         # Pick the first one in the list
+         for i in $AVAILABLE_IP_ADDRESSES; do
+            HOST_PRIVATE_IP=$i
+            break;
+         done
+      fi
+      IP_LAST_OCTET=`getPodProperty "node.ip.lastOctet" $IP_LAST_OCTET`
+      # Extract the first three octets from the primary IP.
+      BASE_PRIVATE_IP_FIRST_THREE_OCTETS=${HOST_PRIVATE_IP%.*}
+      BASE_PRIVATE_IP_LAST_OCTET=$IP_LAST_OCTET
+      BASE_PRIVATE_IP=${BASE_PRIVATE_IP_FIRST_THREE_OCTETS}.${BASE_PRIVATE_IP_LAST_OCTET}
+      NODE_NAME_PRIMARY=${BASE_PRIVATE_IP}
+      MC_HOST=$NODE_NAME_PRIMARY
+      for i in $(seq 1 $NODE_COUNT); do
+         let NODE_OCTET=i+BASE_PRIVATE_IP_LAST_OCTET
+         NODE_IP=${BASE_PRIVATE_IP_FIRST_THREE_OCTETS}.${NODE_OCTET}
+         if [ $i -eq 1 ]; then
+            VM_HOSTS="$NODE_IP"
+         else
+            VM_HOSTS="$VM_HOSTS,$NODE_IP"
+         fi
+      done
+   fi
+
 fi
 
 writeCluster
@@ -727,11 +779,10 @@ else
    echo "      build_pod -pod $POD"
    echo "6. To get the pod details, run the following:"
    echo "      show_pod -pod $POD"
-   echo "7. Login to one of the nodes and start the cluster. For example, to login to the primary node:"
-   echo "      cd $POD_DIR"
-   echo "      vagrant ssh $NODE_NAME_PRIMARY"
-   echo "      password: vagrant"
-   echo "      start_cluster -pod $POD" 
-   echo "8. Execute 'show_cluster' to verify the cluster state."
+   echo "7. To use this pod, attach it to a cluster. For example,"
+   echo "      create_cluster -cluster mycluster -pod $POD"
+   echo "      start_cluster -cluster mycluster"
+   echo "8. You can login to the primary node as follows."
+   echo "      ssh vagrant@$NODE_NAME_PRIMARY"
 fi
 echo "----------------------------------------------------------------"
diff --git a/padogrid-deployment/src/main/resources/snappydata/bin_sh/create_cluster b/padogrid-deployment/src/main/resources/snappydata/bin_sh/create_cluster
--- a/padogrid-deployment/src/main/resources/snappydata/bin_sh/create_cluster
+++ b/padogrid-deployment/src/main/resources/snappydata/bin_sh/create_cluster
@@ -41,7 +41,8 @@ NAME
    $EXECUTABLE - Create a new cluster in the current padogrid workspace
 
 SYNOPSIS
-   $EXECUTABLE [-cluster cluster_name] [-pod pod_name]
+   $EXECUTABLE [-cluster cluster_name]
+               [-pod pod_name]
                [-vm [comma_separated_hosts]]
                [-locator comma_separated_locator_hosts]
                [-port first_locator_port_number] [-?]
@@ -67,12 +68,18 @@ OPTIONS
              specified, then the host list defined by VM_HOSTS in the workspace
              'setenv.sh' file is applied.
 
+             If the '-pod' option is specified then this option is suppressed.
+
    -locator comma_separated_locator_hosts
              A list of locator hosts or addresses separated by comma. If the list
              contains spaces then enclosed it in quotes. This option is meaningful
-             only if the '-vm' option is specified. If this option is not specified
-             but the '-vm' option is specified, then the first host from the '-vm'
-             host list is selected for the locator.
+             only if the '-vm' option is specified. 
+
+             If this option is not specified and the '-pod' option is specified then
+             the primary node is used for the locator.
+
+             If this option is not specified but the '-vm' option is specified, then
+             the first host from the '-vm' host list is selected for the locator.
 
    -port first_locator_port_number
              First locator's port number. Port number is incremented
@@ -84,13 +91,17 @@ OPTIONS
              is added to the member's default port number of $DEFAULT_MEMBER_START_PORT
              to obtain the port number 40406 for the member's first port number.
              Similarly, the JMX Manager's first HTTP port number would be 7072 ($DEFAULT_JMX_MANAGER_HTTP_START_PORT+2).
+
+             This option applies only for a cluster running locally. It is ignored
+             for creating non-local pod and VM clusters.
+
              Default: $DEFAULT_LOCATOR_START_PORT 
 
 EOF
 if [ "$MAN_SPECIFIED" == "false" ]; then
 cat <<EOF
 DEFAULT
-   $EXECUTABLE -cluster $CLUSTER -pod $POD -port $DEFAULT_MEMBER_START_PORT
+   $EXECUTABLE -cluster $CLUSTER -pod $POD -port $DEFAULT_LOCATOR_START_PORT
 
 FILES
    $PADOGRID_WORKSPACE/setenv.sh
@@ -123,9 +134,10 @@ if [ -d $CLUSTER_DIR ]; then
    exit 1
 fi
 
-if [ "$VM_SPECIFIED" == "true" ]; then
-   POD="local"
-fi
+# Suppress pod if VM specified
+#if [ "$VM_SPECIFIED" == "true" ]; then
+#   POD="local"
+#fi
 
 if [ "`isPodExist $POD`" == "false" ]; then
    echo >&2 "----------------------------------------------------------------"
@@ -331,7 +343,6 @@ function writeCluster()
    echo "" >> $ETC_DIR/cluster.properties
 
    if [ "$VM_ENABLED" == "true" ]; then
-      echo "# Individual VM host settings: vm.<host>.*" >> $ETC_DIR/cluster.properties
       __VM_HOSTS=$(echo "$VM_HOSTS" | sed "s/,/ /g")
       for VM_HOST in $__VM_HOSTS; do
          echo "#vm.${VM_HOST}.bindAddress=${VM_HOST}" >> $ETC_DIR/cluster.properties
@@ -344,7 +355,7 @@ function writeCluster()
 # 
 # VM cluster
 #
-if [ $"VM_SPECIFIED" == "true" ]; then
+if [ "$VM_SPECIFIED" == "true" ] && [ "$POD" == "local" ]; then
    VM_ENABLED="true"
 fi
 if [ "$VM_USER" == "" ]; then
@@ -470,7 +481,9 @@ if [ "$VM_ENABLED" == "true" ]; then
    MEMBER_1=`getMemberName 1`
    MEMBER_1_DIR=$CLUSTER_DIR/run/$MEMBER_1
    mkdir -p $MEMBER_1_DIR
-   POD_TYPE="local"
+   if [ "POD" == "local" ]; then
+      POD_TYPE="local"
+   fi
 elif [ "$POD" == "local" ]; then
    LOCATOR_1=`getLocatorName 1`
    LOCATOR_1_DIR=$CLUSTER_DIR/run/$LOCATOR_1
@@ -485,11 +498,21 @@ elif [ "$POD" == "local" ]; then
    mkdir -p $MEMBER_1_DIR
    mkdir -p $MEMBER_2_DIR
    POD_TYPE="local"
-else 
+fi
+
+if [ "$POD" != "local" ]; then
+
+   VM_ENABLED="true"
+   AVAHI_ENABLED=`getPodProperty "pod.avahi.enabled" false`
+   NODE_COUNT=`getPodProperty "node.count" "0"`
+   VM_USER="vagrant"
+   POD_TYPE="vagrant"
+   VM_HOSTS=""
+
    PRIMARY_NODE_NAME=`getPodProperty "node.name.primary" "$DEFAULT_NODE_NAME_PRIMARY"`
    PRIMARY_NODE_LOCAL="${PRIMARY_NODE_NAME}.local"
    BIND_ADDRESS=$PRIMARY_NODE_LOCAL
-   HOSTNAME_FOR_CLIENTS=$NPRIMARY_ODE_LOCAL
+   HOSTNAME_FOR_CLIENTS=$PRIMARY_NODE_LOCAL
 
    # Create locator run directory
    NODE_NAME_PREFIX=$PRIMARY_NODE_NAME
@@ -497,45 +520,89 @@ else
    LOCATOR_1_DIR=$CLUSTER_DIR/run/$LOCATOR_1
    mkdir -p $LOCATOR_1_DIR
 
-   # Create leader run directories
-   NODE_NAME_PREFIX=`getPodProperty "node.name.prefix" $NODE_NAME_PREFIX`
-   NODE_COUNT=`getPodProperty "node.count" "0"`
-   for i in $(seq 1 $NODE_COUNT); do
-       LEADER=`getLeaderName $i`
-       LEADER_DIR=$CLUSTER_DIR/run/$LEADER
-       mkdir -p $LEADER_DIR
-   done
+   # Create leader run directories (Primary and Leader share the same pnode)
+   LEADER_1=`getLeaderName 1`
+   LEADER_1_DIR=$CLUSTER_DIR/run/$LEADER_1
+   mkdir -p $LEADER_1_DIR
 
    # Create member run directories
    NODE_NAME_PREFIX=`getPodProperty "node.name.prefix" $NODE_NAME_PREFIX`
-   NODE_COUNT=`getPodProperty "node.count" "0"`
    for i in $(seq 1 $NODE_COUNT); do
        MEMBER=`getMemberName $i`
        MEMBER_DIR=$CLUSTER_DIR/run/$MEMBER
        mkdir -p $MEMBER_DIR
    done
 
-   POD_TYPE="vagrant"
-   NODE_NAME_PRIMARY=`getPodProperty "node.name.primary"`
-   if [ "$NODE_NAME_PRIMARY" != "" ]; then
-      NODE_NAME_PRIMARY=${NODE_NAME_PRIMARY}.local
-   else
-      NODE_NAME_PRIMARY="localhost"
-   fi
-   
    # Vagrant pod VMs
-   VM_ENABLED="true"
-   VM_HOSTS=""
-   for i in $(seq 1 $NODE_COUNT); do
-     __MEMBER_NUM=`getMemberNumWithLeadingZero $i`
-     NODE_LOCAL="${NODE_NAME_PREFIX}-${__MEMBER_NUM}.local"
-     if [ $i -eq 1 ]; then
-        VM_HOSTS="$NODE_LOCAL"
-     else
-        VM_HOSTS="$VM_HOSTS,$NODE_LOCAL"
-     fi
-   done
-   VM_USER="vagrant"
+   if [ "$AVAHI_ENABLED" == "true" ]; then 
+      NODE_NAME_PRIMARY=`getPodProperty "node.name.primary"`
+      if [ "$NODE_NAME_PRIMARY" != "" ]; then
+         NODE_NAME_PRIMARY=${NODE_NAME_PRIMARY}.local
+      else
+         NODE_NAME_PRIMARY="localhost"
+      fi
+
+      for i in $(seq 1 $NODE_COUNT); do
+        __MEMBER_NUM=`getMemberNumWithLeadingZero $i`
+        NODE_LOCAL="${NODE_NAME_PREFIX}-${__MEMBER_NUM}.local"
+        if [ $i -eq 1 ]; then
+           VM_HOSTS="$NODE_LOCAL"
+        else
+           VM_HOSTS="$VM_HOSTS,$NODE_LOCAL"
+        fi
+      done
+      if [ "$LOCATOR_SPECIFIED" == "true" ]; then
+         VM_LOCATOR_HOSTS=$LOCATOR
+         VM_LEADER_HOSTS=$LOCATOR
+      else
+         # pnode
+         VM_LOCATOR_HOSTS=$PRIMARY_NODE_LOCAL
+         VM_LEADER_HOSTS=$PRIMARY_NODE_LOCAL
+      fi
+   else
+      POD_DIR="$PADOGRID_WORKSPACE/pods/$POD"
+      POD_SETENV="$POD_DIR/bin_sh/setenv.sh"
+      HOST_PRIVATE_IP=""
+      if [ -f "$POD_SETENV" ]; then
+         . $POD_SETENV
+      fi
+      if [ "$HOST_PRIVATE_IP" == "" ]; then
+         AVAILABLE_IP_ADDRESSES=`getPrivateNetworkAddresses`
+         if [ "$AVAILABLE_IP_ADDRESSES" == "" ]; then
+            echo >&2 "ERROR: Private IP address not specified and unable to determine. Please add"
+            echo >&2 "       a host-only ethernet adapter to VirtualBox. Command aborted."
+            exit 1
+         fi
+         # Pick the first one in the list
+         for i in $AVAILABLE_IP_ADDRESSES; do
+            HOST_PRIVATE_IP=$i
+            break;
+         done
+      fi
+      IP_LAST_OCTET=`getPodProperty "node.ip.lastOctet" $IP_LAST_OCTET`
+      # Extract the first three octets from the primary IP.
+      BASE_PRIVATE_IP_FIRST_THREE_OCTETS=${HOST_PRIVATE_IP%.*}
+      BASE_PRIVATE_IP_LAST_OCTET=$IP_LAST_OCTET
+      BASE_PRIVATE_IP=${BASE_PRIVATE_IP_FIRST_THREE_OCTETS}.${BASE_PRIVATE_IP_LAST_OCTET}
+      NODE_NAME_PRIMARY=${BASE_PRIVATE_IP}
+      for i in $(seq 1 $NODE_COUNT); do
+         let NODE_OCTET=i+BASE_PRIVATE_IP_LAST_OCTET
+         NODE_IP=${BASE_PRIVATE_IP_FIRST_THREE_OCTETS}.${NODE_OCTET}
+         if [ $i -eq 1 ]; then
+            VM_HOSTS="$NODE_IP"
+         else
+            VM_HOSTS="$VM_HOSTS,$NODE_IP"
+         fi
+      done
+      if [ "$LOCATOR_SPECIFIED" == "true" ]; then
+         VM_LOCATOR_HOSTS=$LOCATOR
+         VM_LEADER_HOSTS=$LOCATOR
+      else
+         # pnode
+         VM_LOCATOR_HOSTS=$NODE_NAME_PRIMARY
+         VM_LEADER_HOSTS=$NODE_NAME_PRIMARY
+      fi
+   fi
 fi
 
 # Write cluster files
@@ -571,7 +638,7 @@ echo ""
 echo "The default config.xml file has been placed in the CONFIG_DIR directory."
 echo "Modify it or replace it with the appropriate file."
 echo ""
-if [ "$VM_ENABLED" == "true" ]; then
+if [ "$VM_ENABLED" == "true" ] && [ "$POD" == "local" ]; then
    echo "One (1) member has been configured (added) to run in this cluster as follows:"
    echo ""
    echo "      Member: $MEMBER_1"
@@ -592,11 +659,34 @@ elif [ "$POD" == "local" ]; then
 else
    echo "$NODE_COUNT members have been configured (added) to run in this cluster as follows:"
    echo ""
+   NUM=0
+   NODE_NAME_PREFIX=$PRIMARY_NODE_NAME
+   VM_LOCATOR_HOSTS=$(echo "$VM_LOCATOR_HOSTS" | sed "s/,/ /g")
+   for i in $VM_LOCATOR_HOSTS; do
+       let NUM=NUM+1
+       NODE_NAME_PREFIX=$i
+       LOCATOR=`getLocatorName $NUM`
+       LOCATOR_DIR=$CLUSTER_DIR/run/$LOCATOR
+       echo "     Locator: $LOCATOR"
+       echo " Working Dir: $LOCATOR_DIR"
+   done
+   NUM=0
+   NODE_NAME_PREFIX=$PRIMARY_NODE_NAME
+   VM_LEADER_HOSTS=$(echo "$VM_LEADER_HOSTS" | sed "s/,/ /g")
+   for i in $VM_LEADER_HOSTS; do
+       let NUM=NUM+1
+       NODE_NAME_PREFIX=$i
+       LEADER=`getLeaderName $NUM`
+       LEADER_DIR=$CLUSTER_DIR/run/$LEADER
+       echo "      Leader: $LEADER"
+       echo " Working Dir: $LEADER_DIR"
+   done
+   NODE_NAME_PREFIX=`getPodProperty "node.name.prefix" $NODE_NAME_PREFIX`
    for i in $(seq 1 $NODE_COUNT); do
        MEMBER=`getMemberName $i`
        MEMBER_DIR=$CLUSTER_DIR/run/$MEMBER
       echo "      Member: $MEMBER"
-      echo " Working Dir: $MEMBER"
+      echo " Working Dir: $MEMBER_DIR"
    done
    echo ""
 fi
@@ -643,11 +733,10 @@ else
    echo "      build_pod -pod $POD"
    echo "6. To get the pod details, run the following:"
    echo "      show_pod -pod $POD"
-   echo "7. Login to one of the nodes and start the cluster. For example, to login to the primary node:"
-   echo "      cd $POD_DIR"
-   echo "      vagrant ssh $NODE_NAME_PRIMARY"
-   echo "      password: vagrant"
-   echo "      start_cluster -pod $POD" 
-   echo "8. Execute 'show_cluster' to verify the cluster state."
+   echo "7. To use this pod, attach it to a cluster. For example,"
+   echo "      create_cluster -cluster mycluster -pod $POD"
+   echo "      start_cluster -cluster mycluster"
+   echo "8. You can login to the primary node as follows."
+   echo "      ssh vagrant@$NODE_NAME_PRIMARY"
 fi
 echo "----------------------------------------------------------------"
diff --git a/padogrid-deployment/src/main/resources/snappydata/bin_sh/start_leader b/padogrid-deployment/src/main/resources/snappydata/bin_sh/start_leader
--- a/padogrid-deployment/src/main/resources/snappydata/bin_sh/start_leader
+++ b/padogrid-deployment/src/main/resources/snappydata/bin_sh/start_leader
@@ -78,6 +78,7 @@ fi
 
 # Get workspace name
 WORKSPACE=${PADOGRID_WORKSPACE##*/}
+POD=`getClusterProperty "pod.name" "local"`
 
 # Set FG_OPT
 if [ "$SIMULATE" == "true" ]; then
@@ -104,8 +105,8 @@ fi
 if [ "$REMOTE_SPECIFIED" == "false" ]; then
    VM_ENABLED=`getClusterProperty "vm.enabled" "false"`
    if [ "$VM_ENABLED" == "true" ]; then
-      VM_LOCATOR_HOSTS=$(getClusterProperty "vm.locator.hosts")
-      if [ "$VM_LOCATOR_HOSTS" == "" ]; then
+      VM_LEADER_HOSTS=$(getClusterProperty "vm.leader.hosts")
+      if [ "$VM_LEADER_HOSTS" == "" ]; then
          echo >&2 "----------------------------------------------------------------"
          echo >&2 "WORKSPACE: $PADOGRID_WORKSPACE"
          echo >&2 "    ERROR: VM locator hosts undefined. Set 'vm.locator.hosts' in the following cluster.properties file."  
@@ -124,35 +125,31 @@ if [ "$REMOTE_SPECIFIED" == "false" ]; then
          echo >&2 "----------------------------------------------------------------"
          exit 1
       fi
-      LOCATOR_START_PORT=`getClusterProperty "locator.tcp.startPort" $DEFAULT_LOCATOR_START_PORT`
+      LEADER_START_PORT=`getClusterProperty "locator.tcp.startPort" $DEFAULT_LEADER_START_PORT`
       # Replace , with space
-      __VM_LOCATOR_HOSTS=$(echo "$VM_LOCATOR_HOSTS" | sed "s/,/ /g")
-      for VM_HOST in $__VM_LOCATOR_HOSTS; do
-         if [ "$LOCATOR_TCP_LIST" == "" ]; then
-            LOCATOR_TCP_LIST="$VM_HOST:$LOCATOR_START_PORT"
+      __VM_LEADER_HOSTS=$(echo "$VM_LEADER_HOSTS" | sed "s/,/ /g")
+      for VM_HOST in $__VM_LEADER_HOSTS; do
+         if [ "$LEADER_TCP_LIST" == "" ]; then
+            LEADER_TCP_LIST="$VM_HOST:$LEADER_START_PORT"
          else
-            LOCATOR_TCP_LIST="$LOCATOR_TCP_LIST,$VM_HOST:$LOCATOR_START_PORT"
+            LEADER_TCP_LIST="$LEADER_TCP_LIST,$VM_HOST:$LEADER_START_PORT"
          fi
       done
-
-      # Replace , with space
-      __VM_HOSTS=$(echo "$VM_HOSTS" | sed "s/,/ /g")
-      DEFAULT_USER=$(whoami)
-      VM_USER=`getClusterProperty "vm.user" "$DEFAULT_USER"`
-      VM_KEY=`getClusterProperty "vm.privateKeyFile"`
-      if [ "$VM_KEY" != "" ]; then 
-         VM_KEY="-i $VM_KEY"
-      fi
 
       # Determine the host
       __MEMBER_NUMBER=0
       __FOUND="false"
       
-      for VM_HOST in $__VM_HOSTS; do
+      for VM_HOST in $__VM_LEADER_HOSTS; do
          let __MEMBER_NUMBER=__MEMBER_NUMBER+1
          if [ $__MEMBER_NUMBER -eq $MEMBER_NUM_NO_LEADING_ZERO ]; then
             __FOUND="true"
-            ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "$COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/start_leader $FG_OPT $SIMULATE_OPT $CREATE_SCRIPT_OPT -cluster $CLUSTER -remote $VM_HOST -workspace $VM_PADOGRID_WORKSPACE -num 1"
+            if [ "$POD" == "local" ]; then
+               NUM=1
+            else
+               let NUM=__MEMBER_NUMBER
+            fi
+            ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "$COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/start_leader $FG_OPT $SIMULATE_OPT $CREATE_SCRIPT_OPT -cluster $CLUSTER -remote $VM_HOST -workspace $VM_PADOGRID_WORKSPACE -num $NUM"
             break;
          fi
       done
@@ -168,9 +165,10 @@ fi
 #
 # Local cluster
 #
-POD=`getClusterProperty "pod.name" "local"`
-NODE_NAME_PREFIX=`getPodProperty "node.name.prefix" $NODE_NAME_PREFIX`
 
+# Primary node for leader (and locator)
+PRIMARY_NODE_NAME=`getPodProperty "node.name.primary" "$DEFAULT_NODE_NAME_PRIMARY"`
+NODE_NAME_PREFIX=$PRIMARY_NODE_NAME
 MEMBER_NUMBER=$MEMBER_NUM_NO_LEADING_ZERO
 MEMBER=`getLeaderName $MEMBER_NUMBER`
 MEMBER_DIR=$RUN_DIR/$MEMBER
@@ -241,6 +239,16 @@ if [ "$VM_ENABLED" == "true" ]; then
       echo >&2 "----------------------------------------------------------------"
       exit 1
    fi
+   VM_LEADER_HOSTS=$(getClusterProperty "vm.leader.hosts")
+   if [ "$VM_LEADER_HOSTS" == "" ]; then
+      echo >&2 "----------------------------------------------------------------"
+      echo >&2 "WORKSPACE: $PADOGRID_WORKSPACE"
+      echo >&2 "    ERROR: VM leader hosts undefined. Set 'vm.leader.hosts' in the following cluster.properties file."  
+      echo >&2 "           $ETC_DIR/cluster.properties"
+      echo >&2 "           Command aborted."
+      echo >&2 "----------------------------------------------------------------"
+      exit 1
+   fi
    VM_HOSTS=`getClusterProperty "vm.hosts"`
    if [ "$VM_HOSTS" == "" ]; then
       echo >&2 "----------------------------------------------------------------"
@@ -260,6 +268,15 @@ if [ "$VM_ENABLED" == "true" ]; then
          LOCATOR_TCP_LIST="$BIND_ADDRESS:$LOCATOR_START_PORT"
       else
          LOCATOR_TCP_LIST="$LOCATOR_TCP_LIST,$BIND_ADDRESS:$LOCATOR_START_PORT"
+      fi
+   done
+   __LEADER_HOSTS=$(echo "$VM_LEADER_HOSTS" | sed "s/,/ /g")
+   for VM_HOST in $__LEADER_HOSTS; do
+      BIND_ADDRESS=`getClusterProperty "vm.${VM_HOST}.bindAddress" "$VM_HOST"`
+      if [ "$LEADER_TCP_LIST" == "" ]; then
+         LEADER_TCP_LIST="$BIND_ADDRESS:$LEADER_START_PORT"
+      else
+         LEADER_TCP_LIST="$LEADER_TCP_LIST,$BIND_ADDRESS:$LEADER_START_PORT"
       fi
    done
    VM_HOST=$REMOTE
@@ -299,9 +316,9 @@ elif [ "$POD" == "local" ]; then
 else
 
    PRIMARY_NODE_NAME=`getPodProperty "node.name.primary" "$DEFAULT_NODE_NAME_PRIMARY"`
-   LOCATOR_COUNT=`getLocatorCount`
+   LEADER_COUNT=`getLeaderCount`
    PRIMARY_NODE_LOCAL="${PRIMARY_NODE_NAME}.local"
-   LOCATOR_TCP_LIST="$PRIMARY_NODE_LOCAL:$LOCATOR_START_PORT"
+   LEADER_TCP_LIST="$PRIMARY_NODE_LOCAL:$LEADER_START_PORT"
 
    NODE_LOCAL="${NODE_NAME_PREFIX}-${MEMBER_NUM}.local"
    BIND_ADDRESS=$NODE_LOCAL
@@ -413,12 +430,12 @@ SNAPPY_OPTS="-dir=$MEMBER_DIR \
       -spark.ui.port=$SPARK_UI_PORT \
       -log-file=$LOG_FILE \
       -statistic-archive-file=$STATS_FILE"
-#if [ "$BIND_ADDRESS" != "" ]; then
-#   SNAPPY_OPTS="$SNAPPY_OPTS -bind-address=$BIND_ADDRESS"
-#fi
-#if [ "$HOSTNAME_FOR_CLIENTS" != "" ]; then
-#   SNAPPY_OPTS="$SNAPPY_OPTS -hostname-for-clients=$HOSTNAME_FOR_CLIENTS"
-#fi
+if [ "$BIND_ADDRESS" != "" ]; then
+   SNAPPY_OPTS="$SNAPPY_OPTS -bind-address=$BIND_ADDRESS"
+fi
+if [ "$HOSTNAME_FOR_CLIENTS" != "" ]; then
+   SNAPPY_OPTS="$SNAPPY_OPTS -hostname-for-clients=$HOSTNAME_FOR_CLIENTS"
+fi
 if [ "$LEAD_OPTS" != "" ]; then
    SNAPPY_OPTS=$(removeEqualToOpts "$LEAD_OPTS" "$SNAPPY_OPTS")
    SNAPPY_OPTS="$SNAPPY_OPTS $LEAD_OPTS"
@@ -447,7 +464,6 @@ export JAVA_OPTS
 export CLASSPATH
 export JAVA
 
-POD=`getClusterProperty "pod.name" $POD`
 if [ "$POD" != "local" ] && [ "$REMOTE_SPECIFIED" == "false" ]; then
    NODE_NAME_PREFIX=`getPodProperty "node.name.prefix" $NODE_NAME_PREFIX`
    NODE_LOCAL="${NODE_NAME_PREFIX}-${MEMBER_NUM}.local"
