Added preliminary support for Hadoop

diff --git a/padogrid-deployment/src/main/resources/geode/bin_sh/show_log b/padogrid-deployment/src/main/resources/geode/bin_sh/show_log
--- a/padogrid-deployment/src/main/resources/geode/bin_sh/show_log
+++ b/padogrid-deployment/src/main/resources/geode/bin_sh/show_log
@@ -88,7 +88,7 @@ fi
 fi
 
 if [ "$ALL" == "true" ] && [ "$FULL" == "true" ]; then 
-   echo >&2 "${CLightRed}ERROR:${CNone} '-all' and '-full' cannot be specified together. Command aborted ."
+   echo >&2 -e "${CLightRed}ERROR:${CNone} '-all' and '-full' cannot be specified together. Command aborted ."
    exit 1
 fi
 # -num overrides -all
