Changed GemFire Prometheus default settings to 10.1

diff --git a/padogrid-deployment/src/main/resources/geode/bin_sh/start_locator b/padogrid-deployment/src/main/resources/geode/bin_sh/start_locator
--- a/padogrid-deployment/src/main/resources/geode/bin_sh/start_locator
+++ b/padogrid-deployment/src/main/resources/geode/bin_sh/start_locator
@@ -399,7 +399,7 @@ fi
 # Set PROMETHEUS paths
 LOCATOR_PROMETHEUS_ENABLED=`getClusterProperty "locator.prometheus.enabled" $DEFAULT_LOCATOR_PROMETHEUS_ENABLED`
 if [ "$LOCATOR_PROMETHEUS_ENABLED" == "true" ]; then
-   LOCATOR_PROMETHEUS_GEMFIRE_ENABLED=`getClusterProperty "locator.prometheus.gemfire.enabled" $DEFAULT_PROMETHEUS_GEMFIRE_ENABLED`
+   LOCATOR_PROMETHEUS_GEMFIRE_ENABLED=`getClusterProperty "locator.prometheus.gemfire.enabled" $DEFAULT_LOCATOR_PROMETHEUS_GEMFIRE_ENABLED`
    LOCATOR_PROMETHEUS_START_PORT=`getClusterProperty "locator.prometheus.startPort" $DEFAULT_LOCATOR_PROMETHEUS_START_PORT`
    if [ "$POD" == "local" ]; then
       let PROMETHEUS_PORT=LOCATOR_PROMETHEUS_START_PORT+LOCATOR_NUMBER-1
@@ -416,18 +416,22 @@ if [ "$LOCATOR_PROMETHEUS_ENABLED" == "true" ]; then
       PROMETHEUS_CONFIG_FILE_PATH=${PROMETHEUS_CONFIG_FILE_PATH:2}
    fi
    if [ "$LOCATOR_PROMETHEUS_GEMFIRE_ENABLED" == "true" ]; then
-      PROMETHEUS_METRICS_EMISSION=`getClusterProperty "prometheus.metrics.emission" $DEFAULT_PROMETHEUS_METRICS_EMISSION`
-      if [ "$PROMETHEUS_METRICS_EMISSION" != "Default" ] && [ "$PROMETHEUS_METRICS_EMISSION" != "All" ] && [ "$PROMETHEUS_METRICS_EMISSION" != "None" ]; then
-         echo >&2 "----------------------------------------------------------------"
-         echo >&2 "WORKSPACE: $PADOGRID_WORKSPACE"
-         echo >&2 -e "    ${CError}ERROR:${CNone} Invalid value: prometheus.metrics.emission=$PROMETHEUS_METRICS_EMISSION. Valid values are Default, All, or None."
-         echo >&2 "           Set 'prometheus.metrics.emission' in the following cluster.properties file."  
-         echo >&2 "           $ETC_DIR/cluster.properties"
-         echo >&2 "           Command aborted."
-         echo >&2 "----------------------------------------------------------------"
-         exit 1
+      if [ $PRODUCT_MAJOR_VERSION -ge 10 ] && [ $PRODUCT_MINOR_VERSION -ge 1 ]; then
+         PROMETHEUS_METRICS_EMISSION=`getClusterProperty "locator.prometheus.metrics.emission" $DEFAULT_PROMETHEUS_METRICS_EMISSION`
+         if [ "$PROMETHEUS_METRICS_EMISSION" != "Default" ] && [ "$PROMETHEUS_METRICS_EMISSION" != "All" ] && [ "$PROMETHEUS_METRICS_EMISSION" != "None" ]; then
+            echo >&2 "----------------------------------------------------------------"
+            echo >&2 "WORKSPACE: $PADOGRID_WORKSPACE"
+            echo >&2 -e "    ${CError}ERROR:${CNone} Invalid value: locator.prometheus.metrics.emission=$PROMETHEUS_METRICS_EMISSION. Valid values are Default, All, or None."
+            echo >&2 "           Set 'prometheus.metrics.emission' in the following cluster.properties file."  
+            echo >&2 "           $ETC_DIR/cluster.properties"
+            echo >&2 "           Command aborted."
+            echo >&2 "----------------------------------------------------------------"
+            exit 1
+         fi
+         JAVA_OPTS="$JAVA_OPTS --J=-Dgemfire.prometheus.metrics.emission=$PROMETHEUS_METRICS_EMISSION --J=-Dgemfire.prometheus.metrics.port=$PROMETHEUS_PORT"
+      else
+         JAVA_OPTS="$JAVA_OPTS --J=-javaagent:$PROMETHEUS_JAR_PATH=$PROMETHEUS_PORT:$PROMETHEUS_CONFIG_FILE_PATH"
       fi
-      JAVA_OPTS="$JAVA_OPTS --J=-Dgemfire.prometheus.metrics.emission=$PROMETHEUS_METRICS_EMISSION --J=-Dgemfire.prometheus.metrics.port=$PROMETHEUS_PORT"
    else
       JAVA_OPTS="$JAVA_OPTS --J=-javaagent:$PROMETHEUS_JAR_PATH=$PROMETHEUS_PORT:$PROMETHEUS_CONFIG_FILE_PATH"
    fi
diff --git a/padogrid-deployment/src/main/resources/geode/bin_sh/start_member b/padogrid-deployment/src/main/resources/geode/bin_sh/start_member
--- a/padogrid-deployment/src/main/resources/geode/bin_sh/start_member
+++ b/padogrid-deployment/src/main/resources/geode/bin_sh/start_member
@@ -449,19 +449,24 @@ if [ "$PROMETHEUS_ENABLED" == "true" ]; then
       # Remove the disk drive letter from the path. A workaround to a bug in the prometheus exporter.
       PROMETHEUS_CONFIG_FILE_PATH=${PROMETHEUS_CONFIG_FILE_PATH:2}
    fi
+
    if [ "$PROMETHEUS_GEMFIRE_ENABLED" == "true" ]; then
-      PROMETHEUS_METRICS_EMISSION=`getClusterProperty "prometheus.metrics.emission" $DEFAULT_PROMETHEUS_METRICS_EMISSION`
-      if [ "$PROMETHEUS_METRICS_EMISSION" != "Default" ] && [ "$PROMETHEUS_METRICS_EMISSION" != "All" ] && [ "$PROMETHEUS_METRICS_EMISSION" != "None" ]; then
-         echo >&2 "----------------------------------------------------------------"
-         echo >&2 "WORKSPACE: $PADOGRID_WORKSPACE"
-         echo >&2 -e "    ${CError}ERROR:${CNone} Invalid value: prometheus.metrics.emission=$PROMETHEUS_METRICS_EMISSION. Valid values are Default, All, or None."
-         echo >&2 "           Set 'prometheus.metrics.emission' in the following cluster.properties file."  
-         echo >&2 "           $ETC_DIR/cluster.properties"
-         echo >&2 "           Command aborted."
-         echo >&2 "----------------------------------------------------------------"
-         exit 1
+      if [ $PRODUCT_MAJOR_VERSION -ge 10 ] && [ $PRODUCT_MINOR_VERSION -ge 1 ]; then
+         PROMETHEUS_METRICS_EMISSION=`getClusterProperty "prometheus.metrics.emission" $DEFAULT_PROMETHEUS_METRICS_EMISSION`
+         if [ "$PROMETHEUS_METRICS_EMISSION" != "Default" ] && [ "$PROMETHEUS_METRICS_EMISSION" != "All" ] && [ "$PROMETHEUS_METRICS_EMISSION" != "None" ]; then
+            echo >&2 "----------------------------------------------------------------"
+            echo >&2 "WORKSPACE: $PADOGRID_WORKSPACE"
+            echo >&2 -e "    ${CError}ERROR:${CNone} Invalid value: prometheus.metrics.emission=$PROMETHEUS_METRICS_EMISSION. Valid values are Default, All, or None."
+            echo >&2 "           Set 'prometheus.metrics.emission' in the following cluster.properties file."  
+            echo >&2 "           $ETC_DIR/cluster.properties"
+            echo >&2 "           Command aborted."
+            echo >&2 "----------------------------------------------------------------"
+            exit 1
+         fi
+         JAVA_OPTS="$JAVA_OPTS --J=-Dgemfire.prometheus.metrics.emission=$PROMETHEUS_METRICS_EMISSION --J=-Dgemfire.prometheus.metrics.port=$PROMETHEUS_PORT"
+      else
+         JAVA_OPTS="$JAVA_OPTS --J=-javaagent:$PROMETHEUS_JAR_PATH=$PROMETHEUS_PORT:$PROMETHEUS_CONFIG_FILE_PATH"
       fi
-      JAVA_OPTS="$JAVA_OPTS --J=-Dgemfire.prometheus.metrics.emission=$PROMETHEUS_METRICS_EMISSION --J=-Dgemfire.prometheus.metrics.port=$PROMETHEUS_PORT"
    else
       JAVA_OPTS="$JAVA_OPTS --J=-javaagent:$PROMETHEUS_JAR_PATH=$PROMETHEUS_PORT:$PROMETHEUS_CONFIG_FILE_PATH"
    fi
