Added support for GemFire prometheus metrics

diff --git a/padogrid-deployment/src/main/resources/geode/bin_sh/start_member b/padogrid-deployment/src/main/resources/geode/bin_sh/start_member
--- a/padogrid-deployment/src/main/resources/geode/bin_sh/start_member
+++ b/padogrid-deployment/src/main/resources/geode/bin_sh/start_member
@@ -128,7 +128,7 @@ if [ "$REMOTE_SPECIFIED" == "false" ]; then
       if [ "$STANDALONE" != "true" ] && [ "$VM_LOCATOR_HOSTS" == "" ]; then
          echo >&2 "----------------------------------------------------------------"
          echo >&2 "WORKSPACE: $PADOGRID_WORKSPACE"
-         echo >&2 "    ERROR: VM locator hosts undefined. Set 'vm.locator.hosts' in the following cluster.properties file."  
+         echo >&2 -e "    ${CError}ERROR:${CNone} VM locator hosts undefined. Set 'vm.locator.hosts' in the following cluster.properties file."  
          echo >&2 "           $ETC_DIR/cluster.properties"
          echo >&2 "           Command aborted."
          echo >&2 "----------------------------------------------------------------"
@@ -138,7 +138,7 @@ if [ "$REMOTE_SPECIFIED" == "false" ]; then
       if [ "$VM_HOSTS" == "" ]; then
          echo >&2 "----------------------------------------------------------------"
          echo >&2 "WORKSPACE: $PADOGRID_WORKSPACE"
-         echo >&2 "    ERROR: VM hosts undefined. Set 'vm.hosts' in the following cluster.properties file."  
+         echo >&2 -e "    ${CError}ERROR:${CNone} VM hosts undefined. Set 'vm.hosts' in the following cluster.properties file."  
          echo >&2 "           $ETC_DIR/cluster.properties"
          echo >&2 "           Command aborted."
          echo >&2 "----------------------------------------------------------------"
@@ -181,7 +181,7 @@ if [ "$REMOTE_SPECIFIED" == "false" ]; then
          FIRST_NUMBER=1
          LAST_NUMBER=$__MEMBER_NUMBER
          if [ "$__FOUND" == "false" ]; then
-            echo >&2 "ERROR: Invalid member number. Valid range is [$FIRST_NUMBER, $LAST_NUMBER]. Command aborted." 
+            echo >&2 -e "${CError}ERROR:${CNone} Invalid member number. Valid range is [$FIRST_NUMBER, $LAST_NUMBER]. Command aborted." 
          fi
       else
          # If private hosts are not reachable then use a public host as a proxy to execute this command.
@@ -259,7 +259,7 @@ if [ "$VM_ENABLED" == "true" ]; then
    if [ "$VM_LOCATOR_HOSTS" == "" ]; then
       echo >&2 "----------------------------------------------------------------"
       echo >&2 "WORKSPACE: $PADOGRID_WORKSPACE"
-      echo >&2 "    ERROR: VM locator hosts undefined. Set 'vm.locator.hosts' in the following cluster.properties file."  
+      echo >&2 -e "    ${CError}ERROR:${CNone} VM locator hosts undefined. Set 'vm.locator.hosts' in the following cluster.properties file."  
       echo >&2 "           $ETC_DIR/cluster.properties"
       echo >&2 "           Command aborted."
       echo >&2 "----------------------------------------------------------------"
@@ -269,7 +269,7 @@ if [ "$VM_ENABLED" == "true" ]; then
    if [ "$VM_HOSTS" == "" ]; then
       echo >&2 "----------------------------------------------------------------"
       echo >&2 "WORKSPACE: $PADOGRID_WORKSPACE"
-      echo >&2 "    ERROR: VM hosts undefined. Set 'vm.hosts' in the following cluster.properties file."  
+      echo >&2 -e "    ${CError}ERROR:${CNone} VM hosts undefined. Set 'vm.hosts' in the following cluster.properties file."  
       echo >&2 "           $ETC_DIR/cluster.properties"
       echo >&2 "           Command aborted."
       echo >&2 "----------------------------------------------------------------"
@@ -433,6 +433,7 @@ JAVA_OPTS="$JAVA_OPTS ${DEBUG}"
 # Set PROMETHEUS paths
 PROMETHEUS_ENABLED=`getClusterProperty "prometheus.enabled" $DEFAULT_PROMETHEUS_ENABLED`
 if [ "$PROMETHEUS_ENABLED" == "true" ]; then
+   PROMETHEUS_GEMFIRE_ENABLED=`getClusterProperty "prometheus.gemfire.enabled" $DEFAULT_PROMETHEUS_GEMFIRE_ENABLED`
    PROMETHEUS_START_PORT=`getClusterProperty "prometheus.startPort" $DEFAULT_PROMETHEUS_START_PORT`
    if [ "$POD" == "local" ]; then
       let PROMETHEUS_PORT=PROMETHEUS_START_PORT+MEMBER_NUMBER-1
@@ -448,7 +449,22 @@ if [ "$PROMETHEUS_ENABLED" == "true" ]; then
       # Remove the disk drive letter from the path. A workaround to a bug in the prometheus exporter.
       PROMETHEUS_CONFIG_FILE_PATH=${PROMETHEUS_CONFIG_FILE_PATH:2}
    fi
-   JAVA_OPTS="$JAVA_OPTS --J=-javaagent:$PROMETHEUS_JAR_PATH=$PROMETHEUS_PORT:$PROMETHEUS_CONFIG_FILE_PATH"
+   if [ "$PROMETHEUS_GEMFIRE_ENABLED" == "true" ]; then
+      PROMETHEUS_METRICS_EMISSION=`getClusterProperty "prometheus.metrics.emission" $DEFAULT_PROMETHEUS_METRICS_EMISSION`
+      if [ "$PROMETHEUS_METRICS_EMISSION" != "Default" ] && [ "$PROMETHEUS_METRICS_EMISSION" != "All" ] && [ "$PROMETHEUS_METRICS_EMISSION" != "None" ]; then
+         echo >&2 "----------------------------------------------------------------"
+         echo >&2 "WORKSPACE: $PADOGRID_WORKSPACE"
+         echo >&2 -e "    ${CError}ERROR:${CNone} Invalid value: prometheus.metrics.emission=$PROMETHEUS_METRICS_EMISSION. Valid values are Default, All, or None."
+         echo >&2 "           Set 'prometheus.metrics.emission' in the following cluster.properties file."  
+         echo >&2 "           $ETC_DIR/cluster.properties"
+         echo >&2 "           Command aborted."
+         echo >&2 "----------------------------------------------------------------"
+         exit 1
+      fi
+      JAVA_OPTS="$JAVA_OPTS --J=-Dgemfire.prometheus.metrics.emission=$PROMETHEUS_METRICS_EMISSION --J=-Dgemfire.prometheus.metrics.port=$PROMETHEUS_PORT"
+   else
+      JAVA_OPTS="$JAVA_OPTS --J=-javaagent:$PROMETHEUS_JAR_PATH=$PROMETHEUS_PORT:$PROMETHEUS_CONFIG_FILE_PATH"
+   fi
 else
    PROMETHEUS_PORT="Disabled"
 fi
