Updated old error message

diff --git a/padogrid-deployment/src/main/resources/none/bin_sh/add_member b/padogrid-deployment/src/main/resources/none/bin_sh/add_member
--- a/padogrid-deployment/src/main/resources/none/bin_sh/add_member
+++ b/padogrid-deployment/src/main/resources/none/bin_sh/add_member
@@ -183,9 +183,8 @@ if [ "$REMOTE_SPECIFIED" == "false" ]; then
 fi
 
 if [ "$PRODUCT" == "" ] || [ "$PRODUCT" == "none" ]; then
-   echo -e "${CLightRed}ERROR:${CNone} Product undefined. Switch to a cluster that has a product configured"
-   echo "       or run 'update_product' to add a product and run 'make_cluster' to create"
-   echo "       a new cluster. Command aborted."
+   echo >&2 -e "${CLightRed}ERROR:${CNone} Product undefined. Switch to a cluster that has a product configured."
+   echo >&2 "       Command aborted."
    exit 1
 fi
 
diff --git a/padogrid-deployment/src/main/resources/none/bin_sh/stop_cluster b/padogrid-deployment/src/main/resources/none/bin_sh/stop_cluster
--- a/padogrid-deployment/src/main/resources/none/bin_sh/stop_cluster
+++ b/padogrid-deployment/src/main/resources/none/bin_sh/stop_cluster
@@ -73,9 +73,8 @@ fi
 retrieveClusterEnvFile $PADOGRID_WORKSPACE/clusters/$CLUSTER
 
 if [ "$PRODUCT" == "" ] || [ "$PRODUCT" == "none" ]; then
-   echo >&2 -e "${CLightRed}ERROR:${CNone} Product undefined. Switch to a cluster that has a product configured"
-   echo >&2 "       or run 'update_product' to add a product and run 'make_cluster' to create"
-   echo >&2 "       a new cluster. Command aborted."
+   echo >&2 -e "${CLightRed}ERROR:${CNone} Product undefined. Switch to a cluster that has a product configured."
+   echo >&2 "       Command aborted."
    exit 1
 fi
 
